fix(ios): multiple keyboard slide-in animations on app start
keymanapp/keyman pull request #10362
Opened 2024-01-11 04:59 UTC by jahorton

Heavily mitigates #9211.

While there will still be a very slight bit of layout-shift that still occurs, this eliminates the multiple slide-in animations for the keyboard that appear at app start.

How it looks now, in Simulator:

![app load](https://github.com/keymanapp/keyman/assets/25213402/15348c14-61f1-4659-a5fc-df18f76b54e3)

Notice the subtle shift in the keys near the end of the GIF - that's the "slight bit of layout shift" I was referring to.

The likely reason for this:

![image](https://github.com/keymanapp/keyman/assets/25213402/a2e927d8-be23-4bde-b888-715aab449292)

Note the timing of `kmwosk.css` in the Network tab; it loads relatively late in the process... as does the OSK font.  Though... symbols from the font are actually showing up _before_ the shift, so I'm not fully confident that this delay is the cause.

2024-01-11 05:57 UTC, mcdurdin commented
> I am a bit concerned that the code being removed might have a side-effect I'm not anticipating, but this is, by far, the easiest way to smooth out this aspect of app init.

I am very concerned about that. Problem is, the reason for the change is lost in the mists of time. It was added in [v2.3.102](https://github.com/keymanapp/archive-keyman-ios/commit/ed6c8e562ce4c6a9e641d472bc77b135a63f82e2#diff-8698606bd3aa4dc48692b346d35bdb7d57991dd7decad7b93945ed88f59837a8R315), for which we have no version history detail, as far as I can tell.

So this change does need some significant regression testing to verify that it isn't a hacky workaround to some state problem, which seems the most likely reason it appeared in 2015 in the first place!

Note: this same pattern is also in TextField.swift.

2024-01-11 06:00 UTC, jahorton commented
> Note: this same pattern is also in TextField.swift.

Good catch.

2024-01-17 05:36 UTC, mcdurdin requested changes
We'll hopefully catch in beta any subtle new issues with this change. I agree this is better than playing a resign+become shuffle, but I do wonder why this was needed. Note: it may well be something from an old version of iOS that is no longer relevant.

2024-01-17 05:36 UTC, mcdurdin commented on ios/engine/KMEI/KeymanEngine/Classes/TextView.swift
> -    }
This needs to be replicated in TextField.swift

2024-01-18 05:21 UTC, mcdurdin approved these changes

2024-01-18 14:27 UTC, bharanidharanj commented
# Test Results

* **TEST_IOS_APP_START (PASSED):** Tested with the attached PR build (Keyman 17.0.242-alpha-test-10362) in the iPhone 13 mobile device and here is my observation: 1. Rapidly typed some texts on the text input screen. Switched to the Khmer_Angkor keyboard and proceeded with the typing. 2. Installed another keyboard (ipa_sil) using the settings menu. 3. Again typing rapidly on the text screen. Swapped the keyboard then proceeded with the typing. Did not find any issues during the process.

2024-01-19 01:02 UTC, merged

2024-01-19 18:05 UTC, keyman-server commented
Changes in this pull request will be available for download in [Keyman version 17.0.248-alpha](https://keyman.com/downloads/releases/alpha/17.0.248)