feat(web): bulk_render variant - loads and renders keyboards from local KMP
keymanapp/keyman pull request #10432
Opened 2024-01-18 04:05 UTC by jahorton

The existing KMW OSK bulk-renderer engine fetches all keyboards from our cloud servers.  What if we'd rather run it against a local version of a keyboard instead?

Introducing a new variant of the bulk-renderer - a local _package_ renderer!  The easiest solution for specifying and finding all relevant components for a perfect render of local keyboard files - particularly, for the _fonts_ - was to use a package's kmp.json as the lynchpin.

I've also always wanted to try loading a keyboard from a KMP for KeymanWeb, and this _is_ a separate, dev-only child project, so it seemed like the perfect opportunity - especially since it renders nice, consistently-sized PNGs, and I need to update some for a keyboard I'm adding gestures to.

As packages are selected for use, they're automatically added to KMW - there's little preventing a user from loading multiple KMPs for a batch run of multiple KMP-based Web keyboards.

@keymanapp-test-bot skip

2024-01-18 09:58 UTC, ermshiperete requested changes

2024-01-18 09:58 UTC, ermshiperete commented on web/src/tools/testing/bulk_rendering/local-renderer.html
> +                    source: [dFontData]
```suggestion
                    source: [oFontData]
```

2024-01-18 17:52 UTC, jahorton commented on web/src/tools/testing/bulk_rendering/local-renderer.html
> +            const rawMetadata = await metadataFile.getData(new zip.TextWriter());
Yeah, I thought their nomenclature was weird, too.  At least the guide for that package was very straightforward.

2024-01-18 17:59 UTC, ermshiperete approved these changes

2024-06-12 05:56 UTC, merged

2024-06-12 18:02 UTC, keyman-server commented
Changes in this pull request will be available for download in [Keyman version 18.0.54-alpha](https://keyman.com/downloads/releases/alpha/18.0.54)