fix(common): specify title explicitly when opening PR with hub
keymanapp/keyman pull request #11173
Opened 2024-04-05 02:21 UTC by mcdurdin

Fixes #11125.

Discussion in #11125; looks like it may be due to a race in hub?

@keymanapp-test-bot skip

2024-04-05 11:21 UTC, ermshiperete submitted a review, later dismissed
As requested for testing purposes :smile:

2024-04-05 15:39 UTC, srl295 requested changes
Keep the change!

2024-04-11 21:56 UTC, srl295 approved these changes

2024-04-11 21:57 UTC, mcdurdin commented
The test worked on status.keyman.com, so am happy for this to be approved now :grin: (see keymanapp/status.keyman.com#442)

2024-04-11 21:57 UTC, merged

2024-04-12 18:04 UTC, keyman-server commented
Changes in this pull request will be available for download in [Keyman version 17.0.307-beta](https://keyman.com/downloads/releases/beta/17.0.307)