chore(ios): support build on Apple Silicon using Xcode 15.3
keymanapp/keyman pull request #11302
Opened 2024-04-25 08:09 UTC by sgschantz

Several changes to get Keyman for iOS and macOS building on Apple Silicon on macOS Sonoma with the latest version of Xcode 15.3.

Most significantly, **the minimum supported version of macOS had to be increased from 10.10 (Yosemite) to 10.13 (High Sierra)**.

Fixes #10671

2024-04-26 01:50 UTC, mcdurdin commented on resources/build/set-bundle-versions-and-settings.sh
> +#!/bin/bash
```suggestion
#!/usr/bin/env bash
```

We should be using `env` throughout to signify that we want the bash version from the path, even though we are attempting to run the scripts with the correct version of bash.

2024-04-26 03:51 UTC, jahorton approved these changes
LGTM.

That said, the minimum version increase, _this_ late in the game... makes me wonder if we should do a first release before the update lands, then follow up with this one.

Then again, if anything feels broken with the release... we probably don't want to leave users with 10.10 - 10.12 out to dry.  So we probably shouldn't use it as a reason, even if it's unfortunate to shift minimum-requirements despite the prior announcement.

https://community.software.sil.org/t/keyman-17-0-beta-release/8388

> - Minimum supported version of macOS is 10.10 Yosemite.

2024-04-26 05:18 UTC, mcdurdin requested changes
Nits, plus the change from #!/bin/bash to #!/usr/bin/env bash for all the build scripts. But looking good.

* We should use resources/build/mac/ folder for the "embedded" scripts?
* We need to update the oem/fv xcodeproj as well
* Several of the embedded shellscripts have not yet been extracted. We need to do the wrapping for all the scripts in the xcodeproj files.

2024-04-26 05:18 UTC, mcdurdin commented on mac/help/about/requirements.md
> +Mac OS X 10.13 or later should be able to run Keyman for macOS without trouble.
```suggestion
macOS 10.13 or later should be able to run Keyman for macOS without trouble.
```

2024-04-26 05:18 UTC, mcdurdin commented on mac/help/common/requirements.md
> +Mac OS X 10.13 or later should be able to run Keyman for macOS without trouble.
```suggestion
macOS 10.13 or later should be able to run Keyman for macOS without trouble.
```

2024-04-26 07:33 UTC, mcdurdin commented
Note re sentry update:

chore(mac): upgrade sentry pod to 8.24.0

Existing version of Sentry pod, 5.x, had a mac deployment
target of 10.10, but with the upgrade to XCode 1111.66, we
must have a minimum target of 10.13. The min target came in
with sentry 8.0.0, but we opted to go straight to the latest
released minor version in 8.0 series.

This forced an update to cocoapods to support visionos, and
that forced an upgrade of Ruby away from the macOS supplied
2.6.8 to 3.3.1.

Used https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/ 
to upgrade, seemed to work.

2024-04-28 22:10 UTC, mcdurdin commented
> That said, the minimum version increase, _this_ late in the game... makes me wonder if we should do a first release before the update lands, then follow up with this one.
> 
> Then again, if anything feels broken with the release... we probably don't want to leave users with 10.10 - 10.12 out to dry. So we probably shouldn't use it as a reason, even if it's unfortunate to shift minimum-requirements despite the prior announcement.

Yes, better to change minimum version in beta than in 17.0-stable cycle. In any case, we don't have a choice here because we were not ready to release before Apple's deadline.

2024-04-28 22:57 UTC, mcdurdin commented
iOS Sample and Test Projects build failure:

https://build.palaso.org/buildConfiguration/Keyman_iOS_TestSamplesAndTestProjects/458641?buildTab=log&linesState=84&logView=flowAware&focusLine=909

```
/Users/marc_durdin/buildAgent/work/99b311828f4ee7c/keyman/ios/samples/KMSample1/build/KMSample1.build/Debug-iphoneos/KMSample1.build/DerivedSources/GeneratedAssetSymbols.swift:84:10: error: Type Name Violation: Type name '_ACResourceInitProtocol' should only contain alphanumeric and other allowed characters (type_name)
```

2024-04-28 23:19 UTC, mcdurdin commented
Note: iOS build is running afoul of:

* #11061

altool is returning the same error 149,727 times ... hmm.

It may be that this is causing the next step to fail.

Temporary mitigation: adding a hosts entry for northamerica-1.object-storage.apple.com

2024-04-29 00:55 UTC, darcywong00 commented
Eventually we should also update
https://github.com/keymanapp/keyman/blob/master/docs/build/macos.md#prerequisites

2024-04-29 00:59 UTC, mcdurdin commented
iOS build failure (upload to TestFlight for FVKeyboards) seems to be versioning-related and exposed by changes in XCode 15.0.

https://github.com/fastlane/fastlane/discussions/20743

https://build.palaso.org/buildConfiguration/Keyman_iOS_TestPullRequests/458644?buildTab=log&linesState=2747.2799&logView=flowAware&focusLine=2830

```
WARN [2024-04-28 16:42:28.14]:  [33m[altool] 2024-04-28 16:42:28.139 *** Error: The provided entity includes an attribute with a value that has already been used The bundle version must be higher than the previously uploaded version: ‘200’. (ID: d9ee2dd3-47d4-4c25-9e01-9c538b265c9e) (-19232)
```

2024-04-29 02:50 UTC, jahorton commented
```
06:42:28   WARN [2024-04-28 16:42:28.14]: [altool]     NSLocalizedDescription = "The provided entity includes an attribute with a value that has already been used";
06:42:28   
06:42:28   WARN [2024-04-28 16:42:28.14]: [altool]     NSLocalizedFailureReason = "The bundle version must be higher than the previously uploaded version: \U2018200\U2019. (ID: d9ee2dd3-47d4-4c25-9e01-9c538b265c9e)";
06:42:28   
06:42:28   WARN [2024-04-28 16:42:28.14]: [altool]     NSUnderlyingError = "Error Domain=IrisAPI Code=-19241 \"The provided entity includes an attribute with a value that has already been used\" UserInfo={status=409, detail=The bundle version must be higher than the previously uploaded version., source={\n    pointer = \"/data/attributes/cfBundleVersion\";\n}, id=d9ee2dd3-47d4-4c25-9e01-9c538b265c9e, code=ENTITY_ERROR.ATTRIBUTE.INVALID.DUPLICATE, title=The provided entity includes an attribute with a value that has already been used, meta={\n    previousBundleVersion = 200;\n}, NSLocalizedDescription=The provided entity includes an attribute with a value that has already been used, NSLocalizedFailureReason=The bundle version must be higher than the previously uploaded version.}";
```

`\U2018200\U2019` is mentioned as version in one part of the message, but that doesn't look like a version string to me.  Then again... `\u2018` is... [the left-side single-quote](https://www.compart.com/en/unicode/U+2018).  So, basically, it _is_ just reading `'200'` from somewhere, but with curly quotes.

Wait a sec... it failed for the FV app, but not ours.

https://github.com/keymanapp/keyman/blob/5b1a4f08e4180ccb5b27baea47ef39f4f3cf2300/oem/firstvoices/ios/FirstVoices/Info.plist#L21-L22

I think the block linked above is not being properly updated, for whatever reason.

2024-05-02 03:19 UTC, mcdurdin approved these changes
LGTM. A bunch of tidyup work that we should do in 18.0 cycle. I've marked the comments as A18S1 to indicate that we should do them while this is still fresh and early in the dev cycle, but A18S2 also fits well.

2024-05-02 03:19 UTC, mcdurdin commented on ios/keyman/Keyman/Keyman.xcodeproj/project.pbxproj
> +			shellScript = "#verstr1=$(/usr/libexec/PlistBuddy -c \"Print CFBundleShortVersionString\" \"$SRCROOT/Keyman-Info.plist\")\n#verstr2=$(/usr/libexec/PlistBuddy -c \"Print CFBundleVersion\" \"$SRCROO
This call to swiftlint should be cleaned up into a wrapped script as well in 18.0 (A18S1), and commented lines should be removed.

2024-05-02 03:19 UTC, mcdurdin commented on ios/keyman/Keyman/Keyman.xcodeproj/project.pbxproj
> +			shellScript = ". \"$KEYMAN_ROOT/resources/build/xcode-utils.sh\"\n\nif [ ${UPLOAD_SENTRY:-false} = true ]; then\n  # Calls resource script to perform the dSYM upload\n  \"$KEYMAN_ROOT/resources/bu
The `if` test should be inside the sentry-dsym-upload.sh script so that the shellScript is a pure wrapped call to the script (A18S1).

2024-05-02 03:19 UTC, mcdurdin commented on mac/Keyman4MacIM/Keyman-template.dmg
Size has been increased due to larger binaries from XCode 15.3 and/or dependencies.

2024-05-02 03:19 UTC, mcdurdin commented on oem/firstvoices/ios/FirstVoices.xcodeproj/project.pbxproj
> +			shellScript = "#verstr1=$(/usr/libexec/PlistBuddy -c \"Print CFBundleShortVersionString\" \"$SRCROOT/FirstVoices/Info.plist\")\n#verstr2=$(/usr/libexec/PlistBuddy -c \"Print CFBundleVersion\" \"$S
This script should be removed in 18.0 cycle (A18S1).

2024-05-02 03:19 UTC, mcdurdin commented on resources/build/sentry-dsym-upload.sh
All these scripts should be in resources/build/mac in 18.0 (A18S1)

2024-05-02 03:19 UTC, mcdurdin commented on resources/build/set-bundle-versions-and-settings-tagged.sh
It would be good to combine all the set-bundle-versions-... scripts and parameterise, given they are so similar. A18S1

2024-05-02 03:19 UTC, mcdurdin commented on resources/build/xcode-utils.sh
Let's see if we can move this to resources/build/mac as well A18S1

2024-05-02 03:19 UTC, mcdurdin commented on resources/build/xcode-wrap.sh
Let's see if we can move this to resources/build/mac as well A18S1

2024-05-02 04:31 UTC, merged

2024-05-02 18:04 UTC, keyman-server commented
Changes in this pull request will be available for download in [Keyman version 17.0.318-beta](https://keyman.com/downloads/releases/beta/17.0.318)