Chore/common/10183-unicode-version
keymanapp/keyman pull request #11418
Opened 2024-05-11 01:03 UTC by srl295

- load versions from node and ICU4C++ and Blocks.txt

Fixes: #10183

@keymanapp-test-bot skip

2024-05-11 01:04 UTC, srl295 commented
Example output

```
= test_all
== load_json loading tests/unit/ldml/nodeversions.json
== load_json loading ../../../../package.json
== test_unicode_versions
cxx_icu	73.1
cxx_icu_unicode	15.0
node_icu_unicode	15.0
node	18.16.0
node_icu	72.1
node_engine	^18.x
block_unicode_ver	15.1.0.txt
```

2024-05-13 14:45 UTC, srl295 commented
So linux is using ICU from the environment, which only supports Unicode 14 not 15.

```
  stdout:
20:08:09   = test_all
20:08:09   == load_json loading tests/unit/ldml/nodeversions.json
20:08:09   == load_json loading ../../../../package.json
20:08:09   == test_unicode_versions
20:08:09   cxx_icu  70.1
20:08:09   cxx_icu_unicode  14.0
20:08:09   node_icu_unicode  15.0
20:08:09   node  18.17.1
20:08:09   node_icu  73.1
20:08:09   node_engine  ^18.x
20:08:09   block_unicode_ver  15.1.0.txt
20:08:09   stderr:
20:08:09   Test failed at ../../../tests/unit/ldml/test_unicode.cpp:110:
20:08:09   expected: 14
20:08:09   actual:   15
```

2024-05-13 23:17 UTC, srl295 commented
> So linux is using ICU from the environment, which only supports Unicode 14 not 15.
> 
> ```
>   stdout:
> 20:08:09   = test_all
> 20:08:09   == load_json loading tests/unit/ldml/nodeversions.json
> 20:08:09   == load_json loading ../../../../package.json
> 20:08:09   == test_unicode_versions
> 20:08:09   cxx_icu  70.1
> 20:08:09   cxx_icu_unicode  14.0
> 20:08:09   node_icu_unicode  15.0
> 20:08:09   node  18.17.1
> 20:08:09   node_icu  73.1
> 20:08:09   node_engine  ^18.x
> 20:08:09   block_unicode_ver  15.1.0.txt
> 20:08:09   stderr:
> 20:08:09   Test failed at ../../../tests/unit/ldml/test_unicode.cpp:110:
> 20:08:09   expected: 14
> 20:08:09   actual:   15
> ```

I'm going to take out the assert for the cxx_icu version, for now.

2024-05-14 15:06 UTC, srl295 commented
all working but wasm

2024-05-23 22:44 UTC, srl295 commented
OK ptal, web unrelated?

2024-05-24 02:52 UTC, mcdurdin requested changes
Looks fine, just small nits

2024-05-24 02:52 UTC, mcdurdin commented on core/tests/unit/ldml/meson.build
> +keyboard_build_path = join_paths(meson.current_build_dir(),'keyboards')
```suggestion
keyboard_build_path = meson.current_build_dir() / 'keyboards'
```

It's cleaner to use `/` now in meson path construction

2024-05-24 02:52 UTC, mcdurdin commented on core/tests/unit/ldml/meson.build
> +tc = executable('test_context_normalization',
```suggestion
test_context_normalization = executable('test_context_normalization',
```

Can we use the full process name as the variable name? Makes future maintenance so much easier

2024-05-24 02:52 UTC, mcdurdin commented on core/tests/unit/ldml/meson.build
> +u = executable('test_unicode', 'test_unicode.cpp',
```suggestion
test_unicode = executable('test_unicode', 'test_unicode.cpp',
```

Ditto

2024-05-26 22:48 UTC, mcdurdin approved these changes

2024-05-26 22:50 UTC, mcdurdin commented
@ermshiperete the API Verification build is failing, any ideas why? Log is inconclusive.

2024-05-27 10:29 UTC, ermshiperete commented
> @ermshiperete the API Verification build is failing, any ideas why? Log is inconclusive.

Ignore the API Verification for now. I thought it would work, but I must be overlooking something and it's still not working. I'll add a step to always greenbar until that's solved. Sorry for the noise.

2024-05-27 10:32 UTC, ermshiperete commented
> Example output
> 
> ```
> = test_all
> == load_json loading tests/unit/ldml/nodeversions.json
> == load_json loading ../../../../package.json
> == test_unicode_versions
> cxx_icu	73.1
> cxx_icu_unicode	15.0
> node_icu_unicode	15.0
> node	18.16.0
> node_icu	72.1
> node_engine	^18.x
> block_unicode_ver	15.1.0.txt
> ```

I'm wondering if it would be better to change the order of the output so that all ICU versions are together, all Unicode versions are together etc. ? That way it would be easier to spot which versions should be the same.

2024-05-27 13:25 UTC, srl295 commented
> > Example output
> > ```
> > = test_all
> > == load_json loading tests/unit/ldml/nodeversions.json
> > == load_json loading ../../../../package.json
> > == test_unicode_versions
> > cxx_icu	73.1
> > cxx_icu_unicode	15.0
> > node_icu_unicode	15.0
> > node	18.16.0
> > node_icu	72.1
> > node_engine	^18.x
> > block_unicode_ver	15.1.0.txt
> > ```
> 
> I'm wondering if it would be better to change the order of the output so that all ICU versions are together, all Unicode versions are together etc. ? That way it would be easier to spot which versions should be the same.

Good idea. Maybe with some explanatory text, even.

I think I'll do this as a separate PR since this stack is getting longer.

2024-05-27 13:25 UTC, merged

2024-05-27 18:05 UTC, keyman-server commented
Changes in this pull request will be available for download in [Keyman version 18.0.45-alpha](https://keyman.com/downloads/releases/alpha/18.0.45)

2024-05-27 21:45 UTC, srl295 commented
> > Example output
> > ```
> > = test_all
> > == load_json loading tests/unit/ldml/nodeversions.json
> > == load_json loading ../../../../package.json
> > == test_unicode_versions
> > cxx_icu	73.1
> > cxx_icu_unicode	15.0
> > node_icu_unicode	15.0
> > node	18.16.0
> > node_icu	72.1
> > node_engine	^18.x
> > block_unicode_ver	15.1.0.txt
> > ```
> 
> I'm wondering if it would be better to change the order of the output so that all ICU versions are together, all Unicode versions are together etc. ? That way it would be easier to spot which versions should be the same.

https://github.com/keymanapp/keyman/pull/11572

2024-05-29 05:31 UTC, keyman-server commented
Changes in this pull request will be available for download in [Keyman version 18.0.45-alpha](https://keyman.com/downloads/releases/alpha/18.0.45)

2024-05-30 00:56 UTC, keyman-server commented
Changes in this pull request will be available for download in [Keyman version 18.0.45-alpha](https://keyman.com/downloads/releases/alpha/18.0.45)

2024-05-30 21:40 UTC, keyman-server commented
Changes in this pull request will be available for download in [Keyman version 18.0.45-alpha](https://keyman.com/downloads/releases/alpha/18.0.45)

2024-05-31 19:21 UTC, keyman-server commented
Changes in this pull request will be available for download in [Keyman version 18.0.45-alpha](https://keyman.com/downloads/releases/alpha/18.0.45)

2024-05-31 23:06 UTC, keyman-server commented
Changes in this pull request will be available for download in [Keyman version 18.0.45-alpha](https://keyman.com/downloads/releases/alpha/18.0.45)

2024-05-31 23:24 UTC, keyman-server commented
Changes in this pull request will be available for download in [Keyman version 18.0.45-alpha](https://keyman.com/downloads/releases/alpha/18.0.45)