fix(android): keyboard sizing on orientation change
keymanapp/keyman pull request #11484
Opened 2024-05-20 09:09 UTC by jahorton

2024-05-20 09:11 UTC, jahorton commented on android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java
> +    // Note: this func always has a reference to app context b/c class field.
```suggestion
```

2024-05-20 09:11 UTC, jahorton commented on android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java
> +    // view hierarchy (after ensuring that it's removed from a prior one if applicable)
```suggestion
```

2024-05-20 09:11 UTC, jahorton commented on android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java
> +    int kbWidth = (int) (dms.widthPixels / dms.density);
This specific line - `kbWidth` - has two other instances in the codebase already.  This simply makes a third.

2024-05-23 00:23 UTC, darcywong00 commented on android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java
> +  public static int detectOrientation(Context context) {
We probably need to keep the API call getOrientation() which can just call detectOrientation()

Documentation wip on keymanapp/help.keyman.com#1270

2024-05-24 07:23 UTC, mcdurdin reviewed
Rather than approving these changes, I think I will install and use this PR build on my phone for a few days. I experience the OSK height issues most days, so that should be enough to tell us if the patch improves the situation.

2024-05-24 09:39 UTC, dinakaranr commented
# Test Results
I tested this issue with the attached "Keyman 18.0.39-alpha-test-11484" build on an Android 12 & 13 & 14 emulator & physical environment: Here is my observation.
Installed the "Keyman 18.0.39.apk" file and gave all permissions to the application.
Checked the "Enable Keyman as system-wide keyboard" and set the keyboard as the default keyboard box on the settings page.

* **TEST_OSK (PASSED):** - I have followed acceptance steps. OSK works after selecting a default keyboard on the "Keyboard Picker" menu. Hence OSK appears in full width on OSK.

* **TEST_LANDSCAPE_KEYBOARD_PICKER (PASSED):** - I have followed acceptance steps. OSK works after changing the keyboard height. OSK appeared in full width & height after selecting a default keyboard on the "Keyboard picker" menu.

* **TEST_OSK_ROTATION_ANDROID_12 (PASSED):** - I have followed acceptance steps. OSK appeared in full width & height after selecting a default keyboard on the "Keyboard picker" menu. I tried to change the Portrait to Landscape and Landscape to Portrait view and OSK always displays with the correct width & height. It works correctly after repeating steps more than 10 times.

* **TEST_OSK_ROTATION_ANDROID_13 (PASSED):** - I have followed acceptance steps. I tried to change the view from Portrait to Landscape and Landscape to Portrait and OSK always displays with the correct width & height. It works correctly after repeating steps more than 10 times.

2024-05-24 09:47 UTC, mcdurdin commented
![Screenshot_20240524_164517_WhatsApp.jpg](https://github.com/keymanapp/keyman/assets/4498365/c7c662a3-ce98-42e0-b102-ef6a81b83699)

![Screenshot_20240524_164525_WhatsApp.jpg](https://github.com/keymanapp/keyman/assets/4498365/778ff0c7-ca43-438b-a810-e0f8cebc1602)

sadly... Probably worse than before.

2024-05-24 23:42 UTC, mcdurdin commented
![Screenshot_20240524_164517_WhatsApp.jpg](https://github.com/keymanapp/keyman/assets/4498365/c7c662a3-ce98-42e0-b102-ef6a81b83699)

![Screenshot_20240524_164525_WhatsApp.jpg](https://github.com/keymanapp/keyman/assets/4498365/778ff0c7-ca43-438b-a810-e0f8cebc1602)

sadly... definitely worse than before. 

This update doesn't come good if I switch to another keyboard and back, unlike 17.0.325.

Rotation and restore are both broken.

In 17.0.325, rotation seems fine, and it is only restore that seems to sometimes go wrong. So I think we need to leave the rotation handler alone and look at the restore handler.

2024-05-28 23:36 UTC, mcdurdin requested changes
Marking as 'request changes' to take it out of the review queue -- given the issues noted in my earlier comments :grin:

2024-05-29 05:20 UTC, jahorton commented
> In 17.0.325, rotation seems fine, and it is only restore that seems to sometimes go wrong. So I think we need to leave the rotation handler alone and look at the restore handler.

This information looks to be very useful; that's more description than I think I had before.  Upon investigating the current code for `stable`, I have a question - does this ever occur in-app for you, or only with the system keyboard?

I happened to notice there's specific handling for this in-app that lacks a clear parallel in the system keyboard, and your answer would likely help clarify that and point me in the right direction.

2024-05-29 22:48 UTC, mcdurdin commented
> Upon investigating the current code for `stable`, I have a question - does this ever occur in-app for you, or only with the system keyboard?

I almost never use the in-app keyboard so don't have data to answer this question sorry.

> This information looks to be very useful; that's more description than I think I had before.

I've now linked this PR and #11604 to #10054 (the original issue I opened on this problem) for posterity. #10054 said this:

> I have not yet been able to figure out exactly what causes this, but sometimes when the OSK pops up on Android, the keyboard shows at the wrong size. Rotating the device seems to be the only way to address this.

2024-05-31 03:25 UTC, closed without merging

2024-05-31 03:25 UTC, jahorton commented
We're having far better success with #11604, so I'm closing this PR out now.