fix(web): properly pass test-runner verbose-logging flag
keymanapp/keyman pull request #11509
Opened 2024-05-23 04:02 UTC by jahorton

I'm not sure how it wasn't caught as part of the test-runner PRs, but the manner in which the verbose-logging flag (`--debug`) was being passed caused it to have a prepended space that had a nasty unintended side-effect breaking runs like this one: https://build.palaso.org/buildConfiguration/Keymanweb_TestPullRequests/465297?buildTab=log&linesState=719&logView=flowAware

@keymanapp-test-bot skip

2024-05-23 04:11 UTC, mcdurdin requested changes
Because the space really isn't a necessary component of the variable, a better fix would be to remove the space from the WTR_DEBUG flag on line 65:

```
WTR_DEBUG=--manual
```

And then leave the variable reference quoted on lines 70 and 72. That will avoid shell linting warnings

2024-05-23 07:13 UTC, jahorton commented
> And then leave the variable reference quoted on lines 70 and 72. That will avoid shell linting warnings

I don't know about that part - should the variable be changed to represent multiple CLI options, we'd want the variable expansion to resolve into multiple pieces.

I'll go ahead and trim off the prepended space, though.

2024-05-24 06:46 UTC, mcdurdin approved these changes

2024-05-24 06:47 UTC, merged

2024-05-24 18:05 UTC, keyman-server commented
Changes in this pull request will be available for download in [Keyman version 18.0.44-alpha](https://keyman.com/downloads/releases/alpha/18.0.44)