fix(android): fixes one case of incomplete error handling
keymanapp/keyman pull request #11580
Opened 2024-05-28 01:29 UTC by jahorton

Fixes #11561.

## User Testing

TEST_KBD_DOWNLOAD:  Use the in-app keyboard-search to find and install an existing keyboard that supports a lexical model.
- This is likely easiest from a fresh install, but is possible without that so long as the keyboard hasn't previously been downloaded.
- A few candidate keyboard IDs:
    - `khmer_angkor`
    - `gff_amharic`
    - `fv_sencoten`
    - `naijatype`
- Testing with one should be sufficient.
- If the keyboard fails to download, or fails to activate an associated lexical model when swapped to (after a brief wait), fail this test.

2024-05-28 04:16 UTC, mcdurdin requested changes
Two things here:

* state complexity
* a deeper question: why is `registerReceiver()` failing, and should we be retrying it?

## state complexity

This is just a code nit, but I am a little uncomfortable with the additional state complexity added here. I know the additional state variable is relatively simple, but it might be better to make `isInitialized` into an `initializationState` enumeration, something like (`NOT_INITIALIZED`, `STARTED_INITIALIZATION`, `REGISTERED`)?

This gives us:

isInit  |   hasReg   |   initializationState
----------|----------|----------------------
false | false | NOT_INITIALIZED
false | true  | \<does not exist\>
true | false | STARTED_INITIALIZATION
true | true | REGISTERED

IMO, this avoids having to maintain two variables in future and clarifies the initialization state machine.

## `registerReceiver()` and races

If, on the other hand, we want to retry calling `registerReceiver` (because I don't know why the first call failed), then we wouldn't need the additional state variable: you'd just move the `isInitialized = true;` statement up into the `try` block on line 78.

But there seems to be a deeper race condition here -- why is `initialize()` not called before `executeAsDownload()`? Should we be making `executeAsDownload()` into a synchronized method also? Is it possible that `executeAsDownload()` is starting while we are still in `initialize()` on another thread and that's causing the crash?

2024-05-28 05:09 UTC, jahorton commented
> But there seems to be a deeper race condition here -- why is `initialize()` not called before `executeAsDownload()`? 

There is a single class-external reference to `initialize` that I could find:

https://github.com/keymanapp/keyman/blob/aaa0c18ab63dd303a94d2de22d7071a1d003450c/android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java#L423

https://github.com/keymanapp/keyman/blob/aaa0c18ab63dd303a94d2de22d7071a1d003450c/android/KMEA/app/src/main/java/com/keyman/engine/KMManager.java#L447

This _is_ notably early in the app + keyboard lifecycle, so presumably, it's always been run before any downloads or queries are attempted.  It's thus _very_ unlikely that it hasn't been called before any downloads are attempted.

Ideally, we should see _something_ about why the registration failed:

https://github.com/keymanapp/keyman/blob/aaa0c18ab63dd303a94d2de22d7071a1d003450c/android/KMEA/app/src/main/java/com/keyman/engine/cloud/CloudDownloadMgr.java#L64

https://github.com/keymanapp/keyman/blob/aaa0c18ab63dd303a94d2de22d7071a1d003450c/android/KMEA/app/src/main/java/com/keyman/engine/cloud/CloudDownloadMgr.java#L79-L80

Sadly, there's nothing I can find within Sentry's Android reports that matches "initialize" or "initialize error".  Checking the [official documentation](https://developer.android.com/reference/android/content/Context#registerReceiver(android.content.BroadcastReceiver,%20android.content.IntentFilter)) doesn't really help either, as it makes no mention of any thrown errors.  (`IllegalStateException` is a subclass of `RuntimeException`, so it doesn't have to be explicitly declared.)

The lack of logged registration-time Sentry events has me wondering if there somehow _is_ some other angle that could be responsible for the issue, but this approach does seem to be the simplest and most straightforward.  I also feel that it's the least likely to introduce new issues on the `stable-17.0` branch.

----

> ## `registerReceiver()` and races
> 
> If, on the other hand, we want to retry calling `registerReceiver`

To me, this seems way riskier to do on `stable` for an early bug fix... and there's no guarantee that we'd succeed on the retry, so we'd still need a way to bypass things.

2024-05-28 05:40 UTC, jahorton commented
> Is it possible that `executeAsDownload()` is starting while we are still in `initialize()` on another thread and that's causing the crash?

Upon creation, singleton creation is synchronized, as is initialization.  While the _start_ of `executeAsDownload` isn't `synchronized`, in the worst-case, its internal `initialize` call is marked as `synchronized` and would prevent race conditions on the basis of initialization-state.  (`isInitialized` is only ever set to `true` within `initialize`.)

For what it's worth, if there were a race, this block _should_ create a Sentry breadcrumb:

https://github.com/keymanapp/keyman/blob/aaa0c18ab63dd303a94d2de22d7071a1d003450c/android/KMEA/app/src/main/java/com/keyman/engine/cloud/CloudDownloadMgr.java#L215-L216

But waaaaaait.  That's not `KMLog`, so it'd never forward to Sentry!  Guess that's another detail to add to the stack.  (The previously-noted "missing" message passes through a `KMLog.LogException` call.)

2024-05-28 07:37 UTC, mcdurdin commented
> To me, this seems way riskier to do on `stable` for an early bug fix... and there's no guarantee that we'd succeed on the retry, so we'd still need a way to bypass things.

What is the outcome if we don't have a working receiver? Seems like we are in a broken state anyway, so resolving the crash like this doesn't necessarily help make the program more useable.

2024-05-29 01:50 UTC, mcdurdin commented
> If on a keyboard download, I suppose it would fail to install?

Yeah so that's bad.

I've now looked into the history of the try/catch and I think @darcywong00 used the wrong exception in `shutdown()`. I think he probably meant to handle `IllegalArgumentException`: https://github.com/keymanapp/keyman/pull/2635#discussion_r379247749. But that is still just patching over the scenario where we are trying to unregister a non-registered receiver.

2024-05-30 06:12 UTC, jahorton commented
> But that is still just patching over the scenario where we are trying to unregister a non-registered receiver.

Assuming that a receiver can always be registered.  The fact is, we _have_ an error-handling setup when registering.  I assume that the try-catch is there for a reason.

_If_ the cause is that we simply aren't able to register it, what's left to do _but_ "patch over" the scenario?  Granted... yes, _if_.

2024-05-30 06:27 UTC, mcdurdin commented
> I assume that the try-catch is there for a reason.

But as you noted earlier, we have never received any error logs corresponding to registration. So what does that mean?

2024-05-31 06:02 UTC, jahorton commented
Closing in favor of #11626.

2024-05-31 06:02 UTC, closed without merging