fix(web): Don't crash if `text` is undefined
keymanapp/keyman pull request #11607
Opened 2024-05-29 17:26 UTC by ermshiperete

This can happen during startup if the keyboard stub isn't set yet. It's more a hack than a fix, but at least it prevents the crash.

@keymanapp-test-bot skip

2024-05-29 22:10 UTC, mcdurdin requested changes
First, is there an associated crash report or issue?

Sadly, this little tiny patch opens up a world of questions for me.

As you say, this seems like it is a bandaid on a symptom -- and probably will just result in either a crash or else faulty behaviour elsewhere. But without seeing call stacks I cannot comment further.

I see also that you haven't applied a corresponding patch to the associated function `withoutPrefix`, which would be sensible.

Also, the short name is just a pain when symbol searching. Let's try and cleanup this kind of aliasing and just use `toPrefixedKeyboardId` and `toUnprefixedKeyboardId` in all cases...

Personally, I think the existence of these two functions indicates an underlying pathology: functions should not be accepting, in their input parameters, keyboard IDs that are ambiguous (i.e. in this case, may or may not contain a `Keyboard_` prefix). The function should accept one or the other. If there is a published API where we have transgressed in this way, one pattern should be deprecated (probably the pattern _including_ a prefix), and then clearly mark that as such, and eliminate 'utility' functions like these.

2024-05-31 01:47 UTC, jahorton commented
> Personally, I think the existence of these two functions indicates an underlying pathology: functions should not be accepting, in their input parameters, keyboard IDs that are ambiguous (i.e. in this case, may or may not contain a `Keyboard_` prefix). The function should accept one or the other. If there is a published API where we have transgressed in this way, one pattern should be deprecated (probably the pattern _including_ a prefix), and then clearly mark that as such, and eliminate 'utility' functions like these.

Even if so, I think it's wise to have the function defined for cases that do intend to transform keyboard IDs from one type to the other.  Note that the mobile apps do add namespacing to keyboard IDs, which can require a bit of special handling...

https://github.com/keymanapp/keyman/blob/ac294154d12d1fd537514bf24edf0a0386a24fc9/web/src/app/webview/src/keymanEngine.ts#L23-L30

This detail is needed because the final form of the ID is referenced by keyboard custom CSS; we apply it as part of the keyboard's OSK `classList`.
  
Also, of course, having specific functions for the process makes them unit testable.  Yes, they're simple... but testability can be a good thing.

This is by no means an exhaustive list, but a few notes:
- KMW uses the longform ID for fully loaded keyboards and stubs, like within keyboard-processor & finalized `keyboardRequisitioner.cache` stubs
    - Keyman Engine for Android (and for iOS) also sets the `Keyboard_` prefix in place, rather than using public-style stubs.
    - Note that this means we _currently_ actually need that `toUnprefixedKeyboardId` use in the app/webview block shown above.
- KMW typically accepts short-form stubs in others (like site-developer provided stubs passed to `keyman.addKeyboards()`).
    - It also needs short-form IDs for creating keyboard queries against the cloud API.
    - It appears the keyboard-script's loading element ID also uses the short-form ID.

It does look like the process for internal handling could use some work - I see some unit tests that expect the short-form ID for loaded stubs.  Higher-level integration tests tend not to have this - it seems that the prefixing may be set in place outside of the `KeyboardCache` class.

2024-05-31 01:58 UTC, jahorton commented
> First, is there an associated crash report or issue?
> 
> As you say, this seems like it is a bandaid on a symptom -- and probably will just result in either a crash or else faulty behaviour elsewhere. But without seeing call stacks I cannot comment further.

I'm going to second this.  If we _are_ actually getting an undefined here, I'd love to see the call stack and tighten things up in that regard personally.

2024-05-31 02:12 UTC, mcdurdin commented
> Even if so, I think it's wise to have the function defined for cases that do intend to transform keyboard IDs from one type to the other.

I am good with having a utility function that adds `Keyboard_` and a corresponding function that removes `Keyboard_` prefix. In debug builds, these should assert if the prefix state is not as expected.

2024-06-06 08:57 UTC, ermshiperete commented
I don't have a call stack or issue. 

Closing this PR until we have more data and can get to the root of the problem.

2024-06-06 08:57 UTC, closed without merging