feat(linux): mcompile-linux rework  module deadkey 🐘
keymanapp/keyman pull request #11813
Opened 2024-06-18 07:41 UTC by SabineSIL

fixes parts of PR [#9384](https://github.com/keymanapp/keyman/pull/9384)

This PR addresses and bundles comments made on  [#9384](https://github.com/keymanapp/keyman/pull/9384) for the module deadkey.

https://github.com/keymanapp/keyman/pull/9384#discussion_r1611432668
https://github.com/keymanapp/keyman/pull/9384#discussion_r1611443034
https://github.com/keymanapp/keyman/pull/9384#discussion_r1611465003
https://github.com/keymanapp/keyman/pull/9384#discussion_r1611467489
https://github.com/keymanapp/keyman/pull/9384#discussion_r1611471293
https://github.com/keymanapp/keyman/pull/9384#discussion_r1613231108

@keymanapp-test-bot skip

2024-06-18 13:38 UTC, ermshiperete requested changes
I think I found a couple problems, but mostly just nit picks. Feel free to reply and ignore if you disagree with those.

2024-06-18 13:38 UTC, ermshiperete commented on linux/mcompile/keymap/deadkey.cpp
> +        return;
This could be simplified as:

```suggestion
        dkVec.push_back(r_All_Vec[j]);
      }
      return;
```

2024-06-18 13:38 UTC, ermshiperete commented on linux/mcompile/keymap/deadkey.cpp
> +    if (((p_dk_ComposeTable)[i][0] == dk) && (IsKeymanUsedChar((p_dk_ComposeTable)[i][1]))) {
we can save some parens here:

```suggestion
    if ((p_dk_ComposeTable[i][0] == dk) && IsKeymanUsedChar(p_dk_ComposeTable[i][1])) {
```
or even

```suggestion
    if (p_dk_ComposeTable[i][0] == dk && IsKeymanUsedChar(p_dk_ComposeTable[i][1])) {
```

2024-06-18 13:38 UTC, ermshiperete commented on linux/mcompile/keymap/deadkey.cpp
> +      line.push_back((p_dk_ComposeTable)[i][2]);
```suggestion
      line.push_back(p_dk_ComposeTable[i][0]);
      line.push_back(p_dk_ComposeTable[i][1]);
      line.push_back(p_dk_ComposeTable[i][2]);
```

2024-06-18 13:38 UTC, ermshiperete commented on linux/mcompile/keymap/deadkey.cpp
>    vec_dword_1D line;
`row` might be a better name for the variable since we push it to a table.

2024-06-18 13:38 UTC, ermshiperete commented on linux/mcompile/keymap/deadkey.cpp
> +void add_deadkey_combination(vec_dword_2D &dk_ComposeTable, std::string diacritic_name, std::string base_char, KMX_DWORD unicode_value) {
`add_deadkey_combination` is a much better name for the method now :+1:

2024-06-19 12:50 UTC, SabineSIL commented on linux/mcompile/keymap/deadkey.cpp
> +    for (int j = 0; j < (int)dk_ComposeTable.size(); j++) {
OK, changed it except for using (i) instead of (i+1). Otherwise it doesn´t add the first element

2024-06-19 13:40 UTC, SabineSIL commented
All those changes have been adressed 😃

2024-06-19 14:26 UTC, ermshiperete commented on linux/mcompile/keymap/deadkey.cpp
> +void refine_alDead(KMX_WCHAR dk, std::vector<DeadKey *> &dkVec, std::vector<DeadKey *> &r_All_Vec) {
This requires setting `DerivePointerAlignment: false` in `.clang-format`.

2024-06-19 14:32 UTC, ermshiperete approved these changes

2024-06-19 18:22 UTC, ermshiperete commented on linux/mcompile/keymap/deadkey.cpp
> +void refine_alDead(KMX_WCHAR dk, std::vector<DeadKey *> &dkVec, std::vector<DeadKey *> &r_All_Vec) {
I created https://github.com/keymanapp/keyman/pull/11836 to improve the formatting options.

2024-06-20 08:34 UTC, merged