feat(web): add unit testing for finalization of generated suggestions
keymanapp/keyman pull request #11946
Opened 2024-07-10 06:02 UTC by jahorton

@keymanapp-test-bot skip

2024-07-23 04:18 UTC, mcdurdin requested changes
This looks pretty good, but requesting a few tidy up changes for the tests

2024-07-23 04:18 UTC, mcdurdin commented on common/web/lm-worker/src/test/mocha/cases/suggestion-finalization.js
> +    it('with caret at end of current token and context', () => {
the phrase within `it()` should describe the expected outcome, and make sense if "it" is prepended, something like this:

```suggestion
    it('should provide appropriate suggestions with caret at end of current token and context', () => {
```

For this and all `it()` calls in this module.

2024-07-23 04:18 UTC, mcdurdin commented on common/web/lm-worker/src/test/mocha/cases/suggestion-finalization.js
> +      const analyzedSuggestions = [...Object.values(testSet).map((entry) => deepCopy(entry))];
This pattern + `expected` is repeated throughout. Can we refactor?

```suggestion
      const { analyzedSuggestions, testSet, expected } = build_its_is_set();
```

and in `build_its_is_set` return all of these? `expected` seems to be identical in 8 of 9 tests.

2024-07-25 04:37 UTC, rc-swag approved these changes
lgtm

2024-07-29 05:40 UTC, mcdurdin approved these changes

2024-07-29 08:02 UTC, merged

2024-07-29 18:02 UTC, keyman-server commented
Changes in this pull request will be available for download in [Keyman version 18.0.78-alpha](https://keyman.com/downloads/releases/alpha/18.0.78)