feat(linux): add function comments and remaining comments
keymanapp/keyman pull request #12065
Opened 2024-07-30 15:45 UTC by SabineSIL

fixes parts of PR https://github.com/keymanapp/keyman/pull/9384.

This is a PR for the remaining topics. Mostly formatting/editing things like 
- adding function comments
- format document

- replace codecvt
- set capslock =1
- replace Macro for calculating max
- prevent buffer overrun in u16tok 

- @keymanapp-test-bot skip

2024-07-31 13:01 UTC, ermshiperete commented on linux/mcompile/keymap/u16.h
> + * @return a std::string
```suggestion
 * @brief  Obtain a std::u16string from a std::string
 * @param  str the std::string to be converted
 * @return a std::u16string
```

2024-07-31 13:02 UTC, ermshiperete commented on linux/mcompile/keymap/u16.h
> + * @return a std::u16string
```suggestion
 * @param  str the std::u16string to be converted
 * @return a std::string
```

2024-07-31 13:04 UTC, ermshiperete commented on linux/mcompile/keymap/u16.h
> + * @return a std::string
```suggestion
 * @return a long
```

2024-07-31 13:05 UTC, ermshiperete commented on linux/mcompile/keymap/u16.h
> + * @return Pointer to the source with slash/backslash added
```suggestion
 * @brief  Find last '/' or '\\' in an array of char16_t
 * @param  Name Pointer to the source
 * @return Pointer to the last slash/backslash
```

2024-07-31 13:06 UTC, ermshiperete commented on linux/mcompile/keymap/u16.h
> + * @return Pointer to the source with slash/backslash added
```suggestion
 * @brief  Find last '/' or '\\' in an array of char
 * @param  Name Pointer to the source
 * @return Pointer to the the last slash/backslash
```

2024-07-31 13:08 UTC, ermshiperete commented on linux/mcompile/keymap/u16.h
> +const KMX_WCHAR* u16cpy(KMX_WCHAR* dst, const KMX_WCHAR* src);
```suggestion
const KMX_WCHAR* u16cpy(KMX_WCHAR* dst, const KMX_WCHAR* src);

```

2024-08-01 11:27 UTC, SabineSIL reviewed
Thanks for reviewing. Here are the requested changes:

About putting detailed comments into the cpp-files:  
I asked earlier and Marc proposed the other way. Since it`s a lot of work to change, I leave it as he proposed for now. 


Marc wrote on slack: [Jul 3rd at 11:53 PM](https://keymanapp.slack.com/archives/C871HJXT7/p1720043619997529?thread_ts=1720022370.338909&cid=C871HJXT7): `Function comment goes in the .h file, with a one liner duplicate of the function purpose in the .cpp -- I think.`

2024-08-01 11:27 UTC, SabineSIL commented on linux/mcompile/keymap/u16.cpp
> +/** @brief @brief Case sensitive comparison of two strings */
OK - done

2024-08-01 11:27 UTC, SabineSIL commented on linux/mcompile/keymap/keymap.h
left it as is...

2024-08-01 11:27 UTC, SabineSIL commented on linux/mcompile/keymap/mc_kmxfile.cpp
> +LPKMX_KEYBOARD KMX_FixupKeyboard(PKMX_BYTE bufp, PKMX_BYTE base, KMX_DWORD dwFileSize);
left it as is...

2024-08-02 08:08 UTC, ermshiperete commented
> About putting detailed comments into the cpp-files: I asked earlier and Marc proposed the other way. Since it`s a lot of work to change, I leave it as he proposed for now.

OK.

> Marc wrote on slack: [Jul 3rd at 11:53 PM](https://keymanapp.slack.com/archives/C871HJXT7/p1720043619997529?thread_ts=1720022370.338909&cid=C871HJXT7): `Function comment goes in the .h file, with a one liner duplicate of the function purpose in the .cpp -- I think.`

I don't fully agree. If it's for an API that is used externally then it makes sense to put the documentation in the .h file, because typically you have the binary library and the header file, so you look in the header file.

However, if it's only used internally, i.e. within the same project or repo, then I think you more often look at the definition in the .cpp file because not all functions have documentation comments and so then you're required to look at the definition to figure out the meaning of the parameters and what the function does. And if you use F12 in an IDE it'll take you to the definition if it's available. So IMO for internal functions it'd make more sense to have the full documentation in the .cpp file and the one-liner in the .h file.

2024-08-02 08:30 UTC, ermshiperete requested changes
Almost there

2024-08-02 08:30 UTC, ermshiperete commented on linux/mcompile/keymap/deadkey.h
> + * @param         r_dk_ComposeTable vector containing all possible deadkey combinations
```suggestion
 * @param         dk_ComposeTable   vector containing all possible deadkey combinations
```

2024-08-02 08:30 UTC, ermshiperete commented on linux/mcompile/keymap/keymap.h
> + *         if entry can be split
?

2024-08-02 08:30 UTC, ermshiperete commented on linux/mcompile/keymap/keymap.h
> + * @param  keymap pointer to pointer to currently used (underlying) keyborad layout
```suggestion
 * @param  keymap pointer to pointer to currently used (underlying) keyboard layout
```

2024-08-02 08:30 UTC, ermshiperete commented on linux/mcompile/keymap/keymap.h
> + *  return the keycode of the currently used (underlying) keyboard for a given virtual key of the US keyboard
That's missing the `@brief`

2024-08-02 08:30 UTC, ermshiperete commented on linux/mcompile/keymap/keymap.h
> + *  return a virtual key of the US keyboard for a given keycode of the currently used (underlying) keyboard
That's missing the `@brief`

2024-08-02 08:30 UTC, ermshiperete commented on linux/mcompile/keymap/u16.cpp
> +
```suggestion
```

2024-08-02 08:30 UTC, ermshiperete commented on linux/mcompile/keymap/u16.h
> + * @return PPointer to the first token in p
```suggestion
 * @return Pointer to the first token in p
```

2024-08-02 10:34 UTC, SabineSIL reviewed
done all changes except for position of documentation

2024-08-02 10:34 UTC, SabineSIL commented on linux/mcompile/keymap/deadkey.h
> + * @param         r_dk_ComposeTable vector containing all possible deadkey combinations
OK-done (changed to r_dk_ComposeTable)

2024-08-02 19:47 UTC, SabineSIL commented
> > About putting detailed comments into the cpp-files: I asked earlier and Marc proposed the other way. Since it`s a lot of work to change, I leave it as he proposed for now.
> 
> OK.
> 
> > Marc wrote on slack: [Jul 3rd at 11:53 PM](https://keymanapp.slack.com/archives/C871HJXT7/p1720043619997529?thread_ts=1720022370.338909&cid=C871HJXT7): `Function comment goes in the .h file, with a one liner duplicate of the function purpose in the .cpp -- I think.`
> 
> I don't fully agree. If it's for an API that is used externally then it makes sense to put the documentation in the .h file, because typically you have the binary library and the header file, so you look in the header file.
> 
> However, if it's only used internally, i.e. within the same project or repo, then I think you more often look at the definition in the .cpp file because not all functions have documentation comments and so then you're required to look at the definition to figure out the meaning of the parameters and what the function does. And if you use F12 in an IDE it'll take you to the definition if it's available. So IMO for internal functions it'd make more sense to have the full documentation in the .cpp file and the one-liner in the .h file.

@mcdurdin : What do you think? How do we want to do that?

2024-08-07 10:06 UTC, ermshiperete approved these changes
A few minor things left...

2024-08-07 10:06 UTC, ermshiperete commented on linux/mcompile/keymap/mcompile.cpp
> + * @param  argv_gdk pointer to (commandline arguments)
There's no `argv_gdk` parameter...

```suggestion
 * @param  argv     pointer to commandline arguments: executable, inputfile, outputfile
```

2024-08-08 06:40 UTC, SabineSIL commented
changed minor things

Comments:
- detailed comment in .cpp   -> before function definition
- one-liner comment  in .cpp -> before forward declaration
- one-liner comment  in .h     -> before declaration

2024-08-08 06:41 UTC, merged