fix(android): Allow external keyboard to work when OSK hidden
keymanapp/keyman pull request #12381
Opened 2024-09-10 06:06 UTC by darcywong00

Fixes #12366
Reverts part of #7612 which had changed where the Javascript handler gets attached

## User Testing
**Setup** - Install the PR build of Keyman for Android on a physical device. Also pair an external keyboard (USB/bluetooth) to the device

* **TEST_KEYBOARD** - Verifies external keyboard works when virtual keyboard hidden
1. Launch Keyman
2. From "Get Started", enable Keyman as the default system keyboard
3. Launch a separate app where you can type in (ideally a note taking app like Keep or OneNote as reported in the issue). If those aren't available, Chrome browser works
4. Select a text area with Keyman sil_euro_latin selected as the system keyboard
5. Verify the system keyboard types fine (longpresses, switching, keys, etc).
6. With the virtual keyboard displayed, type on the physical keyboard <kbd>`</kbd> <kbd>a</kbd>
7. Verify the text becomes `à`.
8. From the Android system preferences, select "Language and Keyboard" --> Physical keyboard --> Toggle "show on-screen keyboard" so that the OSK is hidden
9. Return to the note-taking / Chrome app and select a text field
10. Type on the physical keyboard <kbd>`</kbd> <kbd>a</kbd>
11. Verify the text becomes `à`

2024-09-10 06:37 UTC, mcdurdin reviewed
I am uncertain about the ramifications of this change. This means the `Runnable` runs on a new thread, not the UI thread, which seems to go against the discussion in the previously linked SO post. Can you elucidate?

2024-09-10 07:45 UTC, darcywong00 commented
> I am uncertain about the ramifications of this change. This means the `Runnable` runs on a new thread, not the UI thread, which seems to go against the discussion in the previously linked SO post. Can you elucidate?

I was just returning the call to how it had been for stable-15.0

https://github.com/keymanapp/keyman/blob/2dcc11448ee6e715fcfbbbaf6701a29f449e5817/android/KMEA/app/src/main/java/com/tavultesoft/kmea/KMKeyboard.java#L253-L272

2024-09-10 07:54 UTC, mcdurdin commented
> I was just returning the call to how it had been for stable-15.0

OK, so this was changed because of reported errors -- see https://github.com/keymanapp/keyman/pull/7612#discussion_r1024688563:

> True. Note that I placed it here because I saw a corresponding error occur once during development. Thought that was interesting, since "shouldn't the code be doing this already?"

I would like to understand _why_ this is causing the event handlers not to attach -- is it because there is no UI thread when the keyboard is hidden?

2024-09-10 10:15 UTC, dinakaranr commented
# Test Results
I tested this issue with the attached "Keyman 18.0.108-alpha-test-12381" build on the Android 14 mobile (physical device and keyboard connected with USB cable). I am sharing my observation.

**TEST_KEYBOARD (Passed):**
1. Installed the "Keyman-18.0.108.apk" file from the PR build. and gave all permissions to the application.
2. Checked the "Enable Keyman as system-wide keyboard" and set the keyboard as the default keyboard box on the settings page.
3. Open the Keyman app. Enable the "Predictions" to install the "Dictionary."
4. Launch the Google Keep application.
5. Create a new note. Keyman "sil_euro_latin" was selected as the system keyboard.
6. Typed some text using the "sil_euro_latin" keyboard.
7. Verified the system keyboard types fine when doing long presses, switching, keys, and pull-down. 
8. Type `a in the physical keyboard, and OSK appears at the same time. 
9. Verified the text appeared as à.
10. Disabled the OSK by selecting "Language and Keyboard" --> Physical keyboard --> Toggle "show the on-screen keyboard."
11. Again, launch the Google Keep application.
12. Create a new note.
13. Verified that the OSK does not appear in the Android mobile app.
14. Type `a in the physical keyboard.
15. Verified the text appeared as à.
It works well using the physical keyboard if OSK is enabled or disabled.
I tested this same scenario in the "https://editpad.org/" on the Chrome browser. It works great for me.

2024-09-12 08:45 UTC, darcywong00 commented
> is it because there is no UI thread when the keyboard is hidden?

That's what seems to be the behavior
![Screenshot from 2024-09-12 14-37-34](https://github.com/user-attachments/assets/dd780927-6efe-48d9-ac39-c3da176990c1)

When the OSK is hidden, executing hardware keystrokes never gets into this handler on the right. And I see the javascriptAfterLoad queue keeps accumulating the Javascript calls.

When the OSK is shown again, all the Javascript calls execute and the text updates.

2024-09-12 23:33 UTC, mcdurdin commented
This reversion may appear to work but it is not thread safe -- which is probably why it was changed in the first place. Calling [`this.postDelayed()`](https://developer.android.com/reference/android/view/View#postDelayed(java.lang.Runnable,%20long)) is scheduling it to run on the UI thread (per the documentation). But calling [`new Handler().postDelayed()`](https://developer.android.com/reference/android/os/Handler) schedules it to run on a new thread.

1. I guess this could cause the error `"All WebView methods must be called on the same thread."` ([per the Stack Overflow discussion](https://stackoverflow.com/a/22611010)). Because now we are calling WebView methods from the wrong thread, right? (We'll only see it happen if `javascriptAfterLoad.size() > 0`.
2. In the runner, we are referencing parent object member variables that could be being modified by another thread, e.g. `javascriptAfterLoad`, `keyboardSet`. This will likely lead to thread races -- access to these members needs to be sychronized.
3. Also all calls to member functions are on the wrong thread, as they expect to be called on the UI thread, e.g. `loadUrl`, `callJavascriptAfterLoad`.
4. It is possible, albeit probably unlikely, that the runner could execute after the parent object is destroyed, resulting in a crash.

So we need to find a better way to solve this.

2024-09-12 23:33 UTC, mcdurdin requested changes
See discussion

2025-01-10 07:04 UTC, jahorton commented on android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java
> +      Handler handler = new Handler();
![On this constructor's deprecation(https://github.com/user-attachments/assets/ecd9e63a-7987-4c96-a9b0-d0097e2ac598)

(from https://developer.android.com/reference/android/os/Handler)

The docs strongly suggest making this, at least, `new Handler(Looper.getMainLooper())`.

2025-01-10 07:48 UTC, jahorton commented on android/KMEA/app/src/main/java/com/keyman/engine/KMKeyboard.java
> +      Handler handler = new Handler();
After a bit more searching, I found this:  https://stackoverflow.com/questions/13974661/runonuithread-vs-looper-getmainlooper-post-in-android

The big takeaway from that link:  `Looper.getMainLooper()` will return the Looper instance associated with the primary UI thread, which is what we want.

2025-01-12 00:10 UTC, closed without merging

2025-01-12 00:10 UTC, darcywong00 commented
Replaced by #12871