feat(developer): kmc-convert:  new conversion .keylayout->kmn
keymanapp/keyman pull request #12564
Opened 2024-10-21 03:32 UTC by SabineSIL

kmc-convert provides tooling to convert between various common keyboard description file formats. Each conversion will be implemented in its single, separate module (and each module will done in its own PR)

This PR will address the conversion **keylayout → kmn**

- keylayout → kmn
- xkb→ kmn
- keylayout → ldml
- xkb→ ldml
- kmn→ ldml
- msklc→ kmn
- msklc→ ldml
- ldml→ kmn
- (inkey→ kmn)
- (inkey→ ldml)

@keymanapp-test-bot skip
see PR #12191

2025-03-28 16:40 UTC, ermshiperete requested changes, later dismissed
You should rename the test files according to the standard we agreed on in Chiang Mai. Also `test-converter-messages.ts` → `converter-messages.tests.ts`. 

You'll also have to change `test/tsconfig.json`:
```
-      "**/test-*.ts",
+      "**/*.tests.ts",
```

2025-03-28 16:40 UTC, ermshiperete commented on developer/src/kmc-convert/test/test-converter.ts
The filename should be `converter.tests.ts` according to the standard we agreed on in Chiang Mai.

2025-03-28 16:40 UTC, ermshiperete commented on developer/src/kmc-convert/test/test-keylayout-to-kmn-converter.ts
The filename should be `keylayout-to-kmn-converter.tests.ts` according to the standard we agreed on in Chiang Mai.

2025-04-01 15:23 UTC, srl295 reviewed
looking good, some comments though!

2025-04-02 00:30 UTC, mcdurdin reviewed
Unforunately, I am not going to get capacity to look at this in detail until after my break. I think we'll still need to do some work on the structure of the PR -- I am seeing some immediate things like:

* use of node modules such as path and fs (we don't use them directly in kmc modules, instead we use callbacks.fs and callbacks.path)
* inclusion of data files in the PR (these will be copyright Apple I expect)
* breaking out file parsing/writing from the conversion, into separate files (e.g. KeylayoutFileReader should be a separate module just like KvkFileReader, for example).
* hardcoded paths e.g. '/data/...'

2025-04-02 11:22 UTC, SabineSIL commented on developer/src/kmc-convert/test/test-keylayout-to-kmn-converter.ts
all done

2025-04-02 14:06 UTC, srl295 commented on developer/src/kmc-convert/data/French.keylayout
could we author a new file for testing purposes (ukulele or something) and put that in?

2025-04-02 14:15 UTC, ermshiperete commented on developer/src/kmc-convert/data/French.keylayout
If we include any such files they should go in `test/data`.

2025-04-03 15:50 UTC, SabineSIL reviewed
some comments/questions on yourreviews

2025-04-03 15:50 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +import { XMLParser } from 'fast-xml-parser';  // for reading an xml file
see new issue #13662

2025-04-03 15:50 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +      console.log("RUN kmc convert - input file: ", (process.cwd() + "\\data\\" + data_object.keylayout_filename), " -->  output file: ", data_object.kmn_filename);
I don`t understand what you mean, are you talking about the console.log statement?

2025-04-03 15:50 UTC, SabineSIL commented on developer/src/kmc-convert/data/French.keylayout
@mcdurdin : 
**- use of node modules**: done
**- breaking out file parsing/writing**: done
**- /data/..:**  where do we want to store the input/output files ?
**- inclusion of data files:**  I need at least one .keylayout file for the tests. Can I alter some content in one of these .keylayout files ( e.g. Italian.keylayout) to be fine with the copyright?

2025-04-04 16:37 UTC, srl295 commented on developer/src/kmc-convert/test/keylayout-to-kmn-converter.tests.ts
> +        await doesNotReject(async () => JSON.stringify(result) === JSON.stringify(values[1]));
I would expect this would still have asserts - you can do `import * as assert from 'node:assert'` and then this line wouldn't need to change

2025-04-08 19:15 UTC, srl295 commented
@SabineSIL tests look good!

I think the rule class issue could be addressed in the future also.

2025-04-22 06:54 UTC, mcdurdin commented on developer/src/kmc-convert/data/French.keylayout
> **- /data/..:** where do we want to store the input/output files ?

This module is not responsible for storing input/output files. They are passed in by kmc itself.

> **- inclusion of data files:** I need at least one .keylayout file for the tests. Can I alter some content in one of these .keylayout files ( e.g. Italian.keylayout) to be fine with the copyright?

No, we need to make our own .keylayout file for the test, using Ukelele, to avoid any copyright issues.

2025-04-25 07:20 UTC, SabineSIL reviewed
worked on comments

2025-05-12 15:34 UTC, mcdurdin reviewed
Not reviewing the tests at this point; once the other modules are ready, will re-review the tests as well.

2025-05-12 15:34 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +  static readonly USED_KEYS_COUNT = 51;               // we use key Nr 0 (A) -> key Nr 49 (Space)
Question why 0-49 in the comment (50 keys) but the constant is 51?

2025-05-12 15:34 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +  static readonly KMC_CONVERT_VERSION = "0.1";
Don't use a private version number; instead use `KEYMAN_VERSION` from `@keymanapp/keyman-version`

2025-05-12 15:34 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +  constructor(private callbacks: CompilerCallbacks, options: CompilerOptions) { };
Shouldn't need a constructor :grin: - per the `KeymanCompiler` interface. 

```suggestion
```

2025-05-12 15:34 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
>  export class KeylayoutToKmnConverter {
```suggestion
export class KeylayoutToKmnConverter implements KeymanCompiler {
```

2025-05-12 15:34 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +  async run(inputFilename: string, outputFilename: string = ""): Promise<ConverterToKmnArtifacts> {
```suggestion
  async run(inputFilename: string, outputFilename?: string): Promise<KmcConverterKmnResult> {
```

To match the interface spec, we need a wrapper 'KeymanCompilerResult' class, e.g. `KmcConverterKmnResult`, which should have an `artifacts: KmcConverterKmnArtifacts` member.

2025-05-12 15:34 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +      throw new Error('Error while processing read()');
This needs to use `this.callbacks.reportMessage()`

2025-05-12 15:34 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +      throw new Error('Error while processing convert()');
This needs to use `this.callbacks.reportMessage()`

2025-05-12 15:34 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +    const out_text_ok: boolean = kmnFileWriter.write(outArray);
The output needs to be written to an in-memory artifact here, and returned in the result, e.g.

```
const result: KmcConverterKmnResult = { kmn: ...., kvks: .... }
```

2025-05-12 15:34 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +      const filePath = this.callbacks.path.join(process.cwd(), KeylayoutToKmnConverter.TEST_SUBFOLDER, KeylayoutToKmnConverter.DATA_SUBFOLDER);
We can't call `process.cwd()` here -- do we really need the input filename in this part of the process? We have the input filename already passed into the `run()` function, so if we need it, we should pass it in.

2025-05-12 15:34 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +      console.log("RUN kmc convert - input file: ", data_object.keylayout_filename, " -->  output file: ", data_object.kmn_filename);
We need to eliminate console.log messages before merge

2025-05-12 15:34 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +  public convert(jsonObj: any, outputfilename: string = ""): convert_object {
should be private; if you need access for tests, see the pattern at https://github.com/keymanapp/keyman/blob/9c1c41745704d55f1bcc67685261d2ca3f61504e/developer/src/kmc-keyboard-info/src/keyboard-info-compiler.ts#L672-L675

2025-05-12 15:34 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +          console.log("ERROR : some output characters can not be used in Keyman \"",
This needs to use `callbacks.reportMessage`

2025-05-12 15:34 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +    if (pos === 0x0A) return "K_BKQUOTE";         /* ^ */
This long ladder of if/else could be an array -- first check bounds of pos:

```
  if(typeof pos == 'number' && pos >= 0 && pos <= 0x##) { 
    return UkeleleKC_to_VK[pos];
  }
  return "";
```

Then define Ukelele_to_VK as an array of strings:

```
const Ukelele_to_VK = [
  'K_A',
  'K_S',
...
];
```

2025-05-12 15:34 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +            }
```suggestion
            returnarray2D.push(returnarray);
```

Or ...

```suggestion
            if (returnarray.length > 0) {
              returnarray2D.push([search, outchar, data...., behaviour, keyName, modifierkmn]);
            }
```

2025-05-12 15:34 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +            returnarray.push(modifierkmn);
This is an object masquerading as an array. Each element in the array has a specific meaning. It would be better to use a class or interface, e.g. 

```
  interface KeyElement {
    search: string;
    outchar: string;
    action: string;
    behaviour: string;
    keyName: string;
    modifierkmn: string;
  };
```

And then `returnarray2D` becomes a 1-dimensional array containing each of these objects.

2025-05-14 09:04 UTC, SabineSIL reviewed
first comments edited

2025-06-27 08:37 UTC, SabineSIL reviewed
worked on all comments

2025-06-27 08:37 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +  async run(inputFilename: string, outputFilename: string = ""): Promise<ConverterToKmnArtifacts> {
done

2025-06-27 08:37 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +      throw new Error('Error while processing read()');
done

2025-06-27 08:37 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +      throw new Error('Error while processing convert()');
done

2025-06-27 08:37 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +            }
done

2025-06-27 08:37 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +          mapIndexArray_2D.push(mapIndexArrayperKey);
done

2025-06-27 08:37 UTC, SabineSIL commented on common/web/types/src/util/util.ts
> +    return instr;
done

2025-06-27 08:37 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +  public convert(jsonObj: any, outputfilename: string = ""): convert_object {
done

2025-06-27 08:37 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +        uniq.push(curr);
Using objects here is a clever idea. 
However I am hesitant to convert arrays to objects because I use arrays frequently and the entire process of jumping back and forth through the input file data depends on these arrays. Replacing them with objects would be a lot of work.

2025-06-27 08:37 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +    if (pos === 0x0A) return "K_BKQUOTE";         /* ^ */
done

2025-06-27 08:37 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +    const out_text_ok: boolean = kmnFileWriter.write(outArray);
created new draft PR 
*  #14233

2025-06-30 22:49 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +        uniq.push(curr);
Looking at future maintainability, I think objects with named members is going to be a lot easier to manage than arrays where small changes could cause a cascade of array index mismatches. We have had a similar issue in the Keyman for iOS code and I do think it would be better to refactor now than to have to address it in the future.

2025-07-08 14:40 UTC, ermshiperete commented on developer/src/kmc-convert/test/kmn-file-reader.tests.ts
> +      const inputFilename = makePathToFixture('../' + 'data' + '/Test.keylayout');
There's not benefit in splitting the string since the three parts will be concatenated right away by the runtime, so I'd suggest to pass a single string instead:

```suggestion
      const inputFilename = makePathToFixture('../data/Test.keylayout');
```

2025-07-09 13:22 UTC, SabineSIL commented on developer/src/kmc-convert/test/kmn-file-reader.tests.ts
> +      const inputFilename = makePathToFixture('../' + 'data' + '/Test.keylayout');
...done

2025-07-16 13:26 UTC, jahorton reviewed
Started a review here.  Haven't looked at these yet:
- developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
- developer/src/kmc-convert/src/keylayout-to-kmn/kmn-file-writer.ts
- any unit testing files

(I started from the top and stopped at the near-1000 line file.)

What I've seen so far seems good, so far as I can tell.  I'm not so familiar with the `boxArray` bit, but I think I get the idea, especially after seeing the related comment in developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-file-reader.ts.

2025-07-16 13:26 UTC, jahorton commented on common/web/types/src/util/util.ts
> +export function convertToUnicodeCodePoint(instr: string): string {
It appears that this function returns the `U+____` form of the character, while `convertToUnicodeCharacter` returns the actual character?  Might be nice to have a doc-comment on the method to make things clear.

2025-07-18 13:03 UTC, jahorton reviewed
Had these comments ready a few days ago; just realized it never actually got submitted.

Nice to see that some cleanup happened since I originally wrote them; I was able to drop a couple of comments.

2025-07-18 13:03 UTC, jahorton commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
>  export class KeylayoutToKmnConverter {
+1 (for visibility, since [the original](https://github.com/keymanapp/keyman/pull/12564/files#r2084889628) is hidden by default)

2025-07-18 13:03 UTC, jahorton commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +  constructor(private callbacks: CompilerCallbacks, options: CompilerOptions) { };
+1 (for visibility, since [the original](https://github.com/keymanapp/keyman/pull/12564/files#r2084888814) is hidden by default)

2025-07-18 13:03 UTC, jahorton commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +    // ToDo in a new PR: check tags  ( issue # 13599)
I see that #13599 is marked as "in code review" now, likely coinciding with this PR moving from "draft" to "review" - is this comment still valid?

2025-07-18 13:03 UTC, jahorton commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +export interface convert_object {
Could probably use some mild documentation on this object.  Looks like it serves as an intermediate processing stage specific to .keylayout => .kmn?

2025-07-18 13:03 UTC, jahorton commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +  public createRuleData(data_ukelele: convert_object, jsonObj: any): convert_object {
I'll pause my review here for now.

2025-07-18 13:03 UTC, jahorton commented on developer/src/kmc-convert/src/converter-messages.ts
> +    this.ERROR_OutputFilenameIsRequired, `An output filename is required for keyboard conversion.`);
Mild code formatting nit: since the opening parenthesis (for the m() function) is at the end of a previous line, should we put the closing parenthesis on its on line, like we would for a if-else brace?

```suggestion
  static Error_OutputFilenameIsRequired = () => m(
    this.ERROR_OutputFilenameIsRequired, `An output filename is required for keyboard conversion.`
  );
```

Similar edits would apply to much of the following code in this file.

To the team: This is something I've been doing in Web / pred-text worker code already, so if the way it is is "correct", then I've got some code reformatting to do eventually elsewhere for consistency's sake.

2025-07-18 20:46 UTC, jahorton reviewed
I might need another pass on a few areas, but this review covers the rest of developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts except where stated otherwise.

2025-07-18 20:46 UTC, jahorton commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +                      for (let n4 = 0; n4 < b1_modifierKey_arr.length; n4++) {
Whoa, we've got some pretty deep loop nesting here.  Normally, that's not a good sign, but I'm guessing it's necessary due to the format.

2025-07-18 20:46 UTC, jahorton commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +            // https://docs.google.com/document/d/12J3NGO6RxIthCpZDTR8FYSRjiMgXJDLwPY2z9xqKzJ0/edit?tab=t.0#heading=h.g7jwx3lx0ydd   .........
👍

2025-07-18 20:46 UTC, jahorton commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +                            for (let n7 = 0; n7 < b1_modifierKey_arr.length; n7++) {
😨 

I imagine the human-written KMN equivalent would use stores here?  The smell I'm picking up is that the .keylayout's definitions correspond to something that corresponds to the role of KMN keyboard stores.  (Granted, stores don't handle modifier sets on input keys, so some loops would still be necessary for that aspect.)

It looks as if these loops are explicitly writing out rules for a full set of permutations across multiple stores - multiple sets of values that can vary completely independently from each other.

It'd be nice to actually _convert_ the pattern to stores if possible.  That would certainly yield a more human-readable result.  That said, I'm not the expert in .keylayout here, and it's a "would be nice", not a necessity for our initial implementation.

2025-07-18 20:46 UTC, jahorton commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +    * @brief  member function to review data in array of Rules[] of data_ukelele: remove duplicate rules and mark first occurance of a rule in object_array
I suppose this is a decent reason to not convert on the store level - if there's a legitimate concern for duplicate rules, which could happen if one is store-based and another is defined using only specific values.

... gonna gloss over this method for now, as it seems to require significant .keylayout knowledge, and the examples from the doc referenced earlier aren't explaining enough for me to follow this.

2025-07-18 20:46 UTC, jahorton commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +  public get_KeyActionOutput_array__From__ActionStateOutput_array(data: any, search: string[][]): string[][] {
Some of these are a bit opaque for me to follow, at least on an initial pass.

2025-07-18 20:46 UTC, jahorton commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +        uniq.push(curr);
> Looking at future maintainability, I think objects with named members is going to be a lot easier to manage than arrays where small changes could cause a cascade of array index mismatches.

I was thinking this idea in a previous review phase, but didn't want to impose.  When there's a very high argument count, it's rough remembering what each parameter is - objects with named members make that much clearer.

One of the things I like about iOS development and Swift is the named arguments feature, for this very sort of reason.

2025-07-21 14:38 UTC, SabineSIL commented on common/web/types/src/util/util.ts
> +export function convertToUnicodeCodePoint(instr: string): string {
done

2025-07-21 14:38 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +    // ToDo in a new PR: check tags  ( issue # 13599)
removed

2025-07-21 14:38 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +export interface convert_object {
done

2025-07-21 14:38 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +                      for (let n4 = 0; n4 < b1_modifierKey_arr.length; n4++) {
yeah, jumping back and forth though the keylayout file

2025-07-21 14:38 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +    * @brief  member function to review data in array of Rules[] of data_ukelele: remove duplicate rules and mark first occurance of a rule in object_array
A 'modi/key combination > dk(X)' might occur in several combined rules ( e.g. 
`+ [NCAPS SHIFT RALT K_1]  >  dk(X)`      ` dk(X) + [NCAPS K_SPACE]  >  '´' `  as well as in 
`+ [NCAPS SHIFT RALT K_1]  >  dk(X)`       `dk(X) + [CAPS K_Q]  >  'Á'`

They might also occur in C2 rules (series of 2 modi/key combinations) or C3 rules (series of 3 modi/key combinations)

`+ [NCAPS SHIFT RALT K_1]  >  dk(X)`        `dk(X) + [CAPS K_Q]  >  'Á' `  **(C2 rule)**
`+ [NCAPS SHIFT RALT K_1]  >  dk(X)`      `dk(X)  + [K_BKQUOTE]  >  dk(Y)`        `dk(Y) + [CAPS K_Q]  >  'Q'`   **(C3 rule)**



Since Keyman does not allow duplicate rules,
- we need to split the first first modi/key combination off from the C2 or C3 combination and thus build a unique set of '`modi/key combination >  dk(...)`' 
- We also need to make sure the first `'modi/key combination >  dk(...)`' in a **C2** rule and the same first '`modi/key combination >  dk(...)`' in a **C3** rule get an identical identifier and thus don`t occur several times in a kmn file.

2025-07-21 14:38 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +  public get_KeyActionOutput_array__From__ActionStateOutput_array(data: any, search: string[][]): string[][] {
... that's the jumping back and forth though a keylayout-file

2025-07-21 14:38 UTC, SabineSIL commented on developer/src/kmc-convert/src/converter-messages.ts
> +    this.ERROR_OutputFilenameIsRequired, `An output filename is required for keyboard conversion.`);
done

2025-07-21 14:38 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +        uniq.push(curr);
new issue #14378 or PR [#14406](https://github.com/keymanapp/keyman/pull/14406)

2025-07-21 17:32 UTC, jahorton reviewed
Here's my first-pass attempt to review developer/src/kmc-convert/src/keylayout-to-kmn/kmn-file-writer.ts.  It's quite possible I'm missing the mark on what's actually going on, but as even that might be valuable code review info, I'm passing it along.

That said, if I'm particularly off-base and this makes a lot more sense to someone else, that might be fine?  That said, I can say that it'd certainly take me a _while_ to come up to speed on the main two files if I were tasked with maintaining this feature.

----

Between this file and the previous file... it seems like there's a _lot_ of specialized knowledge around each of the C0, C1, C2, and C3 classes of "rules" in a .keylayout.  Coming from a new, fresh perspective... without loss of generalization, the organization of code here doesn't keep C0-specific (and C1-C3) stuff encapsulated, where all the C0 is grouped together in a manner that clarifies the nature of C0 stuff.

To be clear, I've referenced [a related document](https://docs.google.com/document/d/12J3NGO6RxIthCpZDTR8FYSRjiMgXJDLwPY2z9xqKzJ0/edit?tab=t.0#heading=h.g7jwx3lx0ydd) to try gaining a better understanding to make this review, especially in relation to C0-C3 rules - the document has some notable related images.  I at least get more than _nothing_ out of the document, but it's not nearly enough to sufficiently clarify things for me.  What are the three parts of a C3 rule?  Like, I see the three column, three row table... but I don't know what that's trying to say or explain.  I don't get why it makes sense to _say_ three parts for a C3 rule, nor do I get how they're functionally related to each other - each part looks like its own separate Keyman rule.  And under "5 different cases", I feel like I get C0 and C1, but I can't trace the actual relationships among the parts for C2 or C3.

Of particular note for me is that there appear to be multiple (at least three) separate locations, all seeking to detect duplicate cases, with some of those also seeking to detect ambiguous cases as well.  It's not clear why duplicate checking needs to be so fragmented across the .keylayout code.

I do recognize that there are _some_ interactions across the classes to prevent duplicate / ambiguous rules - there's clearly some C2 vs C3 stuff, and I doubt that was the only case.  These cross-class interactions would likely make a clear encapsulation of each rule class a little harder.  That said, noting how extensive some of the methods are, and in a manner that requires enumerating separate blocks for each rule class... I can't help but think that the main functions would be clearer if C0 - C3 had some good encapsulated design.

Alternatively, simply splitting up those behemoth methods into multiple smaller-scale functions targeted at specific cases, with corresponding documentation, might help.

2025-07-21 17:32 UTC, jahorton commented on developer/src/kmc-convert/src/keylayout-to-kmn/kmn-file-writer.ts
> +  public writeData_Stores(data_ukelele: convert_object): string {
I see there's no real conversion to Keyman language stores here, despite the name.  This seems to be acting more like a file header.  Is the plan to analyze rules to determine stores at some point?

Past that... maybe set a Keyman-language target version store or similar super-common system stores here?

2025-07-21 17:32 UTC, jahorton commented on developer/src/kmc-convert/src/keylayout-to-kmn/kmn-file-writer.ts
> +    const unique_data_Rules: Rule[] = data_ukelele.arrayOf_Rules.filter((curr) => {
I believe the implication is that any duplicate rule is essentially erased and will be filtered by this statement?

... though, C2 / C3 duplicate cases are handled elsewhere by `reviewRuleInputData`?

---

Either way, even if my crude inference is wrong... it's notable that this method - `writeData_Rules` - is rather long and massive.  Looks like it spans lines 110 to 393?  There appear to be a number of distinct sections in there, from the looks of things, but all expanded within the one method.

2025-07-21 17:32 UTC, jahorton commented on developer/src/kmc-convert/src/keylayout-to-kmn/kmn-file-writer.ts
> +        && new TextDecoder().decode(curr.output) !== new TextDecoder().decode(rule[index].output)
Had to pull out the code editor here; the only difference between this and the following block is lines 478 / 491, with `amb_1_1`'s version possessing a `!==` while `dup_1_1`'s version possesses a `===`.  With the comparison targeting the string-rendered form of the rule, no less.

So, even _more_ duplicate-rule prevention?  Regarding ambiguous rules, I suppose that's in case the .keylayout has two almost-identical rules but with different outputs but the same inputs?

Also, I _assume_ that for both, the purpose behind the `idx < index` component is to ensure we only scan for duplicates / near duplicates in a forward-facing order to prevent triggering twice for the same set.  (i.e., if rule A is before rule B, rule A's check finds B, but B's doesn't find A because B's index is later.)  Is this read of the condition component correct?

2025-07-21 17:51 UTC, jahorton commented
Also, skimming through the test data and definitions, it looks like all of the "unit" tests are what I'd consider to be integration-test level.  I'm not seeing any small-scale tests focused on conversion of single rules, or comparison of two intermediately-processed rules for ambiguity or duplication detection.  

It might help to structure things in order to permit such lower-level tests - to ensure the basics (or at least, specific cases for the basics) are working correctly, in a white-box testing style.

2025-08-16 11:40 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +          console.log("ERROR : some output characters can not be used in Keyman \"",
done

2025-08-16 11:40 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +        uniq.push(curr);
done

2025-08-16 11:40 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/kmn-file-writer.ts
> +  public writeData_Stores(data_ukelele: convert_object): string {
it should only write the header part containing details about stores
=> function name changed to write_KmnFileHeader()

2025-08-16 11:40 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-file-reader.ts
> +      xmlFile = this.callbacks.fs.readFileSync(this.callbacks.path.join(process.cwd(), KeylayoutToKmnConverter.TEST_SUBFOLDER, KeylayoutToKmnConverter.DATA_SUBFOLDER, this.callbacks.path.basename(inp
done

2025-08-16 11:40 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +  static readonly TEST_SUBFOLDER = 'test';
done

2025-08-16 11:40 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +    const out_text_ok: boolean = kmnFileWriter.write(outArray);
done

2025-08-16 11:40 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +      console.log("RUN kmc convert - input file: ", data_object.keylayout_filename, " -->  output file: ", data_object.kmn_filename);
done

2025-08-16 11:43 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/kmn-file-writer.ts
> +        && new TextDecoder().decode(curr.output) !== new TextDecoder().decode(rule[index].output)
.. I updated the documentation hoping C2, C3 rules will be explained more clearly

2025-08-16 11:45 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +    * @brief  member function to review data in array of Rules[] of data_ukelele: remove duplicate rules and mark first occurance of a rule in object_array
... see updated doc...

2025-08-16 11:52 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/kmn-file-writer.ts
> +    const unique_data_Rules: Rule[] = data_ukelele.arrayOf_Rules.filter((curr) => {
added comment: 

  ```
    // filter array of all rules and remove duplicates
    // during the process of creating Rule[], duplicate rules might occur 
    // (e.g. when in a keylayout file the same modifiers occur in several behaviors thus producing the same rules). 
    // This is to filter out those duplicate Rule objects
```

2025-08-19 07:21 UTC, mcdurdin commented on common/web/types/src/util/util.ts
> +export function decodeHexEntity(hex_Entity: string) {
```suggestion
export function decodeHexEntity(hexEntity: string) {
```

We don't generally use underscores in JavaScript identifiers, except sometimes at the start to indicate a private scope

2025-08-19 07:28 UTC, mcdurdin requested changes
I'd like to revisit these functions please -- code going into utils.ts needs to be seriously robust and well tested. We need unit tests for each of these functions too.

Note: at this point I have only reviewed the common/web code

2025-08-19 07:28 UTC, mcdurdin commented on common/web/types/src/util/util.ts
> +    return undefined;
This should really be a precondition, before the const line above it. But it would maybe be better to rewrite both lines using a regex which both validates the format and pulls the hex digits out:

hexEntity
```suggestion
  const match = /^&#x([0-9a-f]{2,6});$/i.match(hexEntity);
  if(!match) {
    return undefined;
  }
  const hex = match[1];
```

2025-08-19 07:28 UTC, mcdurdin commented on common/web/types/src/util/util.ts
> +  const dec = dec_Entity.replace('&#', '').replace(';', '');
Should be similar to decodeHexEntity example above

2025-08-19 07:28 UTC, mcdurdin commented on common/web/types/src/util/util.ts
> +  const hexval = Uni_Val.replace('U+', '0x');
Again, similar to decodeHexEntity

2025-08-19 07:28 UTC, mcdurdin commented on common/web/types/src/util/util.ts
> +  else if (in_str.substring(0, 3) === "&#x") {
```suggestion
  else if (in_str.startsWith("&#x")) {
```

2025-08-19 07:28 UTC, mcdurdin commented on common/web/types/src/util/util.ts
> +  else if ([...new Intl.Segmenter().segment(in_str)].length <= 1) {
What are you trying to do here?

Note that this will not work to get a Unicode Scalar Value because that would have length 1 or 2.

2025-08-19 07:28 UTC, mcdurdin commented on common/web/types/src/util/util.ts
> +    const num_str = instr.substring(instr.indexOf("x") + 1, instr.length - 1);
Here, we already know that instr.indexOf("x") == 2, so we can simplify:


```suggestion
    const num_length = instr.length - 3;
    const num_str = instr.substring(3, instr.length - 1);
```

But this function seems to overlap with decodeHexEntity?

2025-08-20 09:14 UTC, SabineSIL reviewed
created a new PR  #14569

2025-08-20 09:14 UTC, SabineSIL commented on common/web/types/src/util/util.ts
> +export function decodeHexEntity(hex_Entity: string) {
see new PR #14569

2025-08-20 09:14 UTC, SabineSIL commented on common/web/types/src/util/util.ts
> +    return undefined;
see new PR #14569

2025-08-20 09:14 UTC, SabineSIL commented on common/web/types/src/util/util.ts
> +  const dec = dec_Entity.replace('&#', '').replace(';', '');
see new PR #14569

2025-08-20 09:14 UTC, SabineSIL commented on common/web/types/src/util/util.ts
> +  const hexval = Uni_Val.replace('U+', '0x');
see new PR #14569

2025-08-20 09:14 UTC, SabineSIL commented on common/web/types/src/util/util.ts
> +  else if (in_str.substring(0, 3) === "&#x") {
see new PR #14569

2025-08-20 09:14 UTC, SabineSIL commented on common/web/types/src/util/util.ts
> +  else if ([...new Intl.Segmenter().segment(in_str)].length <= 1) {
see new PR #14569

2025-08-20 09:14 UTC, SabineSIL commented on common/web/types/src/util/util.ts
> +    const num_str = instr.substring(instr.indexOf("x") + 1, instr.length - 1);
see new PR #14569

2025-08-29 08:14 UTC, SabineSIL commented on common/web/types/src/util/util.ts
> +export function decodeHexEntity(hex_Entity: string) {
done in [14569](https://github.com/keymanapp/keyman/pull/14569) (removed function)

2025-08-29 08:14 UTC, SabineSIL commented on common/web/types/src/util/util.ts
> +    return undefined;
done in [14569](https://github.com/keymanapp/keyman/pull/14569)

2025-08-29 08:14 UTC, SabineSIL commented on common/web/types/src/util/util.ts
> +  const dec = dec_Entity.replace('&#', '').replace(';', '');
done in [14569](https://github.com/keymanapp/keyman/pull/14569) (removed function)

2025-08-29 08:14 UTC, SabineSIL commented on common/web/types/src/util/util.ts
> +  const hexval = Uni_Val.replace('U+', '0x');
done in [14569](https://github.com/keymanapp/keyman/pull/14569) (removed function)

2025-08-29 08:14 UTC, SabineSIL commented on common/web/types/src/util/util.ts
> +  else if (in_str.substring(0, 3) === "&#x") {
done in [14569](https://github.com/keymanapp/keyman/pull/14569) (changed function)

2025-08-29 08:14 UTC, SabineSIL commented on common/web/types/src/util/util.ts
> +  else if ([...new Intl.Segmenter().segment(in_str)].length <= 1) {
// 'A'  or  "B" have length=1 and segment-length=1 and will be used. 
  // "ẘ"  or  "😎" have length=2 but segment-length=1 and will be used. 
  // "ab" has length=2 and segment-length=2 and will not be used.

2025-08-29 08:14 UTC, SabineSIL commented on common/web/types/src/util/util.ts
> +    const num_str = instr.substring(instr.indexOf("x") + 1, instr.length - 1);
done in [14569](https://github.com/keymanapp/keyman/pull/14569)

2025-08-29 09:43 UTC, mcdurdin commented on common/web/types/src/util/util.ts
> +  else if ([...new Intl.Segmenter().segment(in_str)].length <= 1) {
Here's the issue, Intl.Segmenter does not return number of Unicode codepoints. It returns the number of abstract characters. For example, given the emoji 👨‍👩‍👧‍👦, which has the following codepoints: `[👨 U+1F468 (MAN), U+200D (ZWJ), 👩 U+1F469 (WOMAN), U+200D (ZWJ), 👦 U+1F466 (BOY), U+200D (ZWJ), 👦 U+1F466 (BOY)]`, we see three different outputs:

```
> [...new Intl.Segmenter().segment('👨‍👩‍👧‍👦')].length
< 1
> '👨‍👩‍👧‍👦'.length
< 11
> [...'👨‍👩‍👧‍👦'].length]
< 7
```

<img width="582" height="237" alt="image" src="https://github.com/user-attachments/assets/cb398309-0a70-4c57-8d24-ff76fce8731d" />

So, I guess I am asking again, what are you trying to do here?

(See more at https://www.ibm.com/docs/en/watson-libraries?topic=tasks-character#emoji-with-zero-width-joiner)

2025-08-29 09:44 UTC, mcdurdin commented on common/web/types/src/util/util.ts
> +    const num_str = instr.substring(instr.indexOf("x") + 1, instr.length - 1);
> done in [14569](https://github.com/keymanapp/keyman/pull/14569)

From a process perspective, the fixes need to land in this PR, because this PR is where they are implemented. We can't merge this PR until those fixes are in place here.

2026-02-16 11:21 UTC, mcdurdin commented on common/web/types/src/util/kmcConvertUtil.ts
This file should be removed from this PR

2026-02-16 11:21 UTC, mcdurdin commented on common/web/types/src/util/util.ts
This has whitespace changes only; please revert to base version

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/common/web/utils/src/index.ts
> +export { KeylayoutXMLSourceFile } from './types/keylayout/keylayout-xml.js';
```suggestion
export * as Keylayout from './types/keylayout/keylayout-xml.js';
```

Best to have just the one export, to avoid multiple ways of importing the same symbol. (So it would be `Keylayout.KeylayoutXMLSourceFile`)

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/common/web/utils/src/types/keylayout/keylayout-xml.ts
> + * Keyman is 2025 copyright (C) SIL International. MIT License.
```suggestion
 * Keyman is copyright (C) SIL Global. MIT License.
```

From https://github.com/keymanapp/keyman/wiki/Keyman-Code-Style-Guide#file-header

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/common/web/utils/src/types/keylayout/keylayout-xml.ts
> +export interface KL_Layout {
Try to make the spacing consistent, e.g.

```suggestion
};

export interface KL_Layout {
```

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/common/web/utils/src/types/keylayout/keylayout-xml.ts
> +export interface KL_modifierMap {
```suggestion
};

export interface KL_modifierMap {
```

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/common/web/utils/src/xml-utils.ts
> +
```suggestion
```

please remove debug code

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/common/web/utils/src/xml-utils.ts
> +    attributeNamePrefix: '@_', // avoid @_
```suggestion
    attributeNamePrefix: '@__', 
```

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/common/web/utils/src/xml-utils.ts
> +  private static fixupEmptyStringToEmptyObject_keylayout(data: any) : any {
We should be able to use `fixupEmptyStringToEmptyObject` and not need to duplicate this

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/common/web/utils/src/xml-utils.ts
> +      result = KeymanXMLReader.fixupEmptyStringToEmptyObject_keylayout(result);
```suggestion
```

We'll be using `fixupEmptyStringToEmptyObject` so this should not be required

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/kmc-convert/build.sh
> +
Given that the file keylayout.schema.json is already added to the repository, we shouldn't need to generate this on every build.

```suggestion
```

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/kmc-convert/build.sh
> +builder_run_action test        do_kmc_convert_test
```suggestion
```

We don't normally run actions more than once for a script, so if you did want to do this, you'd make the call to `do_kmc_convert_test` at the start of `do_test`. (But in this case, we don't need to do it anyway, see previous comment)

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/kmc-convert/build.sh
> +builder_run_action test        do_kmc_convert_test
```suggestion
```

We don't normally run actions more than once for a script, so if you did want to do this, you'd make the call to `do_kmc_convert_test` at the start of `do_test`. (But in this case, we don't need to do it anyway, see previous comment)

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/kmc-convert/package.json
> +    "ajv": "^8.17.1"
`ajv` should be under `devDependencies`. We should try and keep the version consistent across all usages (currently, other parts of the project use `^8.12.0`, so if possible match that version).

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/kmc-convert/src/convert-utils.ts
Please remove this empty file

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/kmc-convert/src/converter-messages.ts
> +    `Input file '${def(o.inputFilename)} ' could not be read.`
```suggestion
    `Input file '${def(o.inputFilename)}' could not be read.`
```

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/kmc-convert/src/converter-messages.ts
> +    `Input file '${def(o.inputFilename)} ' could not be converted.`
```suggestion
    `Input file '${def(o.inputFilename)}' could not be converted.`
```

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/kmc-convert/src/converter-messages.ts
> +    `Output file for '${def(o.outputFilename)} ' could not be written.`
```suggestion
    `Output file for '${def(o.outputFilename)}' could not be written.`
```

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/kmc-convert/src/converter-messages.ts
> +    `INFO: Input file ${def(o.inputFilename)} contains unsupported character '${def(o.output)} ' at keyMap index ${def(o.keymap_index)} on Keycode ${def(o.key)} (${def(o.KeyName)})`
```suggestion
    `INFO: Input file ${def(o.inputFilename)} contains unsupported character '${def(o.output)}' at keyMap index ${def(o.keymap_index)} on Keycode ${def(o.key)} (${def(o.KeyName)})`
```

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-file-reader.ts
> + * Keyman is 2025 copyright (C) SIL International. MIT License.
almost done -- don't include the year (and org name has changed too):

```suggestion
 * Keyman is copyright (C) SIL Global. MIT License.
```

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-file-reader.ts
> +import { KeylayoutXMLSourceFile } from "@keymanapp/developer-utils";
```suggestion
import { XMLParser } from 'fast-xml-parser';
import { CompilerCallbacks, DeveloperUtilsMessages, KeylayoutXMLSourceFile } from "@keymanapp/developer-utils";
import { util, SchemaValidators } from '@keymanapp/common-types';
import { ConverterMessages } from '../converter-messages.js';
```

See https://github.com/keymanapp/keyman/wiki/Keyman-Code-Style-Guide#imports-typescript-nodejs-etc for preferred import order.

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-file-reader.ts
> +
```suggestion
```

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-file-reader.ts
> +      attributeNamePrefix: '@_',    // to access the attribute
```suggestion
      attributeNamePrefix: '@__',    // to access the attribute
```

We should match the other usages (e.g. LDML files)

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> + * Keyman is 2025 copyright (C) SIL International. MIT License.
Please match wiki style guide

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
>  import { ConverterToKmnArtifacts } from "../converter-artifacts.js";
Can combine these

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +export interface ProcesData {
Should this be `ProcessData`? Also, I am not sure what this interface name means?

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +export function find_usedKeysCount(data: any, pos: number): number {
```suggestion
export function findUsedKeysCount(data: any, pos: number): number {
```

Generally, we don't use underscores in method names in Typescript

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +    outputFilename = outputFilename ?? inputFilename.replace(/\.keylayout$/, '.kmn');
This should not be needed because we've noted `outputFilename` as required on l.108.

```suggestion
```

Or, perhaps better, keep `outputFilename` as optional and remove l.108 test

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +    }
We generally have failure conditions handled first, so that we don't "nest the good path".

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +      data_object.keylayout_filename = outputfilename.replace(/\.kmn$/, '.keylayout');
If we need `keylayout_filename` then we should use the value we already have from `run` instead of recalculating it here

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +      data_object.kmn_filename = outputfilename;
The `kmn_filename` property should not be required as this is only used in an error message in `write`, and the error message is about encoding rather than about file system.

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +      data_object.keylayout_filename = outputfilename.replace(/\.kmn$/, '.keylayout');
Technically, should use `keylayoutFilename` :grin:

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +          singleModifierSet.push(jsonObj.keyboard.modifierMap.keyMapSelect[j].modifier[k]['@_keys']);
We'll need to fixup all `@_` to `@__`

2026-02-16 11:21 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +      KeylayoutToKmnConverter.USE_KEY_COUNT = find_usedKeysCount(jsonObj, behav);
```suggestion
      // fix the amount of processable keys to the maximun nr of keys of a keyMap to avoid processing more keys than defined
      KeylayoutToKmnConverter.USE_KEY_COUNT = find_usedKeysCount(jsonObj);
```

This function is only used once, so we should be able to eliminate the const `behav` parameter.

2026-02-16 11:23 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +import { KeylayoutXMLSourceFile } from '../../../common/web/utils/src/types/keylayout/keylayout-xml.js';
This should be imported from `@keymanapp/developer-utils`

2026-02-23 15:52 UTC, SabineSIL commented
all comments have been addressed

2026-03-10 08:24 UTC, mcdurdin requested changes
Here's my latest round of comments -- we're getting closer!

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/common/web/utils/src/types/keylayout/keylayout-xml.ts
> + * The prefix KL is stands for 'Keylayout'
Might be good to reference what a keylayout file is here

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/common/web/utils/src/types/keylayout/keylayout-xml.ts
> +export interface KL_Layout {
These two interfaces use a different casing scheme than the other interfaces. Normally, an interface name will use TitleCase rather than camelCase. Suggest that we move all others to the same casing (e.g. `KL_keyboard` -> `KL_Keyboard`).

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/common/web/utils/src/xml-utils.ts
> +
```suggestion
```

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/build.sh
> +
```suggestion
```

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/converter.ts
> +    const result = await converter.run(inputFilename, outputFilename);
This means `binaryData` is no longer used? We shouldn't be reading the same file twice.

2026-03-10 08:24 UTC, mcdurdin commented on resources/standards-data/keylayout/readme.md
Please name this file README.md

2026-03-10 08:24 UTC, mcdurdin commented on resources/standards-data/keylayout/readme.md
> +<small><span style="color: grey"> e.g. resources\standards-data\keylayout\dtd\keylayout.xsd  </small> <br></br>
Can we restrict these internal documentation files to markdown and avoid HTML as far as possible, for future maintainers' sake?

```suggestion
e.g. `resources\standards-data\keylayout\dtd\keylayout.xsd`

```

Here and below

2026-03-10 08:24 UTC, mcdurdin commented on resources/standards-data/keylayout/readme.md
> +This is to get a **keylayout.schema.json** for validating keylayout files
We need to describe what a keylayout file is here as well -- if a developer encounters this folder, they want to know what the file format is for.

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +export interface ProcessedData {
Each exported interface really should have a documentation comment describing its purpose. Ideally each field is documented also. Also for `KeylayoutFileData` and `Rule`

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +  arrayOfRules: Rule[],
```suggestion
  keylayoutFilename: string;
  kmnFilename: string;
  modifiers: string[][];
  rules: Rule[];
```

Avoid using the type in the name of the variable (i.e. just `modifiers` not `arrayOfModifiers`)

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +  outchar?: string;
```suggestion
  actionId?: string;
  keyCode?: string;
  key?: string;
  behaviour?: string;
  modifier?: string;
  outchar?: string;
```

We should probably also spell `behaviour` as `behavior` because generally we use US spelling for consistency. (Speaking here as an Australian, this pains me, but inconsistency is worse!)

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +  output: string,
```suggestion
  id: string;
  state: string;
  output: string;
```

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +  let usedKeyCount = KeylayoutToKmnConverter.MAX_KEY_COUNT;
Why do we need a fixed MAX_KEY_COUNT?

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +  constructor(private callbacks: CompilerCallbacks, options: CompilerOptions) { };
We still don't want this constructor!

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-file-reader.ts
> +  public read(inputFilename: string): Keylayout.KeylayoutXMLSourceFile {
This should be taking a `Uint8Array` binary blob, not a filename. Our file-readers all accept `Uint8Array` as input.

To read as UTF8, use the following pattern:

```ts
  public read(file: Uint8Array): Keylayout.KeylayoutXMLSourceFile {
    const data = new TextDecoder().decode(file);
    const parser = new XMLParser(options);
    const jsonObj = parser.parse(data);
```

In fact, you should also be using `KeymanXMLReader`, which centralizes all the XML parsing and where you have duplicated the `options` for keylayout files already.

So, something like:

```ts
  public read(file: Uint8Array): Keylayout.KeylayoutXMLSourceFile {
    const data = new TextDecoder().decode(file);

    let result: Keylayout.KeylayoutXMLSourceFile;
    try {
      result = new KeymanXMLReader('keylayout')
       .parse(data) as Keylayout.KeylayoutXMLSourceFile;
    } catch(e) {
      this.callbacks.reportMessage(ConverterMessages.Error_UnableToRead({e}));
    }

    if(!result) {
      return null;
    }

    this.boxArray(result.keyboard);   // result now contains arrays; no single fields
    return result;
  }
```

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +    const outUint8: Uint8Array = kmnFileWriter.write(outArray);
Don't embed the type into the variable name:

```suggestion
    const outputKmn = kmnFileWriter.write(processedData);
```

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +    const outArray: ProcessedData = await this.convert(jsonO, inputFilename);
```suggestion
    const processedData = await this.convert(jsonO, inputFilename);
    if(!processedData) {
      // Error already written by this.convert
      return null;
    }
```

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +    } else {
Three things here:

1. Wasn't validation already done on line 109?
2. The failure case should `return null`, not an empty valid object.
3. `else {` is not needed because the `if() {}` clause returns.
You don't need `else { ... }` if the `if()` clause ends with `return`. Just use `if() {... return dataObject; }

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +      dataObject.kmnFilename = inputfilename.replace(/\.kkeylayoutn$/, '.kmn');;
Is the extension really `.kkeylayoutn`?

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +      dataObject.kmnFilename = inputfilename.replace(/\.kkeylayoutn$/, '.kmn');;
```suggestion
      dataObject.kmnFilename = inputfilename.replace(/\.kkeylayoutn$/, '.kmn');
```

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +      }
Here you do `modifierState[i].toUpperCase()` repeatedly. Better to introduce a local and do it just once: 

```ts
      const modifier = modifierState[i].toUpperCase();
```

Or better yet:

```ts
    const modifierState = keylayoutModifier.toUpperCase().split(" ");
    for (const modifier of modifierState) {
```

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +        addModifier = modifierState[i] + " ";
Is this right? Will it push modifiers that Keyman doesn't know about into the modifier string?

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +      }
Why do you use `.includes()` here but `===` in other tests below?

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +    const duplicateModifierArray: string[] = kmnModifier.split(" ").filter(item => item);
It'd be better to be building up an array rather than building up a string in the loop, and skip the split step here.

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +    return JSON.stringify(keylayoutModifier).toUpperCase().includes("CAPS");
This is a bit of a nasty hammer to use on this problem. Would be better to flatten the array

```suggestion
    return keylayoutModifier.flat().find(e => e.toUpperCase() === 'CAPS');
```

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +    return iskKeymanModifier;
```suggestion
    const modifierSingle = keylayoutModifier.toUpperCase().split(" ");
    for(const mod of modifierSingle) {
      if(!mod.match(/^(NCAPS|CAPS|SHIFT|ALT|RALT|LALT|CTRL|LCTRL|RCTRL|)$/) {
        return false;
      }
    }
    return true;
```

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +      "K_?C1"        /* \ */,   // 48 for ANSI  correct??
Is this really `K_?C1`? I would have expected this to be `K_oE2`?

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +    return 0;
I'm not sure why you return the first entry in the array rather than `null` or `-1` -- and that's assuming the array isn't empty?

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +    let returnObject: KeylayoutFileData;
```suggestion
```

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +            returnObject = {
```suggestion
            const returnObject: KeylayoutFileData = {
```

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +            returnObject = {
```suggestion
            const returnObject: ActionStateOutput = {
```

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +    let returnObject: ActionStateOutput;
```suggestion
```

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +          returnObject = {
```suggestion
          const returnObject: KeylayoutFileData = {
```

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +    let returnObject: KeylayoutFileData;
```suggestion
```

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +            returnObject = {
Same pattern, declare the variable here

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +          returnObject = {
Ditto

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +export class Rule {
Can we move this further up in the file?

And can the members be `public readonly`? Or do they change after instantiation?

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/kmn-file-writer.ts
> + * Write Keyman .kmn files
```suggestion
 * Write Keyman .kmn files from an in-memory representation generated
 * from .keylayout files
```

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/kmn-file-writer.ts
> +      this.callbacks.reportMessage(ConverterMessages.Error_UnableToWrite({ outputFilename: dataUkelele.kmnFilename }));
This masks `err` -- we need to report what `err` was here:

```suggestion
      this.callbacks.reportMessage(ConverterMessages.Error_UnableToWrite({ outputFilename: dataUkelele.kmnFilename, error: err }));
```

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/kmn-file-writer.ts
> +        // TODO after merge of PR 14564 use functions from util instead of the ones in this class
TODO here

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/kmn-file-writer.ts
> +        // TODO after merge of PR 14564 use functions from util instead of the ones in this class
```suggestion
        // TODO-kmc-convert: after merge of PR 14564 use functions from util instead of the ones in this class
```

2026-03-10 08:24 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/kmn-file-writer.ts
> +        // TODO after merge of PR 14564 use functions from util instead of the ones in this class
```suggestion
        // TODO-kmc-convert: after merge of PR 14564 use functions from util instead of the ones in this class
```

2026-03-25 15:14 UTC, SabineSIL reviewed
all comments addressed. see coments/need clarification on: 

[`MAX_KEY_COUNT`](https://github.com/keymanapp/keyman/pull/12564#discussion_r2909410166)

[unknown modifiers](https://github.com/keymanapp/keyman/pull/12564#discussion_r2909764917): kmc-convert allows them at present. Do we want to allow them?

 [pass binaryData](https://github.com/keymanapp/keyman/pull/12564#discussion_r2909366707)


> Shouldn't need a constructor 😁 - per the `KeymanCompiler` interface.
 [no use of constructor in  keylayout-to-kmn/keylayout-to-kmn-converter.ts](https://github.com/keymanapp/keyman/pull/12564/changes#r2084888814)

2026-03-25 15:14 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +export class Rule {
moved; some can be readonly

2026-03-25 15:14 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +        addModifier = modifierState[i] + " ";
I found several keylayout files ( e.g. italian.keylayout) that use a modifier  "command". After conversion this unknown modifier will be available in the .kmn file and has to be handled there by the user.

2026-03-25 15:14 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +      }
changed

2026-03-25 15:14 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +      }
changed: use of a  variable modifier and modifierUppercase to be able to add other modifiers ( see explanation below)

2026-03-25 15:14 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +  let usedKeyCount = KeylayoutToKmnConverter.MAX_KEY_COUNT;
all .keylayout files I found use more than the 50 keys we use in Keyman. This is to use only 50 keys

2026-03-25 15:14 UTC, SabineSIL commented on developer/src/kmc-convert/src/converter.ts
> +    const result = await converter.run(inputFilename, outputFilename);
do you mean pass binary into run() of  KeylayoutToKmnConverter like: 
```

- converter.ts:   

   - load data, (binaryData = this.callbacks.loadFile(inputFilename))
   - create outputfile name  from inputfilename (if outputfilename is not available)
   - run(inputFilename, outputFilename, binaryData);
 

- keylayout-to-kmn-converter.ts:

  - convert(), 
  - write()

```
or only pass the filename(s)
```

- converter.ts:   
  - run(inputFilename, outputFilename?)

keylayout-to-kmn-converter.ts :  
  - create outputfile name  from inputfilename if outputfilename is not available
  - load data, (binaryData = this.callbacks.loadFile(inputFilename)))
  - convert(), 
  - write()

```
if I look at other run() functions of modules implementing KeymanCompiler they pass only filenames

2026-04-01 08:30 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +  let usedKeyCount = KeylayoutToKmnConverter.MAX_KEY_COUNT;
I think that the name should reflect that this is the highest key code that we support rather than specifically a number of keys?

2026-04-01 08:32 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +        addModifier = modifierState[i] + " ";
I think we need to generate a warning and skip the key for unknown modifiers; leaving a commented out rule is fine. The principle is that we want to have a file that compiles.

2026-04-01 08:33 UTC, mcdurdin commented on developer/src/kmc-convert/src/converter.ts
> +    const result = await converter.run(inputFilename, outputFilename);
> or only pass the filename(s)

This matches other modules, so we'll go this way.

2026-04-01 09:02 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +  constructor(private callbacks: CompilerCallbacks, options: CompilerOptions) { };
My mistake -- this is not a `KeymanCompiler` implementation but an internal class in kmc-convert, so doing this in the constructor is fine. But then we need to delete `init()` and use just the constructor:

```suggestion
  constructor(private callbacks: CompilerCallbacks, options: CompilerOptions) { 
    this.options = { ...options };
  };
```

2026-04-09 12:50 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +  let usedKeyCount = KeylayoutToKmnConverter.MAX_KEY_COUNT;
changed to   MAX_KEY_IDENTIFIER and USED_KEY_IDENTIFIER

2026-04-09 12:50 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +        addModifier = modifierState[i] + " ";
messages might look like this: 
<img width="832" height="131" alt="image" src="https://github.com/user-attachments/assets/73c225ca-e17b-4172-97cd-272991396725" />

2026-04-09 12:50 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +  constructor(private callbacks: CompilerCallbacks, options: CompilerOptions) { };
done

2026-04-09 12:50 UTC, SabineSIL reviewed
All comments have been addressed: 

- uses KeymanXMLReader now
- removeWhitespace() is not neccessary any more when using KeymanXMLReader
- KeylayoutToKmnConverter uses constructor/no init()
- uses MAX_KEY_IDENTIFIER and dismisses USED_KEY_IDENTIFIER
- unknown modifiers and other messages:
<img width="848" height="202" alt="Image" src="https://github.com/user-attachments/assets/ab2fba79-4e14-45b0-8dd5-35289d638b9a" />

2026-04-21 14:22 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +  let usedKeyCount = KeylayoutToKmnConverter.MAX_KEY_COUNT;
USED_KEY_IDENTIFIER removed altogether along with findUsedKeysCount()

2026-04-22 14:21 UTC, mcdurdin reviewed
I'm going to stop here on this code review -- I've looked mainly at the source file format for keylayout and compared to the Apple docs at [TN2056](https://developer.apple.com/library/archive/technotes/tn2056/_index.html).

Once you apply the `Keylayout.KeylayoutXMLSourceFile` type to the `convert()` `jsonObj` parameter, I suspect that a number of other compile errors will emerge -- these should help to tighten up the code.

2026-04-22 14:21 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-file-reader.ts
> +    }
I think the boxing is not quite right. Any element that can be repeated needs to be boxed, in case there are only 1 or 0 of them. Once boxed, the property will become an array, so it's safe to reference.

This matches more closely to the spec, I think:

```suggestion
    boxXmlArray(source, 'modifierMap');
    boxXmlArray(source, 'keyMapSet');
    
    if(source.layouts) {
      boxXmlArray(source.layouts, 'layout');
    }

    if(source.modifierMap) {
      for(const modifierMap of source.modifierMap) {
        boxXmlArray(modifierMap, 'keyMapSelect');
        if(modifierMap.keyMapSelect) {
          for (const keyMapSelect of source.modifierMap.keyMapSelect) {
            boxXmlArray(keyMapSelect, 'modifier');
          }
        }
      }
    }

    for (const keyMapSet of source.keyMapSet) {
      boxXmlArray(keyMapSet, 'keyMap');
      for (const keyMap of keyMapSet.keyMap) {
        boxXmlArray(keyMap, 'key');
      }
    }

    if(source.actions) {
      boxXmlArray(source.actions, 'action');
      for (const action of source.actions.action) {
        boxXmlArray(action, 'when');
      }
    }

    boxXmlArray(source?.terminators, 'when');
```

2026-04-22 14:21 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-file-reader.ts
> +      this.boxArray(jsonObj.keyboard);            // jsonObj now contains arrays; no single fields
```suggestion
      if(!jsonObj?.keyboard) {
        // TODO: report an error
        return null;
      }
      this.boxArray(jsonObj.keyboard);            // jsonObj now contains arrays; no single fields
```

2026-04-22 14:21 UTC, mcdurdin commented on developer/src/common/web/utils/src/types/keylayout/keylayout-xml.ts
> +  layouts?: KL_Layouts[];
This is created as an array here but the array appears actually to be the child element layouts.layout? It seems it is unused so slipping through but should be corrected.

Also, per TN2056 it is not optional:

```suggestion
  layouts: KL_Layouts[];
```

2026-04-22 14:21 UTC, mcdurdin commented on developer/src/common/web/utils/src/types/keylayout/keylayout-xml.ts
> +  //layoutsMM: KL_Layouts[];
```suggestion
```

2026-04-22 14:21 UTC, mcdurdin commented on developer/src/common/web/utils/src/types/keylayout/keylayout-xml.ts
> +   */
This comment is attached to the `group` property as a javadoc-style comment. This is probably not what you want. As it is a structural comment, you could either go with (my preference):

```suggestion
  // attributes of the root element <keyboard>
```

or:

```suggestion
  /*
   * attributes of the root element <keyboard>
   */
```

This needs to be corrected throughout this file.

You have the option to add javadoc-style comments above the interface itself and/or for each property.

2026-04-22 14:21 UTC, mcdurdin commented on developer/src/common/web/utils/src/types/keylayout/keylayout-xml.ts
> +   */
```suggestion
  /*
   * <layouts>, <modifierMap>, <keyMapSet>, <actions>, <terminators>
   * the 5 main elements.
   * 
   * The keyboard element must contain exactly one <layouts> element, one or more <modifierMap> elements, one or more <keyMapSet> elements, an optional <actions> element, and an optional <terminators> element. (Source: TN2056)
   */
```

2026-04-22 14:21 UTC, mcdurdin commented on developer/src/common/web/utils/src/types/keylayout/keylayout-xml.ts
> +  layouts?: KL_Layout;
```suggestion
  layout: KL_Layout[];
```

2026-04-22 14:21 UTC, mcdurdin commented on developer/src/common/web/utils/src/types/keylayout/keylayout-xml.ts
> +  index?: string;
missing `baseMapSet` and `baseIndex` optional attributes (per TN2056)


```suggestion
  index: string;
  baseMapSet?: string;
  baseIndex?: string;
```

2026-04-22 14:21 UTC, mcdurdin commented on developer/src/common/web/utils/src/types/keylayout/keylayout-xml.ts
> +  action?: string;
Note that `action` can be either an attribute or a sub-element - and they have different content - when an attribute, it is the name of an action from the `<actions>` element; when a sub-element, it is an 'anonymous action'.

I don't know how widely the 'anonymous action' form is used, but we need to at least mark this as a TODO:


```suggestion
  action?: string;  //TODO-KMC-CONVERT: Support <action> sub-element 'anonymous actions'
```

2026-04-22 14:21 UTC, mcdurdin commented on developer/src/common/web/utils/src/types/keylayout/keylayout-xml.ts
> +  next?: string;
`through`, `multiplier` attributes missing

2026-04-22 14:21 UTC, mcdurdin commented on developer/src/common/web/utils/src/types/keylayout/keylayout-xml.ts
> +  terminators?: KL_Terminators[];
```suggestion
  modifierMap: KL_ModifierMap[];
  keyMapSet: KL_KeyMapSet[];
  actions?: KL_Actions;
  terminators?: KL_Terminators;
```

Per TN2056

2026-04-22 14:21 UTC, mcdurdin commented on developer/src/common/web/utils/src/types/keylayout/keylayout-xml.ts
> +  maxoutS?: string;
```suggestion
  group: string;
  id: string;
  name: string;
  maxout?: string;
```

These are all required, except `maxout` (which was mislabeled `maxoutS`?).

2026-04-22 14:21 UTC, mcdurdin commented on developer/src/common/web/utils/src/types/keylayout/keylayout-xml.ts
> +  modifiers?: string;
```suggestion
  first: string;
  last: string;
  mapSet: string;
  modifiers: string;
```

2026-04-22 14:21 UTC, mcdurdin commented on developer/src/common/web/utils/src/types/keylayout/keylayout-xml.ts
> +  defaultIndex?: string;
```suggestion
  id: string;
  defaultIndex: string;
```

2026-04-22 14:21 UTC, mcdurdin commented on developer/src/common/web/utils/src/types/keylayout/keylayout-xml.ts
> +  keyMapSelect?: KL_KeyMapSelect[];
```suggestion
  keyMapSelect: KL_KeyMapSelect[];
```

2026-04-22 14:21 UTC, mcdurdin commented on developer/src/common/web/utils/src/types/keylayout/keylayout-xml.ts
> +  modifier?: KL_Modifier[];
```suggestion
  mapIndex: string;
  /**
   * <modifier> the sub element of <keyMapSelect>
   */
  modifier: KL_Modifier[];
```

2026-04-22 14:21 UTC, mcdurdin commented on developer/src/common/web/utils/src/types/keylayout/keylayout-xml.ts
> +  keys?: string;
```suggestion
  keys: string;
```

2026-04-22 14:21 UTC, mcdurdin commented on developer/src/common/web/utils/src/types/keylayout/keylayout-xml.ts
> +  keyMap?: KL_KeyMap[];
```suggestion
  id: string;
  /**
   * <keyMap> the sub element of <keyMapSet>
   */
  keyMap: KL_KeyMap[];
```

2026-04-22 14:21 UTC, mcdurdin commented on developer/src/common/web/utils/src/types/keylayout/keylayout-xml.ts
> +  key?: KL_Key[];
```suggestion
  key: KL_Key[];
```

2026-04-22 14:21 UTC, mcdurdin commented on developer/src/common/web/utils/src/types/keylayout/keylayout-xml.ts
> +  code?: string;
```suggestion
  code: string;
```

2026-04-22 14:21 UTC, mcdurdin commented on developer/src/common/web/utils/src/types/keylayout/keylayout-xml.ts
> +  action?: KL_Action[];
```suggestion
  action: KL_Action[];
```

2026-04-22 14:21 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +export interface ProcessedData {
The doc comment needs to go above the `export interface ProcessedData {` line!

2026-04-22 14:21 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +  private convert(jsonObj: any, inputfilename: string, outputFilename?: string): ProcessedData {
```suggestion
  private convert(jsonObj: Keylayout.KeylayoutXMLSourceFile, inputfilename: string, outputFilename?: string): ProcessedData {
```

We have the type, we need to use it!

2026-04-22 14:21 UTC, mcdurdin commented on resources/standards-data/keylayout/dtd/keylayout.dtd
> +<!ATTLIST key (action #REQUIRED output #IMPLIED | output #REQUIRED action #IMPLIED)>
We should use the TN2056 DTD if possible, unless it doesn't match reality:

```
<!-- Overall structure -->
<!ELEMENT keyboard (layouts+, modifierMap+, keyMapSet+, actions*, terminators*)>
<!ATTLIST keyboard group NMTOKEN #REQUIRED >
<!ATTLIST keyboard id NMTOKEN #REQUIRED >
<!ATTLIST keyboard name CDATA #REQUIRED >
<!ATTLIST keyboard maxout NMTOKEN #IMPLIED >

<!-- Hardware layout elements -->
<!ELEMENT layouts (layout+) >
<!ELEMENT layout EMPTY >
<!ATTLIST layout first NMTOKEN #REQUIRED >
<!ATTLIST layout last NMTOKEN #REQUIRED >
<!ATTLIST layout modifiers IDREF #REQUIRED >
<!ATTLIST layout mapSet IDREF #REQUIRED >

<!-- Modifier descriptions -->
<!ELEMENT modifierMap (keyMapSelect+) >
<!ATTLIST modifierMap id ID #REQUIRED >
<!ATTLIST modifierMap defaultIndex NMTOKEN #REQUIRED >

<!ELEMENT keyMapSelect (modifier+) >
<!ATTLIST keyMapSelect mapIndex NMTOKEN #REQUIRED >

<!ELEMENT modifier EMPTY >
<!ATTLIST modifier keys CDATA #REQUIRED >

<!-- Keyboard mapping -->
<!ELEMENT keyMapSet (keyMap+) >
<!ATTLIST keyMapSet id ID #REQUIRED >

<!ELEMENT keyMap (key+) >
<!ATTLIST keyMap index NMTOKEN #REQUIRED >
<!ATTLIST keyMap baseMapSet IDREF #IMPLIED >
<!ATTLIST keyMap baseIndex NMTOKEN #IMPLIED >

<!ELEMENT key (action*) >
<!ATTLIST key code NMTOKEN #REQUIRED >
<!ATTLIST key output CDATA #IMPLIED >
<!ATTLIST key action IDREF #IMPLIED >

<!-- Actions (state records) -->
<!ELEMENT actions (action+) >
<!ELEMENT action (when+) >
<!ATTLIST action id ID #IMPLIED >

<!ELEMENT when EMPTY >
<!ATTLIST when state NMTOKEN #REQUIRED >
<!ATTLIST when through NMTOKEN #IMPLIED >
<!ATTLIST when output CDATA #IMPLIED >
<!ATTLIST when multiplier NMTOKEN #IMPLIED >
<!ATTLIST when next NMTOKEN #IMPLIED >

<!-- Terminators -->
<!ELEMENT terminators (when+) >
```

2026-04-22 14:21 UTC, mcdurdin commented on resources/standards-data/keylayout/dtd/keylayout.xsd
> +        <xs:element name="layouts">
We can add some constraints, e.g. layouts may be only 1 so `minOccurs="1" maxOccurs="1"`. Need to review each element.

2026-04-28 20:46 UTC, SabineSIL reviewed
..the present round of comments on [12564 ](#12564 )is finished. 
Note that squiggely lines for 'return null' ,unclear defined return types etc.  are already or will be addressed in PR [15860](#15860 ) I left most of them unchanged in 12564

2026-05-15 09:40 UTC, mcdurdin commented on developer/src/common/web/utils/src/types/keylayout/keylayout-xml.ts
> +  layouts?: KL_Layouts[];
And, according to [TN2056](https://developer.apple.com/library/archive/technotes/tn2056/_index.html#//apple_ref/doc/uid/DTS10003085-CH1-SUBSECTION4):

> The keyboard element must contain exactly one `<layouts>` element.

So:

```suggestion
  layouts: KL_Layouts;
```

2026-05-15 09:40 UTC, mcdurdin commented on resources/standards-data/keylayout/dtd/keylayout.dtd
> +<!ATTLIST key (action #REQUIRED output #IMPLIED | output #REQUIRED action #IMPLIED)>
According to the text of the spec, the sub-elements of `<keyboard>` are more constrained than the DTD. So I would do this:

```
<!-- 
  TN2056 has looser constraints in the DTD than the text of the TN, so we 
  tightened the quantifiers according to the descriptive text.
  TN2056: <!ELEMENT keyboard (layouts+, modifierMap+, keyMapSet+, actions*, terminators*)>
 -->
<!ELEMENT keyboard (layouts, modifierMap+, keyMapSet+, actions?, terminators?)>
```

2026-05-15 09:40 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-file-reader.ts
> +      this.callbacks.reportMessage(ConverterMessages.Error_UnableToRead());
```suggestion
      this.callbacks.reportMessage(ConverterMessages.Error_UnableToRead({err}));
```
Pass the parsing error through to the error message

2026-05-15 09:40 UTC, mcdurdin commented on developer/src/kmc-convert/src/converter-messages.ts
> +  );
This should be at the bottom of the file

2026-05-15 09:40 UTC, mcdurdin commented on developer/src/kmc-convert/src/converter-messages.ts
> +  );
These four messages look very similar. Are they all separate errors?

2026-05-15 09:40 UTC, mcdurdin commented on developer/src/kmc-convert/src/converter.ts
>      }
This is an API usage error, so it should throw rather than report a message, because it's not something the keyboard author/user can fix.


```suggestion
    if (!inputFilename) {
      throw new Error('Input filename is required');
    }
```

2026-05-15 09:40 UTC, mcdurdin commented on developer/src/kmc-convert/src/converter-messages.ts
> +    `${def(o.inputFilename)}: Action id ${def(o.action)} of key ${def(o.KeyName)} in keymapIndex ${def(o.keymapIndex)} is not defined`
inputFilename should not be needed because that is provided by kmc directly to the message printer

2026-05-15 09:40 UTC, mcdurdin commented on developer/src/kmc-convert/test/data/Test.keylayout
> +<!DOCTYPE keyboard SYSTEM "../../../../../resources/standards-data/Keylayout/Keylayout.dtd">
```suggestion
<!DOCTYPE keyboard SYSTEM "../../../../../resources/standards-data/keylayout/dtd/keylayout.dtd">
```

2026-05-15 09:40 UTC, mcdurdin commented on developer/src/kmc-convert/test/data/Test_ambiguous_keys.keylayout
> +<!DOCTYPE keyboard SYSTEM "../../../../../resources/standards-data/Keylayout/Keylayout.dtd">
Pls check all the doctypes 😄

2026-05-15 09:40 UTC, mcdurdin commented on developer/src/kmc-convert/test/kmn-file-reader.tests.ts
> + * Tests for KeylayoutToKmnConverter, KeylayoutFileReader, KmnFileWriter
```suggestion
 * Tests for KeylayoutFileReader
```

2026-05-15 09:40 UTC, mcdurdin commented on developer/src/kmc-convert/test/keylayout-file-reader.tests.ts
Should be called keylayout-file-reader.tests.ts

2026-05-15 09:40 UTC, mcdurdin commented on developer/src/kmc-convert/test/kmn-file-writer.tests.ts
> + * Tests for KeylayoutToKmnConverter, KeylayoutFileReader, KmnFileWriter
```suggestion
 * Tests for KmnFileWriter
```

2026-05-15 09:40 UTC, mcdurdin commented on developer/src/kmc-convert/test/data/keylayout.dtd
There are two copies of this file - one in test data and one in resources. We should only have the one in resources.

2026-05-15 09:40 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/kmn-file-writer.ts
> +export interface messageCharacter {
```suggestion
interface MessageCharacter {
```

2026-05-15 09:40 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/kmn-file-writer.ts
> +  public reviewRules(rule: Rule[], index: number): string[] {
Let's refactor the return value into an interface with `isDuplicate: boolean` flag and the like.

Also: private I think?


```suggestion
  private reviewRules(rule: Rule[], index: number): ReviewRulesResult {
```

or something like:

```suggestion
  public reviewRules(rule: Rule[], index: number): {isDuplicate:boolean, warningText: string} {
```

(I prefer to define the interface; it's more maintainable and documentable.

2026-05-15 09:40 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +    }
This should throw as it is an API usage error, not an end user error

2026-05-15 09:40 UTC, mcdurdin commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +  public convertBound = {
```suggestion
  public unitTestEndpoints = {
```

This is our [normal pattern](https://github.com/keymanapp/keyman/wiki/Unit-Tests#typescript) for unit test exposure of internal functions

2026-05-15 09:40 UTC, mcdurdin commented on developer/src/kmc-convert/test/keylayout-to-kmn-converter.tests.ts
> +        sut.run(files[0]);
```suggestion
    [
      'Test_C0.keylayout',
      'Test_C1.keylayout',
      'Test_C2.keylayout',
      'Test_C2_several.keylayout',
      'Test_C3.keylayout',
      'Test_C3_several.keylayout',
      'Test_C0_C1_C2_C3.keylayout',
      'Test_maxKeyCode.keylayout',
      'Test_messages.keylayout',
      'Test_messages_controlCharacter.keylayout',
      'Test_messages_superior_C2.keylayout',
      'Test_messages_superior_C3.keylayout',
      'Test_duplicate_missing_keycode.keylayout',
      'Test_modifier.keylayout',
      'Test_modifierNoCaps.keylayout',
      'Test_differentAmountOfKeysInBehaviours.keylayout',
      'Test_duplicate_missing_keys.keylayout',
      'Test_duplicate_keys.keylayout',
      'Test_ambiguous_keys.keylayout',
      'Test_nr_elements.keylayout',
      'Test.keylayout',
      'Test_differentEncodings.keylayout',
      'Test_ExtraWarning.keylayout',
    ].forEach(function (file) {
      it(file + " should give no errors ", async function () {
        sut.run(makePathToFixture('../data/'+file));
```

2026-05-15 09:40 UTC, mcdurdin commented on developer/src/kmc-convert/test/kmn-file-reader.tests.ts
> +    it('read() should return empty array on empty input', async function () {
```suggestion
    it('read() should return null on empty input', async function () {
```

2026-05-15 09:40 UTC, mcdurdin commented on developer/src/kmc-convert/test/kmn-file-reader.tests.ts
> +    it('read() should return empty array on space as input', async function () {
```suggestion
    it('read() should return null on space as input', async function () {
```

2026-05-15 09:40 UTC, mcdurdin commented on developer/src/kmc-convert/test/kmn-file-reader.tests.ts
> +    it('read() should return empty array on typo in path', async function () {
```suggestion
    it('read() should return null on unavailable file name', async function () {
      const inputFilenameUnavailable = makePathToFixture('../data/X.keylayout');
      const result = sutR.read(compilerTestCallbacks.loadFile(inputFilenameUnavailable));
      assert.isNull(result);
    });

    it('read() should return null on typo in path', async function () {
```

2026-05-15 09:40 UTC, mcdurdin commented on developer/src/kmc-convert/test/kmn-file-reader.tests.ts
> +      assert.isNotEmpty(result);
It would be good to check that the structure returned is correct, i.e. test the layout of the structure exactly matches the expected JSON with assert.deepEqual or the like

2026-05-15 09:40 UTC, mcdurdin commented on developer/src/kmc-convert/test/kmn-file-reader.tests.ts
Can you add tests for the validation code?

2026-05-20 11:33 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-file-reader.ts
> +      this.callbacks.reportMessage(ConverterMessages.Error_UnableToRead());
done

2026-05-20 11:33 UTC, SabineSIL commented on developer/src/kmc-convert/src/converter-messages.ts
> +  );
done

2026-05-20 11:33 UTC, SabineSIL commented on developer/src/kmc-convert/src/converter-messages.ts
> +  );
done

2026-05-20 11:34 UTC, SabineSIL commented on developer/src/kmc-convert/src/converter.ts
>      }
done

2026-05-20 11:34 UTC, SabineSIL commented on developer/src/kmc-convert/src/converter-messages.ts
> +    `${def(o.inputFilename)}: Action id ${def(o.action)} of key ${def(o.KeyName)} in keymapIndex ${def(o.keymapIndex)} is not defined`
done

2026-05-20 11:34 UTC, SabineSIL commented on developer/src/kmc-convert/test/data/Test.keylayout
> +<!DOCTYPE keyboard SYSTEM "../../../../../resources/standards-data/Keylayout/Keylayout.dtd">
done

2026-05-20 11:34 UTC, SabineSIL commented on developer/src/kmc-convert/test/data/Test_ambiguous_keys.keylayout
> +<!DOCTYPE keyboard SYSTEM "../../../../../resources/standards-data/Keylayout/Keylayout.dtd">
done

2026-05-20 11:34 UTC, SabineSIL commented on developer/src/kmc-convert/test/kmn-file-reader.tests.ts
> + * Tests for KeylayoutToKmnConverter, KeylayoutFileReader, KmnFileWriter
done

2026-05-20 11:34 UTC, SabineSIL commented on developer/src/kmc-convert/test/keylayout-file-reader.tests.ts
done

2026-05-20 11:34 UTC, SabineSIL commented on developer/src/kmc-convert/test/kmn-file-writer.tests.ts
> + * Tests for KeylayoutToKmnConverter, KeylayoutFileReader, KmnFileWriter
done

2026-05-20 11:34 UTC, SabineSIL commented on developer/src/kmc-convert/test/data/keylayout.dtd
done

2026-05-20 11:34 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/kmn-file-writer.ts
> +export interface messageCharacter {
done

2026-05-20 11:35 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/kmn-file-writer.ts
> +  public reviewRules(rule: Rule[], index: number): string[] {
I need to talk about that

2026-05-20 11:35 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +    }
done

2026-05-20 11:35 UTC, SabineSIL commented on developer/src/kmc-convert/src/keylayout-to-kmn/keylayout-to-kmn-converter.ts
> +  public convertBound = {
done

2026-05-20 11:35 UTC, SabineSIL commented on developer/src/kmc-convert/test/keylayout-to-kmn-converter.tests.ts
> +        sut.run(files[0]);
done

2026-05-20 11:35 UTC, SabineSIL commented on developer/src/kmc-convert/test/kmn-file-reader.tests.ts
> +    it('read() should return empty array on empty input', async function () {
done

2026-05-20 11:35 UTC, SabineSIL commented on developer/src/kmc-convert/test/kmn-file-reader.tests.ts
> +    it('read() should return empty array on space as input', async function () {
done

2026-05-20 11:36 UTC, SabineSIL commented on developer/src/kmc-convert/test/kmn-file-reader.tests.ts
> +    it('read() should return empty array on typo in path', async function () {
done

2026-05-20 11:36 UTC, SabineSIL commented on developer/src/kmc-convert/test/keylayout-file-reader.tests.ts
> +      assert.isNotEmpty(result);
done

2026-05-20 11:36 UTC, SabineSIL commented on developer/src/kmc-convert/test/keylayout-file-reader.tests.ts
done

2026-06-02 12:47 UTC, mcdurdin approved these changes
I think this looks good-to-go!

2026-06-02 13:25 UTC, ermshiperete commented
I think it needs the latest changes from `master` to pass Linux source verification.

npm pack/publish fails because it has test failures in kmc-convert.

2026-08-18 13:16 UTC, merged