fix(linux/config): Catch if kmp.json is invalid JSON
keymanapp/keyman pull request #3593
Opened 2020-09-17 07:05 UTC by darcywong00

This catches [JSONDecodeError](https://sentry.keyman.com/organizations/keyman/issues/873/?environment=alpha&project=12) when kmp.json is invalid JSON.

Question: Is it appropriate to exit out? The Keyman config dialog can't really handle if kmp.json is invalid.

2020-09-17 20:21 UTC, mcdurdin requested changes
LNGTM (Nearly). I think if there is no pathway for feeding back errors, we should add one, and show a dialog that says "The package file is invalid" (perhaps with a reason). Aborting a process is a poor user experience.

2020-09-17 20:24 UTC, mcdurdin commented
I just looked at the error report ... this is showing that the *installed* file is damaged, which is concerning. It means that something has gone wrong with the kmp.json data on disk. It'd be nice to know what! For resilience, in this situation, it should show the package in the list with "corrupt" or "damaged" message, rather than aborting (which makes Keyman Configuration unusable).

Keyman for Windows, if it encounters a damaged package in its installed data, shows the package with a suitable message in the list, so the user can attempt to remove it, at least.

2020-09-18 04:17 UTC, mcdurdin approved these changes

2020-09-18 04:21 UTC, darcywong00 commented
Slight tweak so "About" on a damaged keyboard shows the following
![invalid metadata](https://user-images.githubusercontent.com/7358010/93555715-fcd32100-f9a0-11ea-8282-03667b3981bd.png)

2020-09-18 04:42 UTC, merged