fix(android/engine): Remove usage of WRITE_EXTERNAL_STORAGE permission
keymanapp/keyman pull request #4170
Opened 2020-12-17 15:20 UTC by darcywong00

Fixes #4120 and reverts #2946

Our current use of DownloadManager with  [setDestinationUri](https://developer.android.com/reference/android/app/DownloadManager.Request#setDestinationUri(android.net.Uri)) meant:
> Must be a file URI to a path on external storage, and the calling application must have the WRITE_EXTERNAL_STORAGE permission.

This mean on app start, we'd need to request WRITE_EXTERNAL_STORAGE permission, and the dialog would get hidden by the "Get Started" menu.

This PR removes the usage of setDestinationUri, which means we can remove the request for WRITE_EXTERNAL_STORAGE permission.

## Additional changes
* Refactor the conversion of the downloaded file from `content://` and `file://` schemes to `FileUtils.cacheAndGetDownloadInfo()`.
* FileUtils.cacheAndGetDownloadInfo() also copies the downloaded file to local cache so other cloud callbacks can access it.

## User Testing
Scenarios to verify the DownloadManager still works

### Get keyboard update
1. I used a custom build that had an older version of sil_euro_latin.kmp (version 1.8.1).
2. Load this version of Keyman for Android
3. Close the "Get Started" menu and allow the app time to check for keyboard updates
4. When a notification for an update to sil_euro_latin appears, download it
5. The keyboard update will proceed in the background. Eventually the keyboard downloads and updates.

For the rest of these tests, use the CI test build

### Install (keyboard) from keyman.com
1. Load Keyman for Android and close the "Get Started" menu
2. Go to "Settings" --> Install Keyboard or Dictionary --> Install from keyman.com
3. Search for a keyboard and install
4. Verify the keyboard package downloads and can be installed

### Install from local file
1. From Chrome, download another keyboard package and save/copy it to the SD card/Downloads folder.
2. Load Keyman for Android and close the "Get Started" menu
3. Go to "Settings" --> Install keyboard or Dictionary --> Install from local file
4. Browse to SD card / Downloads  to the saved kmp file and select it
5. Verify Keyman for Android shows a system dialog requesting access to the SD card
6. Accept the permission and continue with the keyboard package installation

2020-12-17 21:21 UTC, MattGyverLee commented
This is great. I was wondering why I was alerted about new permissions when I moved to embedding KMEA13.

2020-12-18 02:33 UTC, darcywong00 commented
>  I was wondering why I was alerted about new permissions when I moved to embedding KMEA13.

The `WRITE_EXTERNAL_STORAGE` permission was being used in KMEA 14 alpha. KMEA 13 is only using `READ_EXTERNAL_STORAGE` (and probably quietly throwing storage exceptions).

2020-12-18 03:20 UTC, mcdurdin commented
Well done! I am happy to see this PR. I will review when back at my desk.

2020-12-19 19:00 UTC, mcdurdin requested changes
This looks really good. I like the refactor. I've got some minor change requests, and I realise some of them come from the existing code that was simply shifted around, but I think that it's important to leave the code in a better state than it was anyway ;-)

2021-01-06 07:34 UTC, darcywong00 commented on android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/DownloadFileUtils.java
> +      Toast.makeText(context, message, Toast.LENGTH_LONG).show();
Done. I had the two callers (`MainActivity.useLocalKMP()` and `CloudApiTypes.cacheAndOpenDestinationFile()`) check and handle the Toast notifications.

2021-01-06 07:35 UTC, darcywong00 commented on android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/DownloadFileUtils.java
> +    private final String filename;    // Internal filename (may be a document number)
That was a stale comment. I've updated it

2021-01-06 07:35 UTC, darcywong00 commented on android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/DownloadFileUtils.java
> +    return info;
The caller in MainActivity will return if this is invalid

2021-01-06 07:36 UTC, darcywong00 commented on android/KMEA/app/src/main/java/com/tavultesoft/kmea/cloud/CloudApiTypes.java
> +      DownloadFileUtils.Info info = DownloadFileUtils.cacheDownloadFile(context, data);
Good idea. I've renamed to `cacheAndOpenDestinationFile()`

2021-01-06 07:37 UTC, darcywong00 commented on android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/MainActivity.java
> +        "No keyboards/dictionaries were installed.";
Added to localizable string R.string.not_valid_package_file

2021-01-06 07:38 UTC, darcywong00 commented on android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/DownloadFileUtils.java
> +        ".\nCheck Android Settings --> Apps --> Keyman to grant storage permissions";
The callers now check if filename is null and give a Toast and return.

2021-01-12 21:46 UTC, mcdurdin approved these changes
LGTM.

2021-01-12 23:54 UTC, merged

2021-01-13 18:00 UTC, keyman-server commented
Changes in this pull request will be available for download in [Keyman version 14.0.220-beta](https://keyman.com/downloads/releases/beta/14.0.220)

2021-01-19 08:58 UTC, MakaraSok commented
@darcywong00 Tested against this build (v14.0.220-beta) on emulator Mixel 2 API 29.

**One issue is found**

At this step of "Install from local file":

> 5. Verify Keyman for Android shows a system dialog requesting access to the SD card

No dialog requesting access to the SD card was shown to me. The keyboard got installed without any blockage.

2021-01-19 09:03 UTC, darcywong00 commented
> No dialog requesting access to the SD card was shown to me. The keyboard got installed without any blockage.

Ah, well I'm not concerned if some Android devices don't ask for the permission. I know older devices don't bother asking.

2021-01-20 02:26 UTC, MakaraSok commented
Fair enough then :)

2021-01-25 18:01 UTC, keyman-server commented
Changes in this pull request will be available for download in [Keyman version 15.0.9-alpha](https://keyman.com/downloads/releases/alpha/15.0.9)