fix(android/engine): Disable Sentry on tests; Check MapCompat for null
keymanapp/keyman pull request #4664
Opened 2021-03-15 02:30 UTC by darcywong00

Fixes #4269 

* Disable Sentry on unit tests
* Add a null check in MapCompat

The Sentry log was old, so I don't have insight on how MapCompat was null. But this null-check should prevent the app from crashing and will give us more info in the log.

2021-03-15 02:43 UTC, mcdurdin commented
> * Disable Sentry on unit tests

Why disable Sentry on unit tests? Doesn't it give us more detail on call stacks, etc, if we get an error?

2021-03-15 02:50 UTC, mcdurdin requested changes

2021-03-15 02:50 UTC, mcdurdin commented on android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/MapCompat.java
> +    if (map == null) {
I'd prefer this to still throw on `null`. It's invalid input.

If we want to do anything about that, the parent function `com.tavultesoft.kmapro.KeyboardSettingsActivity$2.onItemClick` already has a test for `hashMap == null` and logs that. Just return from that test after L152:

https://github.com/keymanapp/keyman/blob/493bb945b61f0ed0a625a45dd4e8041dcc7e047c/android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/KeyboardSettingsActivity.java#L150-L153

2021-03-15 02:55 UTC, darcywong00 commented
> Why disable Sentry on unit tests? Doesn't it give us more detail on call stacks, etc, if we get an error?

Ah, mis-remembered the details on #4581 disabling Sentry for dev environments (I was thinking when running tests).

I just wasn't sure we wanted to send Sentry errors with every build (tests get run every time)

2021-03-15 03:01 UTC, mcdurdin commented
> I just wasn't sure we wanted to send Sentry errors with every build (tests get run every time)

An additional event is no big deal to receive and it really helps if we know exactly which build stops generating the errors too :grin:

2021-03-15 05:22 UTC, mcdurdin approved these changes
LGTM but I don't think we need the additional test in `MapCompat`.

Good spelunking 👍

2021-03-15 05:22 UTC, mcdurdin commented on android/KMEA/app/src/main/java/com/tavultesoft/kmea/util/MapCompat.java
> +    if (map == null) {
We don't actually need this test at all, just let it bork as it was previously!

2021-03-15 06:03 UTC, merged

2021-03-15 18:02 UTC, keyman-server commented
Changes in this pull request will be available for download in [Keyman version 14.0.260-beta](https://keyman.com/downloads/releases/beta/14.0.260)

2021-03-22 18:08 UTC, keyman-server commented
Changes in this pull request will be available for download in [Keyman version 15.0.20-alpha](https://keyman.com/downloads/releases/alpha/15.0.20)