fix(common/core/web): disambiguation of keys sharing same base key ID
keymanapp/keyman pull request #4703
Opened 2021-03-17 04:11 UTC by jahorton

Fixes #4617.

Implements the spec suggested within https://github.com/keymanapp/keyman/issues/4617#issuecomment-799907262, additionally noting a few different _kinds_ of ID needed at various levels of keyboard processing:

- `baseKeyIdentifier`:  this is the key ID as known to the Keyman keyboard language.  No modifiers, no layer information, etc.  _**Just**_ the base key.
- `coreID`: `baseKeyIdentifier` + the _modifier_ layer, if different from the key's _display_ layer.
    - "Modifier layer":  the layer representing a modifier set that would be accessible to the Keyman keyboard language, as set by keyboard developers within the touch-layout designer on a per-key basis as an override.
    - Check against https://github.com/keymanapp/keyman/issues/4617#issuecomment-799907262 for further clarification, explanation, and examples as needed.
- `elementID`: the key's _display_ layer + `coreID`.  This is the identifier used as a web element ID and will be unique among all keys of the loaded keyboard (unless there is an intended, _literal_ duplicate key definition).
    - Caveat:  if two separate keyboards are simultaneously loaded somehow, two keys with the same `elementID` may coexist - one from each keyboard.

Note that this does introduce a breaking change for any developer who may have had code relying on key IDs.  That said, this spec does its best to minimize breaks, preserving the original ID structure for the most common cases.

## User Testing
@MakaraSok 

Please test with the same resources you were using to report the original issue.  The symptoms should be resolved.

From a quick load/test within iOS:

![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-03-17 at 11 09 37](https://user-images.githubusercontent.com/25213402/111413692-51b5e100-8711-11eb-9a9c-4ea17c8918e2.png)

Additionally, please test a keyboard or two with subkeys - even `sil_euro_latin` should suffice here.  There were a few tweaks needed to maintain popup key behavior as a result, so we need to be sure that nothing was broken there.

Some tests with `khmer_angkor` would also be good - it has some subkeys with modifiers that don't match the display layer.  For example, ឆ (base key) has ឈ (subkey, '+shift') and ក (base key) គ (subkey, '+shift').  Everything should "feel normal" with no unexpected changes.

Finally, some tests with `sil_cameroon_qwerty` may be nice.  I've already tested them within Web, but Android-based tests may be wise as well.  The top row of its SHIFT layer has some diacritic keys with modifier sets that don't match the SHIFT layer, thus have new IDs internally.  (There may be more keys, but those were the easiest to find.)   Everything should "feel normal" with no unexpected changes.

I've run most of these tests myself on Web, with some also on emulated Android... but it'd be good to have a second pair of eyes on this.

2021-03-17 04:13 UTC, jahorton commented on web/source/osk/preProcessor.ts
> +        let keySpec = (e['key'] ? e['key'].spec : null) as unknown as keyboards.ActiveKey;
Naturally, as is practically tradition for me, I've identified a piece of technical debt that could use some future resolution.  Definitely not touching this right now.

It'd be a good fit with any major OSK refactors that may occur in the future.

2021-03-17 04:23 UTC, mcdurdin requested changes
I understand the changes I think. I'm not entirely clear on exactly when/where the 3 different identifier types should be used!

Asking for a little more doc on the three new identifiers in `OSKKeySpec`.

2021-03-17 04:23 UTC, mcdurdin commented on web/source/osk/visualKeyboard.ts
> +    elementID?: string;
Can you document what these look like with examples here? That will really help for future maintenance.

Also I am not that comfortable with using `Identifier` vs `ID` here. It feels inconsistent.

2021-03-18 03:29 UTC, mcdurdin approved these changes

2021-03-18 05:04 UTC, MakaraSok commented
Tested with this build (![image](https://user-images.githubusercontent.com/28331388/111574509-36b1a280-87df-11eb-9a41-462305f97a7c.png)). 

Observation: the prediction works as expected only when there is only one character preceded by a regular space to the left of the caret.
- space + consonant + caret:

![Screenshot_1616043513](https://user-images.githubusercontent.com/28331388/111575595-51851680-87e1-11eb-8b19-ab1a4adf050d.png)

- space + consonant + subscript + caret:

![Screenshot_1616043624](https://user-images.githubusercontent.com/28331388/111575697-8db87700-87e1-11eb-8c34-c247ecd99d50.png)

The EuroLatin (SIL) keyboard with the prediction does work as expected when though there are multiple consonants/vowels to the left of the caret:
![Screenshot_1616043813](https://user-images.githubusercontent.com/28331388/111575913-fbfd3980-87e1-11eb-90c4-c6f30e349765.png)

2021-03-18 05:30 UTC, jahorton commented
> Tested with this build (![image](https://user-images.githubusercontent.com/28331388/111574509-36b1a280-87df-11eb-9a41-462305f97a7c.png)).
>
>     * space + consonant + subscript + caret: 
> 
> ![Screenshot_1616043624](https://user-images.githubusercontent.com/28331388/111575697-8db87700-87e1-11eb-8c34-c247ecd99d50.png)

This is due to this part of your model spec and the fact that you're using Khmer script:

```
        wordBreaker: wordBreakers['default'],
```

The Unicode defaults for Khmer script don't wordbreak as you'd expect, even when manually inserting spaces.  It'll need a custom wordbreaker spec to avoid this, which is separate from this issue.

2021-03-18 05:50 UTC, merged

2021-03-18 18:01 UTC, keyman-server commented
Changes in this pull request will be available for download in [Keyman version 14.0.265-beta](https://keyman.com/downloads/releases/beta/14.0.265)

2021-03-22 18:04 UTC, keyman-server commented
Changes in this pull request will be available for download in [Keyman version 15.0.20-alpha](https://keyman.com/downloads/releases/alpha/15.0.20)