docs(windows): Initial commit - README.md
keymanapp/keyman pull request #5119
Opened 2021-05-20 03:56 UTC by rc-swag

Fixes #5118

2021-05-24 10:37 UTC, mcdurdin requested changes
A few suggestions...

2021-05-24 10:37 UTC, mcdurdin commented on windows/src/desktop/README.md
> +Formerly called "Keyman Desktop" now called "Keyman" to harmonyze with other OSes
```suggestion
Formerly called "Keyman Desktop", now called "Keyman" to harmonize with other platforms.
```

2021-05-24 10:37 UTC, mcdurdin commented on windows/src/desktop/README.md
> +# Keyman, for Windows
```suggestion
# Keyman for Windows
```

2021-05-24 10:37 UTC, mcdurdin commented on windows/src/desktop/README.md
> +Contains all the help mark down documents for Keyman. It can build both microsft compiled help chm or HTML format.
```suggestion
Contains all the help documents in Markdown format for Keyman for Windows. It can build both compiled help chm or HTML format.
```

2021-05-24 10:37 UTC, mcdurdin commented on windows/src/desktop/README.md
> +Builds a executable to install the help system - insthelp.exe.
```suggestion
Builds a helper executable to do various installation tasks - insthelp.exe.
```

2021-05-24 10:37 UTC, mcdurdin commented on windows/src/desktop/README.md
> +This creates a web browser to test keyboard designs - kmbrowserhost.exe is the chromium embedded framework (CEF) host process executable. CEF uses a multi-process model and subprocesses are hosted in
```suggestion
kmbrowserhost.exe is the chromium embedded framework (CEF) host process executable. CEF uses a multi-process model and subprocesses are hosted in kmbrowserhost.exe.
```

2021-05-24 10:37 UTC, mcdurdin commented on windows/src/desktop/README.md
> +Used for keyman configuration. Configuration can be imported from a json file or exported to a json file. Individual settings can be set.
```suggestion
Used for configuration of advanced Keyman settings. Configuration can be imported from a json file or exported to a json file. Individual settings can be set.
```

2021-05-24 10:37 UTC, mcdurdin commented on windows/src/desktop/README.md
> +TODO
```suggestion
User interface strings in various languages
```

2021-05-24 10:37 UTC, mcdurdin commented on windows/src/desktop/README.md
> +Installation program for installing and initial setup of Keyman.
```suggestion
Installation program for installing and initial setup of Keyman. A wrapper for keymandesktop.msi that also automates keyboard downloads and update downloads.
```

2021-05-24 10:37 UTC, mcdurdin commented on windows/src/developer/README.md
> +This is the main source code for the keyboard complier it is packaged as dynamic linked library. The consumers will call 'CompileKeyboardFile'
```suggestion
This is the main source code for the keyboard compiler, packaged as dynamic linked library. The consumers will call 'CompileKeyboardFile'
```

2021-05-24 10:37 UTC, mcdurdin commented on windows/src/developer/README.md
> +The main command line compiler for a keyboard. It compiles keyboards in either kmn or .kps format.
```suggestion
The main command line compiler for a keyboard. It compiles keyboards (.kmn), packages (.kps), and projects (.kpj).
```

2021-05-24 10:37 UTC, mcdurdin commented on windows/src/engine/README.md
> +There are a number of build artifacts that make up the keyman engine. This is a brief description of each artifacts purpose.
```suggestion
There are a number of build artifacts that make up the Keyman Engine. This is a brief description of each artifact's purpose.
```

2021-05-24 10:37 UTC, mcdurdin commented on windows/src/engine/README.md
> +This is the COM API dynamic linked library that will be used by keyman.exe.  The *.dbg is debug build.
```suggestion
This is the public COM API library, used by keyman.exe, kmshell.exe, and various other Keyman and 3rd party programs.
```

 *.dbg are debug symbols (also .pdb are debug symbols)...

2021-05-24 10:37 UTC, mcdurdin commented on windows/src/engine/README.md
> +
```suggestion
```

The .pdb is the debug symbol file only...

2021-05-24 10:37 UTC, mcdurdin commented on windows/src/engine/README.md
> +## kmtip - kmtip.dll | kmtip64.dll [ kmtip.pdb | kmtip64.pdb ]
```suggestion
## kmtip - kmtip.dll | kmtip64.dll
```

2021-05-24 10:37 UTC, mcdurdin commented on windows/src/engine/README.md
> +## kmcomapi - kmcomapi.dll | kmcomapi.x64.dll [ kmcomapi.dbg ]
```suggestion
## kmcomapi - kmcomapi.dll | kmcomapi.x64.dll
```

2021-05-24 22:11 UTC, mcdurdin approved these changes

2021-05-25 06:45 UTC, merged

2021-05-26 18:02 UTC, keyman-server commented
Changes in this pull request will be available for download in [Keyman version 15.0.54-alpha](https://keyman.com/downloads/releases/alpha/15.0.54)

2021-05-28 18:02 UTC, keyman-server commented
Changes in this pull request will be available for download in [Keyman version 15.0.58-alpha](https://keyman.com/downloads/releases/alpha/15.0.58)