fix(common/core/desktop): Fix failing tests on armhf
keymanapp/keyman pull request #5169
Opened 2021-05-27 15:30 UTC by ermshiperete

This change fixes the FixupKeyboard method. In the .kmx files on disk array pointers for an empty array point to the end of the file
(one byte after the end of the data structure). When we expand the pointers in FixupKeyboard this leads to `cgp->dpKeyArray` to point to an unallocated memory location - this shouldn't matter since we don't try to read or write at this location if the Key array is empty, but armhf still seems to raise a SIGBUS, probably because we cast the value to a `LPKEY`. This change sets `cgp->dpKeyArray` to `NULL` if we have an empty key array, similar to what's done for strings. (Fixes #5072)

Also:
- small refactoring in FixupKeyboard
- exclude s390x from package builds until we support big endian (#5111)

2021-05-27 16:44 UTC, ermshiperete commented
Should be :cherries: to `stable-14.0`

2021-05-28 02:56 UTC, mcdurdin commented
I will try and review today -- am going to also consider if we need to map these changes to the win32 codebase.

2021-05-31 01:01 UTC, mcdurdin requested changes
Changes suggested are available in #5197.

2021-05-31 09:43 UTC, mcdurdin approved these changes

2021-05-31 12:58 UTC, merged