feat(android/app): Add menu to adjust keyboard height
keymanapp/keyman pull request #5606
Opened 2021-08-19 07:30 UTC by darcywong00

Addresses #3225 for Android

This adds a new "Settings" menu to adjust the keyboard height. The new menu allows the user to adjust the keyboard height for the current orientation (portrait vs landscape). These adjusted heights are saved as a SharedPreference.
The "RESET TO DEFAULTS" button clears out the saved heights so the default layout dimensions are used.

* Also adds a new API call `KMManager.setKeyboardHeight()` so the adjusted height gets passed to KeymanWeb (`setOskHeight`). The Javascript call already exists in keyboard.html, but they currently were called from `KMKeyboard.onResume()` and `KMKeyboard.onConfigurationChanged()`

TODO for separate PR - Use a static KeymanWeb OSK image for the new menu

### Screenshots

"Settings" menu
![settings](https://user-images.githubusercontent.com/7358010/130026137-0f294bb7-0f48-4ec5-92ae-2bd73f6c2634.png)

"Adjust Keyboard Height" with the default keyboard height
![adjust default](https://user-images.githubusercontent.com/7358010/130026193-62768c9c-014e-41b0-8b8d-45ab5bf3ad59.png)

"Adjust Keyboard Height" with a bigger keyboard height
![adjust](https://user-images.githubusercontent.com/7358010/130026454-fc40aa23-2283-4eda-87b5-8ac822da5ea7.png)

"Updated keyboard OSK"
![adjusted osk](https://user-images.githubusercontent.com/7358010/130026500-91a635a4-c3c3-4569-916e-ae5a6e07943c.png)

2021-08-20 00:53 UTC, mcdurdin commented
Instead of the Keyman logo as the image, could you put a blank 4-row keyboard in -- one without letters on the keys that is representative of any keyboard, and stretch it vertically?

2021-08-20 01:01 UTC, mcdurdin requested changes
I have not yet tested this on a device, but conceptually it's looking good.

Can we move `Enable Keyman` and `Set Keyman as default keyboard` above `Adjust keyboard height` and `Spacebar caption`? We are starting to get option proliferation!

2021-08-20 02:41 UTC, MakaraSok commented
Please notify me once this PR is ready for testing. It seems like there are still things to be done there per Marc's comment.

2021-08-20 02:59 UTC, darcywong00 commented on android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/AdjustKeyboardHeightActivity.java
> +    }
![updated settings](https://user-images.githubusercontent.com/7358010/130172406-d8fca085-191a-4490-b760-bccf576c2299.png)

2021-08-20 03:02 UTC, darcywong00 commented on android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/AdjustKeyboardHeightActivity.java
> +            currentHeight -= y;
given a `defaultHeight` from the layout.xml files I'll gate `currentHeight` so
`defaultHeight / 2` <= `currentHeight` <= `2 * defaultHeight`

2021-08-20 03:03 UTC, darcywong00 commented
> Instead of the Keyman logo as the image, could you put a blank 4-row keyboard in -- one without letters on the keys that is representative of any keyboard, and stretch it vertically?

Here's an updated screenshot with the stretched blank OSK. I'll need to generate an image to use on tablets...

![adjusted blank osk](https://user-images.githubusercontent.com/7358010/130172755-e91d5430-9a5d-464e-ab2b-a98672f89b63.png)

2021-08-20 04:00 UTC, mcdurdin commented on android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/AdjustKeyboardHeightActivity.java
> +    }
This LGTM

2021-08-20 04:00 UTC, mcdurdin commented
Stretched keyboard looks good

2021-08-20 04:01 UTC, mcdurdin approved these changes
LGTM. Ready for testing!

2021-08-20 08:18 UTC, MakaraSok commented
## User Testing Results
| Notes |
| --- |
| Checked, **PASSED** -- works as expected/indicated; otherwise, **FAILED**. |
| Any noticeable behavior would be included as a comment underneath the case in question |
| This test doesn't touch on whether or not each key works as expected, but solely focus on the height adjustments. |

### Setup
* - [x] Load the test build
* - [x] From the "Get Started" menu, enable Keyman as a system-wide keyboard and set Keyman as a default system keyboard.
* Note on the menu for adjusting keyboard height, given a default height (from the layout dimens.xml files, the range of values the keyboard height can be adjusted is:
`default height / 2` <= `adjusted height` <= `2 * default height`

### Adjust Keyboard Height (portrait orientation)
* - [x] Have the device in portrait orientation
* - [x] Go to "Settings" --> "Adjust keyboard height"
* - [x] Note the current keyboard height (default value)
* - [x] On the menu, drag the keyboard to either increase or decrease the keyboard height, and then release your finger
* - [x] Verify the red keyboard height adjusts accordingly
* - [x] Hit the back button until you're back in the Keyman app text area
* - [x] Verify the in-app keyboard height is adjusted per the menu
> _It would be worth noting that the height would exclude the suggestion banner. The banner would be shown right above the resized layout height._
* - [x] On the device, open a separate app (like Chrome)
* - [x] Select an input field and display the Keyman keyboard
* - [x] Verify the system keyboard height is also adjusted per the menu
* - [x] In the Keyman app, go back to the "Adjust keyboard height" menu
* - [x] Press the "RESET TO DEFAULTS" button
* - [x] Verify the red keyboard height adjusts back to the default height
* - [x] Hit the back button until you're back in the Keyman app text area
* - [x] Verify the in-app keyboard height is adjusted per the menu

---

### Adjust Keyboard Height (landscape orientation)
* - [x] Have the device in landscape orientation
* - [x] Go to "Settings" --> "Adjust keyboard height"
* - [x] Note the current keyboard height (default value)
* - [x] On the menu, drag the keyboard to either increase or decrease the keyboard height, and then release your finger
* - [x] Verify the red keyboard height adjusts accordingly
* - [x] Hit the back button until you're back in the Keyman app text area
* - [x] Verify the in-app keyboard height is adjusted per the menu
* - [x] On the device, open a separate app (like Chrome)
* - [x] Select an input field and display the Keyman keyboard
* - [x] Verify the system keyboard height is also adjusted per the menu
* - [x] In the Keyman app, go back to the "Adjust keyboard height" menu
* - [x] Press the "RESET TO DEFAULTS" button
* - [ ] Verify the red keyboard height adjusts back to the default height
* - [ ] Hit the back button until you're back in the Keyman app text area
* - [ ] Verify the in-app keyboard height is adjusted per the menu

> _A general note on portrait/landscape mode, the setting menu shows a stretched keyboard layout where the functions keys look a little ugly. _
>
> _portrait:_ 
> <img width="70" alt="image" src="https://user-images.githubusercontent.com/28331388/130202592-dac268ab-ca7a-45cf-aca2-5517e6d1cca6.png">
>
> _landscape:_ 
> <img width="139" alt="image" src="https://user-images.githubusercontent.com/28331388/130202363-5399e4f9-d0cf-45aa-b534-74941b8786a3.png">

2021-08-21 04:09 UTC, merged

2021-08-21 18:00 UTC, keyman-server commented
Changes in this pull request will be available for download in [Keyman version 15.0.99-alpha](https://keyman.com/downloads/releases/alpha/15.0.99)