fix(web): Fix layers for embedded longpress keys
keymanapp/keyman pull request #5651
Opened 2021-08-27 08:11 UTC by darcywong00

Follow-on to #5351 and fixes #5610

Some longpress keys on the shift layer weren't working on Keyman for Android (e.g. sil_madi).
This fixes how the "functional" layer and "display" layers are determined in kmwembedded.ts.

This fills out `kLayer` and `kbdLayer` so it matches what KeymanWeb on desktop uses
![longpress a](https://user-images.githubusercontent.com/7358010/131092540-aaca2ef6-e2d2-48e6-98b8-8310d6111ee3.png)

The keyboards seem to work in 15.0 (`master`) so maybe don't need to 🍒 pick?

## User Testing
<details><summary>Setup</summary>
1.  Install the test build
2.  Install sil_madi and sil_cameroon_qwerty keyboards
</details>

* **TEST_MADI:** Longpress on shift layer
1. Change the keyboard to sil_madi
2. On the default layer, longpress on a vowel and select it
3. Verify the correct character is output
4. Press <kbd>Shift</kbd> to switch to the "Shift" layer
5. Longpress on the <kbd>A</kbd> and select one of the caps longpresses.
6. Verify the correct character is output

* **TEST_NEXT_LAYER:** Test application of nextlayer
<detail>These steps are based on  #5351</detail>
1. Change the keyboard to sil_cameroon_qwerty
2. Press <kbd>Shift</kbd> to switch to the "Shift" layer
3. Longpress on the <kbd>W</kbd> or <kbd>E</kbd> keys and select one of the caps longpresses
4. Verify the correct character is output
5. Verify the keyboard switches to the to the default layer
6. Press <kbd>Shift</kbd> to switch to the "Shift" layer
7. Press the spacebar
8. Verify the layer remains on "Shift"
9. For each of the following:
    * switch to the symbolic layer
    * longpress on the base key and select any of the longpress keys
    * verify the correct character is output
    * verify the keyboard **switches** to the default layer
    **Base Key**
    <kbd><<</kbd> 
    <kbd>>></kbd> 
    <kbd>'</kbd> (single quote)
    <kbd>"</kbd> (double quote)
10. For each of the following:
    * switch to the symbolic layer
    * longpress on the base key and select any of the longpress keys
    * verify the correct character is output
    * verify the keyboard **remains** on the symbolic layer
    **Base Key**
    <kbd>(</kbd> 
    <kbd>)</kbd> 
    <kbd>?</kbd> (Note, the basekey <kbd>?</kbd> will switch to the default layer
    <kbd>!</kbd> (Note, the basekey <kbd>!</kbd> will switch to the default layer

As only subkeys are affected, testing with other keyboards that utilize subkeys isn't a bad idea. Try with sil_bunong since that was also reported in the issue

2021-08-30 01:19 UTC, jahorton requested changes
Mostly fine, but there's one very important detail that I believe is off.

If things break with the suggestion in place, I believe that's indicative of further problems that may need investigation.

2021-08-30 01:19 UTC, jahorton commented on web/source/kmwembedded.ts
> +      let layer = 'default';
```suggestion
      let layer = displayLayer;
```

2021-08-30 01:25 UTC, jahorton commented
Oh!  Also, some other unit testing ideas - use `sil_cameroon_qwerty`.

I strongly recommend revisiting the tests for that keyboard specified under #5387.  (Alas, that _is_ before we started using the new test-spec format.)  Note the mentioned symbolic layer keys.

While I can't point to a specific example right away without analyzing that keyboard more thoroughly, there is likely a rule in there somewhere that could be affected and that would be wise to test.

2021-08-30 01:31 UTC, jahorton commented on web/source/kmwembedded.ts
> +      let layer = 'default';
Relevant code for the non-embedded representation:

https://github.com/keymanapp/keyman/blob/7db9477f85c8dee3585477e2ecf4e68c5028a4fd/web/source/osk/browser/subkeyPopup.ts#L93-L102

`vkbd.layerId` matches `displayLayer` in purpose.

2021-08-30 09:29 UTC, MakaraSok commented
- **TEST_MADI: PASSED** _The long press keys on both default and shift layers output the expected character without any issue._
- **TEST_NEXT_LAYER: PASSED** _Long press keys on both default and shift layers of `sil_madi`, `sil_cameroon_qwerty`, `khmer_angkor` and `sil_bunong` do output the expected characters._

2021-08-31 01:12 UTC, jahorton approved these changes

2021-08-31 01:23 UTC, darcywong00 commented
> The keyboards seem to work in 15.0 (master) so maybe don't need to 🍒 pick

@jahorton - Last question. Is the OSK refactoring in 15.0 why the keyboards work?

2021-08-31 03:38 UTC, merged

2021-09-17 01:53 UTC, keyman-server commented
Changes in this pull request will be available for download in [Keyman version 14.0.281](https://keyman.com/downloads/releases/stable/14.0.281)