chore(windows): move common components to common
keymanapp/keyman pull request #6804
Opened 2022-06-19 20:33 UTC by mcdurdin

@keymanapp-test-bot skip

This PR's goal is to move the following files in windows/src/global/delphi/comp to common:

* ExtShiftState.pas (to common/windows/delphi/general)
* FixedTrackbar.pas
* keybtn.pas
* OnScreenKeyboard.pas
* PaintPanel.pas

All other files moved are dependencies of these files, into common/windows/delphi subfolders; remaining files in windows/src/global/delphi/general, windows/src/global/delphi/vcl will be moved in upcoming PRs.

Also:
* Added a common_components package for the moved components and build infrastructure for it.
* Updated all project references to moved files.
* Fixed up the build for keymanversion_build.in (global_versions target in Makefiles)

2022-06-23 15:57 UTC, ermshiperete requested changes

2022-06-23 15:57 UTC, ermshiperete commented on common/windows/delphi/ext/sentry/test/SentryClientVclTest.dpr
> +  KeymanVersion in '..\..\..\..\..\common\windows\delphi\general\KeymanVersion.pas',
I don't think `common/common/windows` is correct. Strange that it still compiles...

I think the correct path is `..\..\..\..\..\..\common\windows\delphi\general\KeymanVersion.pas` or `..\..\..\..\..\windows\delphi\general\KeymanVersion.pas` which can be shortened to `..\..\..\general\KeymanVersion.pas`

```suggestion
  KeymanVersion in '..\..\..\general\KeymanVersion.pas',
```

2022-06-23 15:57 UTC, ermshiperete commented on common/windows/delphi/ext/sentry/test/SentryClientVclTest.dpr
> +  RegistryKeys in '..\..\..\..\..\common\windows\delphi\general\RegistryKeys.pas',
```suggestion
  RegistryKeys in '..\..\..\general\RegistryKeys.pas',
```

2022-06-23 15:57 UTC, ermshiperete commented on common/windows/delphi/ext/sentry/test/SentryClientVclTest.dpr
> +  ErrorControlledRegistry in '..\..\..\..\..\common\windows\delphi\vcl\ErrorControlledRegistry.pas',
```suggestion
  ErrorControlledRegistry in '..\..\..\vcl\ErrorControlledRegistry.pas',
```

2022-06-23 15:57 UTC, ermshiperete commented on common/windows/delphi/ext/sentry/test/SentryClientVclTest.dpr
> +  Unicode in '..\..\..\..\..\common\windows\delphi\general\Unicode.pas';
```suggestion
  Unicode in '..\..\..\general\Unicode.pas';
```

2022-06-23 15:57 UTC, ermshiperete commented on common/windows/delphi/ext/sentry/test/SentryClientVclTest.dproj
> +        <DCCReference Include="..\..\..\..\..\common\windows\delphi\general\KeymanVersion.pas"/>
```suggestion
        <DCCReference Include="..\..\..\general\KeymanVersion.pas"/>
```

2022-06-23 15:57 UTC, ermshiperete commented on common/windows/delphi/ext/sentry/test/SentryClientVclTest.dproj
> +        <DCCReference Include="..\..\..\..\..\common\windows\delphi\general\RegistryKeys.pas"/>
```suggestion
        <DCCReference Include="..\..\..\general\RegistryKeys.pas"/>
```

2022-06-23 15:57 UTC, ermshiperete commented on windows/src/test/manual-tests/test_iconsave/test_iconsave.dpr
> +  Unicode in '..\..\..\..\common\windows\delphi\general\Unicode.pas',
```suggestion
  Unicode in '..\..\..\..\..\common\windows\delphi\general\Unicode.pas',
```

2022-06-23 15:57 UTC, ermshiperete commented on windows/src/test/manual-tests/test_iconsave/test_iconsave.dpr
> +  KeymanVersion in '..\..\..\..\common\windows\delphi\general\KeymanVersion.pas',
```suggestion
  KeymanVersion in '..\..\..\..\..\common\windows\delphi\general\KeymanVersion.pas',
```

2022-06-23 15:57 UTC, ermshiperete commented on windows/src/test/manual-tests/test_iconsave/test_iconsave.dproj
> +			<DCCReference Include="..\..\..\..\common\windows\delphi\general\Unicode.pas"/>
```suggestion
			<DCCReference Include="..\..\..\..\..\common\windows\delphi\general\Unicode.pas"/>
```

2022-06-24 04:22 UTC, mcdurdin commented
Many of the manual tests will fail to build as they are very, very old. We could go and clean them up but it is a low-value task. We could even go and delete nearly all of them. But I don't want to do that in this PR chain.

I've fixed a couple which were more recent. The others, I propose to leave and not fix until we actually need them.

2022-06-24 19:31 UTC, merged