change(web): rotation polish - OSK reload no longer needed
keymanapp/keyman pull request #7188
Opened 2022-09-02 05:36 UTC by darcywong00

:cherries: pick of #6787 and fixes #7169 to stable-15.0 (16.0 master already contains the fix)

# User Testing

## Test environments

- GROUP_IOS - any iOS device should suffice
- GROUP_ANDROID - any Android device should suffice

## Tests

- **TEST_INAPP_ROTATE_P-TO-L**:

  1. With Keyman not active, load it in a portrait orientation.
  2. Once loaded, rotate the device to a landscape orientation.
      - The test "passes" if the OSK rotates properly.

- **TEST_INAPP_ROTATE_L-TO-P**:

  1. With Keyman not active, load it in a landscape orientation.
  2. Once loaded, rotate the device to a portrait orientation.
      - The test "passes" if the OSK rotates properly.

- **TEST_BROWSER_ROTATE_P-TO-L**:

  1. Before loading the test page, have the device in a portrait orientation.
  2. Load the KeymanWeb testing page "Test unminified Keymanweb".
  3. Select the top text area in order to display the OSK.
  4. Open the language menu, but do not change keyboards.
  5. Once loaded, rotate the device to a landscape orientation.
      - The test "passes" if the OSK rotates properly.
      - The test "fails" if the OSK is not visible after rotation.

- **TEST_BROWSER_ROTATE_L-TO-P**:

  1. Before loading the test page, have the device in a landscape orientation.
  2. Load the KeymanWeb testing page "Test unminified Keymanweb".
  3. Select the top text area in order to display the OSK.
  4. Open the language menu, but do not change keyboards.
  5. Once loaded, rotate the device to a portrait orientation.
      - The test "passes" if the OSK rotates properly.
      - The test "fails" if the OSK is not visible after rotation.

- **TEST_ANDROID_SHIFT_AFTER_GLOBE**: Verifies fix to #7169

  1. Load the PR build of Keyman for Android
  2. In the Keyman app with the default sil_euro_latin keyboard, the keyboard should be at start-of-sentence
  3. Verify the OSK starts in the Shift layer (note, suggestions may appear in lowercase)
  4. Press the globe key, then exit the Keyboard picker menu
  5. Verify the OSK is still in the Shift layer
  6. Press the <kbd>Shift</kbd> button and verify the OSK switches to the default layer

2022-09-06 03:19 UTC, jahorton approved these changes
LGTM.

2022-09-06 03:19 UTC, jahorton commented on web/source/osk/anchoredOskView.ts
> +    public refreshLayout(pending?: boolean): void {
The main difference is that I see we didn't 🍒 the @override annotation; this is reflected by three less added lines in the lines-changed count.

There's also a dropped newline at line 70 compared to the original - that's the one additional line-change difference of note.  The rest seems to match.

2022-09-06 08:46 UTC, bharanidharanj commented
### GROUP_IOS: - any iOS device should suffice

* **TEST_INAPP_ROTATE_P-TO-L (PASSED):** Tested this with the attach PR build (15.0.270-test-7188) in iOS 15.5 / iPhone 13 Pro max simulator and the OSK rotates properly. 
* **TEST_INAPP_ROTATE_L-TO-P (PASSED):** Tested this with the attach PR build (15.0.270-test-7188) in iOS 15.5 / iPhone 13 Pro max simulator and the OSK rotates properly. 
* **TEST_BROWSER_ROTATE_P-TO-L (PASSED):** Tested this with the attach PR build (15.0.270-test-7188) in iOS 15.5 / iPhone 13 Pro max simulator and the OSK rotates properly. 
* **TEST_BROWSER_ROTATE_L-TO-P (FAILED):** Tested this with the attach PR build (15.0.270-test-7188) in iOS 15.5 / iPhone 13 Pro max simulator and the OSK appears partially on the Screen. 
   <img width="300" src="https://user-images.githubusercontent.com/19683143/188589605-74074ea3-bcaa-49f8-95fd-bc36fabec839.png">
* **TEST_ANDROID_SHIFT_AFTER_GLOBE (PASSED):** Tested this with the attach PR build (15.0.270-test-7188) in iOS 15.5 / iPhone 13 Pro max simulator and verified that the OSK switches to the default layer.

2022-09-06 09:26 UTC, bharanidharanj commented
### GROUP_ANDROID: - any Android device should suffice

* **TEST_INAPP_ROTATE_P-TO-L (PASSED):** Tested this with the attached PR build (Keyman 15.0.270-test-7188) in my Android Mobile device Version 11.0 and verified that the OSK rotates properly. 
* **TEST_INAPP_ROTATE_L-TO-P (PASSED):** Tested this with the attached PR build (Keyman 15.0.270-test-7188) in my Android Mobile device Version 11.0 and verified that the OSK rotates properly. 
* **TEST_BROWSER_ROTATE_P-TO-L (PASSED):** Tested this with the attached PR build (Keyman 15.0.270-test-7188) in my Android Mobile device Version 11.0 and verified that the OSK rotates properly. 
* **TEST_BROWSER_ROTATE_L-TO-P (PASSED):** Tested this with the attached PR build (Keyman 15.0.270-test-7188) in my Android Mobile device Version 11.0 and verified that the OSK rotates properly. 
* **TEST_ANDROID_SHIFT_AFTER_GLOBE (PASSED):** Tested this with the attached PR build (Keyman 15.0.270-test-7188) in my Android Mobile device Version 11.0 and verified that the OSK switches to the default layer.

2022-09-18 22:58 UTC, mcdurdin commented
> * **TEST_BROWSER_ROTATE_L-TO-P (FAILED):** Tested this with the attach PR build (15.0.270-test-7188) in iOS 15.5 / iPhone 13 Pro max simulator and the OSK appears partially on the Screen.

@jahorton and @darcywong00 can you review this issue?

2022-09-19 02:19 UTC, jahorton commented
> > * **TEST_BROWSER_ROTATE_L-TO-P (FAILED):** Tested this with the attach PR build (15.0.270-test-7188) in iOS 15.5 / iPhone 13 Pro max simulator and the OSK appears partially on the Screen.
> 
> @jahorton and @darcywong00 can you review this issue?

I am able to reproduce the test failure on my personal iPhone, though not in Chrome emulation.

For comparison, and to ensure that it isn't broken on `master`, I double-checked on the same device using the test build product from #7142, which includes the already-merged 16.0-alpha version of these changes.  (I double-checked _that_ aspect - that the changes are there - as well.)

This test result _does not reproduce_ on 16.0-alpha; somehow, there's... _something_ different that's specific to 15.0-stable.  What "something"?  Good question!  That'll take time to investigate.

2022-09-19 02:42 UTC, jahorton commented
Well, _that's_ probably related:  we should probably cherry-pick the "patch PR" followup as part of this, too.  See #6979.

The original version had similarly-noted test issues, but since it'd already undergone significant review at the time, I made a "patch PR" that could be reviewed separately, in case reviewers didn't like the "patch" changes.

2022-09-19 06:01 UTC, jahorton requested changes
Oh, right.  Noting my prior comment, I'm requesting that the changes from #6979 be included in this 🍒-pick, as that should address the failed unit test.

2022-09-19 07:18 UTC, jahorton approved these changes

2022-09-19 07:22 UTC, darcywong00 commented
With the changes from #6979 now :cherries:-picked, 

@keymanapp-test-bot retest GROUP_IOS TEST_BROWSER_ROTATE_L-TO-P

2022-09-19 13:45 UTC, bharanidharanj commented
### GROUP_IOS: - any iOS device should suffice

* **TEST_BROWSER_ROTATE_L-TO-P (OPEN):** notes

## SUITE_ROTATION: 

### GROUP_IOS_PHONE: - any modern iOS phone should suffice

* **TEST_OSK_PORTRAIT_LOAD (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 16.0 / iPhone 14 Pro max simulator and the OSK rotates properly.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/191028806-ab4b974a-694e-4bc4-93fc-590cefa9ae57.png">


* **TEST_OSK_LANDSCAPE_LOAD (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 16.0 / iPhone 14 Pro max simulator and the OSK rotates properly.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/191028823-0a10e603-2320-41d8-8ea4-55d136312def.png">


* **TEST_BROWSER_ROTATE_P-TO-L (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 16.0 / iPhone 14 Pro max simulator and the OSK rotates properly.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/191028837-fbd17f63-9edb-400e-b4dc-d1c9003b9d99.png">


* **TEST_BROWSER_ROTATE_L-TO-P (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 16.0 / iPhone 14 Pro max simulator and the OSK rotates properly.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/191028853-42f16178-2706-48c3-a897-358c0a032af1.png">

2022-09-19 14:09 UTC, bharanidharanj commented
## SUITE_ROTATION: 

### GROUP_IOS_TABLET: - any modern iOS tablet should suffice

* **TEST_OSK_PORTRAIT_LOAD (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 16.0 / iPad Pro 3 generation simulator and the OSK rotates properly.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/191036461-409f2f39-248c-470d-a0d2-57aeb17086a6.png">


* **TEST_OSK_LANDSCAPE_LOAD (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 16.0 / iPad Pro 3 generation simulator and the OSK rotates properly.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/191036510-95a0e174-1485-4ac6-8eec-fba625d4d723.png">



* **TEST_BROWSER_ROTATE_P-TO-L (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 16.0 / iPad Pro 3 generation simulator and the OSK rotates properly.


   <img width="300" src="https://user-images.githubusercontent.com/19683143/191036535-c8aa7fdb-fa53-47ab-8a2c-274ad5493f0d.png">



* **TEST_BROWSER_ROTATE_L-TO-P (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 16.0 / iPad Pro 3 generation simulator and the OSK rotates properly.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/191036585-01fcd08d-b520-481f-b5eb-aa0e8bda7a04.png">

2022-09-19 14:31 UTC, bharanidharanj commented
### GROUP_IOS: - any iOS device should suffice

* **TEST_BROWSER_ROTATE_L-TO-P (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 15.0 / iPhone 13 Pro Simulator and the OSK rotates properly.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/191042126-b24004de-dd80-4509-839b-7d68d88f0d58.png">

2022-09-20 07:48 UTC, bharanidharanj commented
## SUITE_ROTATION: 

### GROUP_OLD_IOS: - try to find an iOS 12 or iOS 13 device to test with

* **TEST_OSK_PORTRAIT_LOAD (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 12.4 / iPhone 7 Simulator and verified the appearance of the OSK and it seems to be reasonably positioned and sized. No cropping issues. 


   <img width="300" src="https://user-images.githubusercontent.com/19683143/191189750-34b70760-c369-4a3a-87c2-356eb69ddf61.png">

* **TEST_OSK_LANDSCAPE_LOAD (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 12.4 / iPhone 7 Simulator and verified the appearance of the OSK and it seems to be reasonably positioned and sized. No cropping issues. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/191189768-e832539d-a8a9-43dc-bff2-4e3424e3bae3.png">


* **TEST_BROWSER_ROTATE_P-TO-L (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 12.4 / iPhone 7 Simulator and the OSK rotates properly. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/191189794-d4ddf4c8-7c95-4351-bdad-486f5b5af0ab.png">


* **TEST_BROWSER_ROTATE_L-TO-P (FAILED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 12.4 / iPhone 7 Simulator and I noticed that the OSK flashes on the screen and it does not appear on the View. 

    <img width="300" src="https://user-images.githubusercontent.com/19683143/191198718-4768223a-6ce8-4210-8b64-03edf2a4e493.png">

2022-09-20 08:52 UTC, darcywong00 commented
@bharanidharanj 
TEST_BROWSER_ROTATE_L-TO-P  should have rotated from landscape to portrait orientation, and the screenshot looks like it's still landscape. Are you saying the OSK failed to display in the original landscape orientation?

See the [screenshot](https://user-images.githubusercontent.com/19683143/182170252-9e17fe5d-d8a7-44cf-8e28-17dfc235191b.png) from the original PR

2022-09-20 09:36 UTC, bharanidharanj commented
## SUITE_ROTATION: 

### GROUP_ANDROID_PHONE: - any modern Android phone should suffice

* **TEST_OSK_PORTRAIT_LOAD (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in my Android Mobile device Version 11.0 and verified the appearance of the OSK and it seems to be reasonably positioned and sized. No cropping issues.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/191221217-058d8a59-5754-4c62-832a-0a44450abf6b.jpg">


* **TEST_OSK_LANDSCAPE_LOAD (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in my Android Mobile device Version 11.0 and verified the appearance of the OSK and it seems to be reasonably positioned and sized. No cropping issues.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/191221260-5e110cc6-29eb-45f1-84e3-7bb65728b565.jpg">


* **TEST_BROWSER_ROTATE_P-TO-L (FAILED):** Tested this with the attach PR build (15.0.271-test-7188) in my Android Mobile device Version 11.0 and I noticed that the Inconsistent behavior of the OSK. ie., the OSK sometimes appear on the screen and sometimes it does not appear after rotating it from Portrait to Landscape. Seems to be an issue.

   <img width="500" src="https://user-images.githubusercontent.com/19683143/191221288-6d820125-bd19-4556-975d-32a4707a6603.jpg">

* **TEST_BROWSER_ROTATE_L-TO-P (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in my Android Mobile device Version 11.0 and the OSK rotates properly.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/191221321-b080aa4b-1e7d-4ce7-ac7f-9fe8d8d4822c.jpg">

2022-09-20 13:32 UTC, bharanidharanj commented
## SUITE_ROTATION: 

### GROUP_ANDROID_TABLET: - any modern Android tablet should suffice

* **TEST_OSK_PORTRAIT_LOAD (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in Pixel C API 31 / Android 12.0 and verified the appearance of the OSK and it seems to be reasonably positioned and sized. No cropping issues.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/191270271-d3e8cd6c-8567-4714-a04b-faacddef779e.PNG">


* **TEST_OSK_LANDSCAPE_LOAD (PASSED):**  Tested this with the attach PR build (15.0.271-test-7188) in Pixel C API 31 / Android 12.0 and verified the appearance of the OSK and it seems to be reasonably positioned and sized. No cropping issues.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/191270304-4bb46da6-7dab-444b-98cd-2f6f31245fcb.PNG">

* **TEST_BROWSER_ROTATE_P-TO-L (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in Pixel C API 31 / Android 12.0 and verified the appearance of the OSK and it rotates properly.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/191270333-6733a37d-f559-473d-9fd5-26fbef747dbe.PNG">


* **TEST_BROWSER_ROTATE_L-TO-P (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in Pixel C API 31 / Android 12.0 and verified the appearance of the OSK and it rotates properly.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/191270366-8f245d5b-f4a1-46b8-9545-0c324d447605.PNG">

2022-09-20 14:40 UTC, bharanidharanj commented
### GROUP_ANDROID_7: - run tests against early Android if possible (Android 7.0)

* **TEST_OSK_PORTRAIT_LOAD (PASSED):**  Tested this with the attach PR build (15.0.271-test-7188) in API 24 / Android 7.0 emulator and verified the appearance of the OSK and it seems to be reasonably positioned and sized. No cropping issues.

<img width="300" src="https://user-images.githubusercontent.com/19683143/191285787-21dce220-276a-4088-99a0-652a8de50f36.PNG">


* **TEST_OSK_LANDSCAPE_LOAD (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in API 24 / Android 7.0 emulator and verified the appearance of the OSK and it seems to be reasonably positioned and sized. No cropping issues.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/191285820-36add4f0-cdb8-49da-99bd-8181a3cd9cc4.PNG">


* **TEST_BROWSER_ROTATE_P-TO-L (PASSED):** Tested this with the attach PR build (15.0.271-test-7188) in API 24 / Android 7.0 emulator and verified the appearance of the OSK and it rotates properly.

    <img width="300" src="https://user-images.githubusercontent.com/19683143/191285852-945793a5-444a-417e-9698-326f2e6c24f5.PNG">


* **TEST_BROWSER_ROTATE_L-TO-P (PASSED):**  Tested this with the attach PR build (15.0.271-test-7188) in API 24 / Android 7.0 emulator and verified the appearance of the OSK and it rotates properly.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/191285888-e2d5f197-b54a-4b54-a228-69668bd5b9b4.PNG">

2022-09-20 15:13 UTC, bharanidharanj commented
> @bharanidharanj TEST_BROWSER_ROTATE_L-TO-P should have rotated from landscape to portrait orientation, and the screenshot looks like it's still landscape. Are you saying the OSK failed to display in the original landscape orientation?
> 
> See the [screenshot](https://user-images.githubusercontent.com/19683143/182170252-9e17fe5d-d8a7-44cf-8e28-17dfc235191b.png) from the original PR

@darcywong00 The attached Screenshot looks like it's in Portrait orientation. (from Landscape). Actually, I am confused which emulator you are asking about. 

When I tested 15.0.270-test-7188 in iOS 15.5 / iPhone 13 Pro Max Simulator, after rotating the device from Landscape to Portrait, the OSK appears partially on the Screen. (Please, see my attached Screenshot) [screenshot](https://user-images.githubusercontent.com/19683143/191295429-e9a8bcef-596f-42f7-b2ed-2c192c68b498.png)

When I tested the same (TEST_BROWSER_ROTATE_P-TO-L) in iOS 12.4 / iPhone 7 Simulator, the OSK is failed to display in the original landscape orientation. (Please, see the attached Screenshot) [screenshot](https://user-images.githubusercontent.com/19683143/191295776-2a72f91c-48b3-4b26-bd69-2ff6d6c2878d.png)

Please, let me know if further clarification is needed. Thanks.

2022-09-21 03:06 UTC, darcywong00 commented
@bharanidharanj 
I was asking about your test result from here:

> * **TEST_BROWSER_ROTATE_L-TO-P (FAILED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 12.4 / iPhone 7 Simulator and I noticed that the OSK flashes on the screen and it does not appear on the View. 
>
>    <img width="300" src="https://user-images.githubusercontent.com/19683143/191198718-4768223a-6ce8-4210-8b64-03edf2a4e493.png">

Are you saying the OSK flashed and disappeared **before** rotating from landscape to portrait orientation?

@jahorton - is the browser OSK expected to intermittently disappear?

2022-09-21 06:05 UTC, bharanidharanj commented
> @bharanidharanj I was asking about your test result from here:
> 
> > * **TEST_BROWSER_ROTATE_L-TO-P (FAILED):** Tested this with the attach PR build (15.0.271-test-7188) in iOS 12.4 / iPhone 7 Simulator and I noticed that the OSK flashes on the screen and it does not appear on the View.
> >    <img alt="" width="300" src="https://user-images.githubusercontent.com/19683143/191198718-4768223a-6ce8-4210-8b64-03edf2a4e493.png">
> 
> Are you saying the OSK flashed and disappeared **before** rotating from landscape to portrait orientation?
> 
> @jahorton - is the browser OSK expected to intermittently disappear?

@darcywong00 Yes, That's right.

2022-09-23 06:26 UTC, darcywong00 commented
From Friday standup, @mcdurdin said we'll hold off on this PR till @jahorton can investigate the browser OSK rotation issues.

2022-09-27 05:47 UTC, jahorton commented
> @jahorton - is the browser OSK expected to intermittently disappear?

I'll need to revisit it to be sure, but my memory is that KMW will usually hide the OSK pre-rotation and re-display it afterward.  So, this suggests that the 'redisplay' part isn't happening for whatever reason.

2022-09-27 06:35 UTC, jahorton commented
While certainly not an answer to the lingering issues from user testing mentioned above, there were a few oddities noted here on one of the original PRs: https://github.com/keymanapp/keyman/pull/6979#issuecomment-1203688781

It does make me wonder if there may be a bit more to address there as well.

2022-09-27 06:48 UTC, jahorton commented
Unlike before, I'm having trouble attempting to repro the user test failures.  That's going to make investigation at least a bit tricky.

2022-09-28 03:57 UTC, MakaraSok commented
@keymanapp-test-bot retest SUITE_ROTATION GROUP_OLD_IOS TEST_BROWSER_ROTATE_L-TO-P GROUP_ANDROID_PHONE TEST_BROWSER_ROTATE_P-TO-L

2022-09-28 03:59 UTC, MakaraSok commented
Self assigned to retest and double check the failed cases

2022-09-28 04:51 UTC, MakaraSok commented
# Test Results

## SUITE_ROTATION: 

### GROUP_OLD_IOS: - try to find an iOS 12 or iOS 13 device to test with

* **TEST_BROWSER_ROTATE_L-TO-P (FAILED):** Tested with the [build off of this PR](https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/339125:id/index.html):

  * on iOS 12.4 iPhone Xs Max simulator. There is no way to open the language menu as the globe key is nowhere to be found.

  <img width="500" alt="image" src="https://user-images.githubusercontent.com/28331388/192683244-910cbb16-41b6-40f6-9eab-26734beb8cfe.png">

    Here is how it looks after rotate to portrait:
  <img width="300" alt="image" src="https://user-images.githubusercontent.com/28331388/192685340-b4c7387c-dfaa-44b9-ba57-e1cfd6dc666a.png">

If this is out of the scope of this test case, please ignore the this result.

  * The behavior above doesn't occur in iOS 13.7 simulator though.

  <img width="500" alt="image" src="https://user-images.githubusercontent.com/28331388/192687665-6ba02fd5-0748-4e4b-ac34-631911b02285.png">

  <img width="300" alt="image" src="https://user-images.githubusercontent.com/28331388/192687851-f1abdb04-88ac-470d-a8c1-4cdc927eca3c.png">


### GROUP_ANDROID_PHONE: - any modern Android phone should suffice

* **TEST_BROWSER_ROTATE_P-TO-L (PASSED):** Tested with Android 12 (API 31), the keyboard is shown OK after rotating to landscape.
 
  <img width="500" alt="image" src="https://user-images.githubusercontent.com/28331388/192689993-ddd2c93f-496f-47bb-ad58-d0138ed4ba66.png">

2022-10-04 06:10 UTC, jahorton commented
> # Test Results
> ## SUITE_ROTATION:
> ### GROUP_OLD_IOS: - try to find an iOS 12 or iOS 13 device to test with
> 
>     * **TEST_BROWSER_ROTATE_L-TO-P (FAILED):** Tested with the [build off of this PR](https://build.palaso.org/repository/download/Keymanweb_TestPullRequests/339125:id/index.html):
>       
>       * on iOS 12.4 iPhone Xs Max simulator. There is no way to open the language menu as the globe key is nowhere to be found.
>       
>       <img alt="image" width="500" src="https://user-images.githubusercontent.com/28331388/192683244-910cbb16-41b6-40f6-9eab-26734beb8cfe.png">

I may need to double-check, but I think this is the same Safari issue as noted on one of the other tests previously.  Older iOS devices put the nav bar at the top rather than the bottom, but the in-page side effects were the same.  If the nav bar hadn't appeared, the globe key would likely be in view.

2022-10-04 06:24 UTC, jahorton commented
Come to think on it... if the 'worst' user test failure we're getting is that the OSK isn't showing after a rotation... as long as it shows again when the element is reselected, that doesn't seem too bad of an issue.  Also, even that is only happening intermittently at that, so far as we've seen, right?

2022-10-06 07:00 UTC, bharanidharanj commented
As per Makara's suggestion I have retested this (GROUP_OLD_IOS: - try to find an iOS 12 or iOS 13 device to test with- TEST_BROWSER_ROTATE_L-TO-P )in iOS 12.4 and here is my observation:
1. Tested the Landscape to Portrait mode in iPhone 7 Plus Simulator and I was able to see the OSK on the Screen in the landscape mode. However, the bottom of the OSK has been cropped. 

   <img width="500" src="https://user-images.githubusercontent.com/19683143/194235113-ef83280b-f087-4a37-8c67-fe3f24a8c15d.png">

2. In iPhone X Simulator after clicking the text area, the globe key is not visible on the Screen. 

   <img width="500" src="https://user-images.githubusercontent.com/19683143/194235224-caa60c81-354c-48f9-9543-aea49c90627a.png">

3. In iPhone xs Max Simulator, after scrolling down the page I could able to see the globe key. However, scrolling up the page will hide the globe key on the screen. 



4. Tested the same in iOS 16.0, the OSK is fully visible on the Screen. Seems to be working fine in the latest iOS verion. 

   <img width="500" src="https://user-images.githubusercontent.com/19683143/194235279-d1317646-b8b4-4bf3-8215-6af533a4763d.png">

2022-10-06 07:12 UTC, mcdurdin commented
My feeling on this, is if the issue is less severe than previously, we should merge this. In particular, if this rotation issue only impacts Keyman Web on mobile, and only impacts rotation, and is easily resolved by the user by refocusing the edit control, that's a much smaller user base, with a much less severe impact, so we should merge.

Then we should open a new issue to correct the remaining rotation issues!

2022-10-16 23:58 UTC, merged

2022-10-16 23:58 UTC, mcdurdin commented
One fail on the old version of iOS, modern iOS versions seem to work fine.

2022-10-18 18:31 UTC, keyman-server commented
Changes in this pull request will be available for download in [Keyman version 15.0.271](https://keyman.com/downloads/releases/stable/15.0.271)