fix(android/engine): Refresh OSK after changing spacebar caption
keymanapp/keyman pull request #7348
Opened 2022-09-22 08:43 UTC by darcywong00

Fixes #6603 

I still don't understand the KeymanWeb namespacing, but changing the OSK refresh call
from `keyman.correctOSKTextSize();` 
to `kmw.correctOSKTextSize()` resulted in the spacebar text caption correctly refreshing without needing the globe key to switch keyboard.

Does this impact other `keyman.correctOSKTextSize()` calls?

## User Testing

* **TEST_SPACEBAR_CAPTION_REFRESHES** - Verifies issue #6603 is fixed
1. Load the PR build of Keyman for Android
2. Verify the default OSK spacebar caption shows **Language + Keyboard** (e.g. English - EuroLatin (SIL))
3. Go to Keyman settings --> change Spacebar caption to **Language** --> exit the Settings menu
4. Verify the OSK spacebar caption shows **Language** (e.g. English)
5. Go to Keyman settings --> change Spacebar caption to **Keyboard** --> exit the Settings menu
7. Verify the OSK spacebar caption shows **Keyboard** (e.g. EuroLatin (SIL))
8. Go to Keyman settings --> change Spacebar caption to **Language + Keyboard** --> exit the Settings menu
9. Verify the OSK spacebar caption shows **Language + Keyboard** (e.g. English - EuroLatin (SIL))
10. Go to Keyman settings --> change Spacebar caption to **Blank** --> exit the Settings menu
11. Verify the OSK spacebar caption shows **Blank** (e.g. no caption)

2022-09-22 14:43 UTC, bharanidharanj commented
* **TEST_SPACEBAR_CAPTION_REFRESHES (PASSED):** Tested this in API 26 / Android 8.0 emulator with the attached PR build (16.0.70-alpha-test-7348) and verified that the OSK spacebar caption is working as expected in all the conditions.

2022-09-22 18:49 UTC, mcdurdin requested changes
`window['keyman']` is exactly equivalent to `keyman`. So assigning it to the local variable `kmw` doesn't change the code behaviour in any way. 

As this actually doesn't make any difference to the code execution, if you are seeing different behaviour, there's something else that's doing that.

2022-09-22 23:25 UTC, darcywong00 commented
Hmm,
So on the current 16.0.69 alpha, I'm seeing the spacebar caption correctly refreshes after leaving the Settings menu (without needing to swtch keyboards)...

2022-09-23 02:10 UTC, darcywong00 commented
PR going back to wip for further investigation

2022-09-23 10:09 UTC, bharanidharanj commented
* **TEST_SPACEBAR_CAPTION_ANDROID (PASSED):** Retested this in both Android 8.0 and Android 11 emulators and the space bar captions is working as expected in all settings.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/191938596-d5b843d4-e33c-4549-b0b7-d9cd8b5ca764.PNG">

* **TEST_SPACEBAR_CAPTION_IOS (FAILED):** Retested this in both iPhone 14 Pro (iOS 16.0) and iPad Pro (3 generation) Simulators and it is PASSED in iPhone and FAILED IN iPad .

   <img width="500" src="https://user-images.githubusercontent.com/19683143/191938627-299d0a7b-99b7-4ec1-9dda-a6235b10ecb8.png">

2022-09-26 00:51 UTC, darcywong00 commented
OK, I'm disassociating issue #7228  and will add details on that issue what I *think* needs to be added.

I'll also move the failing iOS test to the issue for when that's ready to test.

2022-09-27 01:36 UTC, jahorton approved these changes

2022-09-29 00:48 UTC, mcdurdin approved these changes

2022-09-29 01:35 UTC, merged