fix(android/engine): Verify keyboard file exists before switching
keymanapp/keyman pull request #7489
Opened 2022-10-19 08:47 UTC by darcywong00

Fixes #7412

This change to Keyman Engine for Android verifies a Javascript keyboard file exists before having KeymanWeb switch to the keyboard.

For my testing, I installed sil_cameroon_qwerty package, then manually deleted the .js file before trying to switch to a second keyboard and verified the Toast notification of the LogError appeared.

@keymanapp-test-bot skip

2022-10-20 02:43 UTC, jahorton commented
> > I... wouldn't say this fixes the issue. It provides us somewhat better data _about_ the issue, though.
> > I'm pretty sure that users would say "it's an issue" if a keyboard appeared to have spontaneously uninstalled itself. If the file goes missing, but the keyboard is still in the language list, that doesn't sound like an intentional uninstallation.
> 
> What do you suggest for resolving the Sentry message?

I'll admit, I'm stumped on how to resolve it overall.

That said, this doesn't _resolve_ it either.  It just "passes the buck" to a different message.

> > Cannot find the Warang Citi keyboard for Ho (Warang Citi) at /data/user/0/com.tavultesoft.kmapro/app_data/packages/warang_citi/warang_citi.js?v=1664969917797.
> 
> I don't see how Keyman Engine gets in that state...

Yeah, like I said, I'm stumped on how to resolve it overall.  If I had a clear answer here, that'd be your resolution.

2022-10-20 20:33 UTC, mcdurdin commented
I concur with @jahorton on this one. My best guess is that I'd be looking at keyboard uninstallation and/or upgrade as a potential culprit here.

2022-10-20 22:55 UTC, mcdurdin requested changes
Let's look at root causes rather than addressing the symptom

2022-10-25 07:54 UTC, darcywong00 commented
I've added Sentry logging for keyboard uninstalls and updates via the cloud

2022-10-25 22:01 UTC, mcdurdin commented
Sadly, I'm not sure this logging will help us -- it does not provide enough detail on what the filesystem and metadata store looks like before + after the uninstalls and updates.

Given we are having trouble with diagnosing this and getting logging together, I wonder if we can try and get a repro on alpha and then go from there?

2022-10-31 01:48 UTC, jahorton commented
If only we had Android unit tests set up like the iOS unit tests defined here: https://github.com/keymanapp/keyman/blob/master/ios/engine/KMEI/KeymanEngineTests/MigrationTests.swift

A setup like that would allow loading from constructed "save states", facilitating before and after comparison of engine / install state, which could be useful for investigation here.  It could even be used to set up states that we've "patched out" to verify that they're properly transitioned.

2022-10-31 02:13 UTC, darcywong00 commented
I'm currently wondering if there's some race condition from this #6438 change (added in 15.0 beta):

https://github.com/keymanapp/keyman/blob/30747f5600ccc0587eaa3f2b5ba300c43c3632d8/android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java#L285

2022-10-31 03:10 UTC, jahorton commented
> I'm currently wondering if there's some race condition from this #6438 change (added in 15.0 beta):
> 
> https://github.com/keymanapp/keyman/blob/30747f5600ccc0587eaa3f2b5ba300c43c3632d8/android/KMAPro/kMAPro/src/main/java/com/tavultesoft/kmapro/PackageActivity.java#L285

I'm not seeing anything immediately on whether or not that function is async.

That said, one interesting tidbit I ran into, courtesy of https://stackoverflow.com/a/14393017 - https://developer.android.com/reference/android/webkit/WebSettings.html#setCacheMode%28int%29.  (The `LOAD_NO_CACHE` part, in particular.)

2022-10-31 08:58 UTC, jahorton commented
It's possible I messed up doing this, but could you do me a favor and try the following?

1. Download/prepare fv_all.kmp

```bash
KEYBOARDS_TARGET=fv_all.kmp KEYBOARDS_TARGET=temp.temp $KEYMAN_ROOT/oem/firstvoices/common/build_keyboards.sh -download-keyboards
```

2. Drag-copy the resulting downloaded `fv_all.kmp` into a live instance of the Keyman app.  (We're doing the package-based ad-hoc path here.)

3. Once the package installer appears, simply click "Install".

4. Check sentry.io and see if you get any error reports like these:
    - `keyman-android`: https://sentry.io/share/issue/80eee015a19047a5b81f56e5cc574248/
    - `keyman-web`: https://sentry.io/share/issue/12c8946f2d7748a1a232681542865716/
        - Note the `.local` on the correponding events:  I triggered these when following the above steps.

2022-10-31 09:02 UTC, jahorton commented
Following up on the previous comment:

>Non-Error promise rejection captured with value: Cannot find the Anicinapemi8in/Anishinàbemiwin keyboard for Algonquin (Latin) at /data/user/0/com.tavultesoft.kmapro.debug/app_data/packages/fv_all/fv_anicinapemi8in.js?v=1667206299329.

But:

![image](https://user-images.githubusercontent.com/25213402/198970740-b98c4bd2-bb6e-4223-afb7-0f4f7a1306f7.png)

(Within an unaltered un-zip of fv_all.kmp.)

2022-10-31 09:13 UTC, jahorton commented
Tried a second time after wiping the emulation instance; the error did not recur this time.  So there may be some sort of race condition... but it _can_ happen via ad-hoc installs, at least.  The linked Sentry reports are proof of that.

2022-10-31 09:23 UTC, jahorton commented
Also, for what it's worth...

The installed keyboards are all registered with lowercased language tags.  I inspected the app's filesystem, `app_userdata/keyboards_list.json` to verify this.  The base `fv_all.kmp` file's `kmp.json` does have mixed-case language tags, thus the app itself is confirmed to apply lowercasing on keyboards coming in via ad-hoc install.

2022-10-31 09:25 UTC, jahorton commented
Oh, and all of the above was done on `master`, not on this branch - just for clarification.

In retrospect, this may not have been the best place to leave these notes, but... at least they're available here.  Not sure where to move 'em at the moment, and it's the end of the workday.  "Somewhere" is at least better than "nowhere", so hopefully all of that proves useful.

2022-10-31 09:43 UTC, jahorton commented
While I remember:  I think the first run started with French Basic as the active keyboard, not SIL EuroLatin.  I know there were at least two keyboards total installed.  This may be relevant to repro attempts - that the prior active keyboard wasn't EuroLatin.

2022-11-01 01:35 UTC, jahorton commented
... yeah, starting to seem like I "lucked out" that one time; I haven't had any successful attempts so far today.

2022-11-01 02:28 UTC, darcywong00 commented
> Probably of note: I was not prompted to select any languages to install.

@jahorton - Since fv_all.kmp contains multiple keyboards to install, we don't use a language picker during the package installation. It just picks the first language in each list. They can always add the desired language in the Settings menu.

2022-11-01 03:04 UTC, darcywong00 commented
One thing I'll note. Keyman for Android starts with the default keyboard:
```json
{
  "packageID": "sil_euro_latin"
  "resourceID": "sil_euro_latin"
}
```

and after installing fv_all.kmp, the packageID in the keyboards_list.json gets updated to:
```json
{
  "packageID": "fv_all"
  "resourceID": "sil_euro_latin"
}
```

The sil_euro_latin folder is still intact though.


This is probably because the Keyboard controller sees a matching keyboardID: sil_eruo_latin and languageID: en
and updates the packageID....


This wouldn't explain other keyboards in the Sentry logs: arabic_izza, sil_cameroon_qwerty, ...

2022-11-02 08:22 UTC, jahorton commented
You know... a _lot_ of this feels kinda similar to issue #6862.  Granted, the errors logged by Sentry are different, but the end-user experience felt very similar.  I don't believe `fv_all.kmp` has a welcome.htm, so that aspect was (naturally) bypassed for the case reported here.

2022-12-12 08:32 UTC, darcywong00 commented
Abandoning this as we chase down the root cause. (A17S13)

2022-12-12 08:32 UTC, closed without merging