fix(windows): kmshell -ikl install language and enable keyboard
keymanapp/keyman pull request #7856
Opened 2022-12-01 02:53 UTC by rc-swag

Fixes #7670 
the `-ikl` sets up the language registration for the keyboard for the user whos shell runs the command. 
This calls a `InstallKeyboardLanguage` when following the command chain all the way through will update the windows registry
 in Line 560 of `Keyman.System.Process.KPInstallKeyboardLanguage` builds a registry key for the `KeyboardID` String Name under `Active Keyboards` and adds the BCP47Tag under the `Languages` path. It does not enable the keyboard. 

As reported in #7670, no KeymanID is written directly under `Active Keyboards` nor the corresponding `Active Keyboards\KeyboardId\keymanid` with the integer value. 

`InstallKeyboardLanguage` will now enable the just-installed active keyboard.  - I am not 100% on this either it would better to have separate `EnableKeyboard` function, however I am not sure where it would sit in the the architecture.

Further discussion it was thought that this would be picked up on the keyboard load.
https://github.com/keymanapp/keyman/blob/58496402bba029acff7e33aa0270f4237a430691/windows/src/global/delphi/general/RegKeyboards.pas#L356-L370

However, the reason the else on line 367 will not be called is because the  ` Active Keyboards\KeyboardId` id exists it doesn't have keymanid. Had the else been for the `if ValueExists(SRegValue_KeymanID) then`  one line 360 then it may have worked. This still doesn't seem like a good method to be catching and enabling a keyboard based on a registry state rather than an explicit request.

2022-12-14 09:39 UTC, ermshiperete approved these changes

2022-12-14 19:51 UTC, mcdurdin requested changes

2022-12-14 19:51 UTC, mcdurdin commented on windows/src/desktop/kmshell/install/UfrmInstallKeyboardLanguage.pas
> +  kbd.Loaded := TRUE;
```suggestion
  kbd.Loaded := True;
```

2022-12-14 19:51 UTC, mcdurdin commented on windows/src/desktop/kmshell/install/UfrmInstallKeyboardLanguage.pas
> +    // TODO: Log error unexpected `KeyboardID` not found
We should do a Sentry report for this.

2022-12-21 20:54 UTC, mcdurdin approved these changes
LGTM, minor suggestion on Sentry report.

2022-12-21 20:54 UTC, mcdurdin commented on windows/src/desktop/kmshell/install/UfrmInstallKeyboardLanguage.pas
> +    TKeymanSentryClient.Client.MessageEvent(Sentry.Client.SENTRY_LEVEL_ERROR, 'KeyboardID: '+KeyboardID+' not found');
A bit more context is probably helpful for error reports -- and including 'InstallKeyboardLanguage' helps for filtering on Sentry.

```suggestion
    TKeymanSentryClient.Client.MessageEvent(Sentry.Client.SENTRY_LEVEL_ERROR, 'InstallKeyboardLanguage: KeyboardID "'+KeyboardID+'" not found, attempting to install for language "'+ISOCode+'".');
```

2022-12-23 10:56 UTC, bharanidharanj commented
# Test Results

* **TEST_CMD_LINE_OPTION (PASSED):** Tested with attached PR build (Keyman 16.0.117-beta-test-7856) in Windows 11 OS (VM) and here is my observation: 1. Able to install Tamil 99 Basic Keyboard by running the command in the Command Prompt in the main user account. 2. Then, switched to Test User account. Run the other command in the Command prompt and I was able to see the Tamil 99 Basic keyboard in the Keyboard Layouts dialog. Seems to be working as expected. 

..from main user account
   <img width="300" src="https://user-images.githubusercontent.com/19683143/209323691-94bde2b5-b235-4153-8386-51fe0d12522a.PNG">

..from test user account

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209323736-c0c6cdd5-26d2-4108-a2c3-f8c4d5a4fc6b.PNG">

   <img width="300" src="https://user-images.githubusercontent.com/19683143/209323806-87e75389-0cbe-4367-b432-7711aaccb5fb.PNG">

2023-01-09 05:40 UTC, merged

2023-01-09 18:01 UTC, keyman-server commented
Changes in this pull request will be available for download in [Keyman version 16.0.130-beta](https://keyman.com/downloads/releases/beta/16.0.130)