fix(core): ldml: add asserts to C++ 🙀
keymanapp/keyman pull request #7992
Opened 2023-01-06 22:55 UTC by srl295

- found a logic bug in kmx_plus.cpp

Fixes #7984

2023-01-06 22:56 UTC, srl295 commented on core/src/kmx/kmx_plus.cpp
> +  const uint8_t *rawdata = reinterpret_cast<const uint8_t *>(newLayr);
Woops! This was the error.

2023-01-06 22:57 UTC, srl295 commented
not sure about 2 copies of the logic

```c
assert (a <= b);
if(a > b) {
   return nullptr;
}
```

2023-01-06 23:59 UTC, mcdurdin commented
> not sure about 2 copies of the logic

Agreed, this turns into a classic copypasta problem. Simple always-false assert is probably safer. (I wish we could do messages in C asserts!)

```c
  if(a > b) {
    assert(false);  // throw in debug mode
    return nullptr;
  }
```

2023-01-07 00:09 UTC, mcdurdin requested changes
I'm fiddling here...

One could also define an `assert_false_and_return(retval, logmessage, ...)` macro which would bundle that DebugLog(), assert(), return pattern. (May need two versions, one which does a plain `return;`.) I think this could be a good strategy, and enforce a consistent pattern of use.

In lieu of that, I went through and moved the assertion in each case _after_ the `DebugLog` so that the last debug log message relates directly to the assertion.

I'm not 100% _sure_ that all the assertions here are appropriate -- assertions shouldn't typically be used for input data validation, but for program logic validation, and some of these assertions are being thrown for invalid kmx_plus structures. That said, we are also responsible for generating said structures in kmc, so perhaps this is still appropriate (and certainly early-fail makes it easier to track down _why_ a file is invalid!)

2023-01-07 00:09 UTC, mcdurdin commented on core/src/kmx/kmx_plus.cpp
>      return nullptr;
```suggestion
  if (!data) {
    DebugLog("!data");
    assert(false);
    return nullptr;
```

2023-01-07 00:09 UTC, mcdurdin commented on core/src/kmx/kmx_plus.cpp
>    }
```suggestion
  if (length < LDML_LENGTH_HEADER) {
    DebugLog("length < LDML_LENGTH_HEADER");
    assert(false);
    return nullptr;
  }
```

2023-01-07 00:09 UTC, mcdurdin commented on core/src/kmx/kmx_plus.cpp
>    }
```suggestion
  if (!all->valid(length)) {
    DebugLog("header failed validation");
    assert(false);
    return nullptr;
  }
```

2023-01-07 00:09 UTC, mcdurdin commented on core/src/kmx/kmx_plus.cpp
>      return nullptr;
```suggestion
  if (all->ident != ident) {
    DebugLog("header had wrong section id");
    assert(false);
    return nullptr;
```

2023-01-07 00:09 UTC, mcdurdin commented on core/src/kmx/kmx_plus.cpp
>      return nullptr;
```suggestion
  if (length < sizeof(T)) { // Does not include dynamic data. First check.
    DebugLog("length < sizeof(section)");
    assert(false);
    return nullptr;
```

2023-01-07 00:09 UTC, mcdurdin commented on core/src/kmx/kmx_plus.cpp
>      return nullptr;
```suggestion
  if (rawbytes == nullptr) {
    DebugLog("section_from_sect(nullptr) == nullptr");
    assert(false);
    return nullptr;
```

2023-01-07 00:09 UTC, mcdurdin commented on core/src/kmx/kmx_plus.cpp
>    }
```suggestion
  if (size < LDML_LENGTH_HEADER) {
    DebugLog("size < LDML_LENGTH_HEADER");
    assert(false);
    return false;
  }
```

2023-01-07 00:09 UTC, mcdurdin commented on core/src/kmx/kmx_plus.cpp
>      return false;
```suggestion
  if (size > length) {
    DebugLog("size > length");
    assert(false);
    return false;
```

2023-01-07 00:09 UTC, mcdurdin commented on core/src/kmx/kmx_plus.cpp
>    }
```suggestion
  if (header.size < sizeof(*this)+(sizeof(entries[0])*count)) {
    DebugLog("header.size < expected size");
    assert(false);
    return false;
  }
```

2023-01-07 00:09 UTC, mcdurdin commented on core/src/kmx/kmx_plus.cpp
>    }
```suggestion
  if (header.size < sizeof(*this)+(sizeof(entries[0])*count)) {
    DebugLog("header.size < expected size");
    assert(false);
    return false;
  }
```

2023-01-07 00:09 UTC, mcdurdin commented on core/src/kmx/kmx_plus.cpp
>    }
```suggestion
  if (header.size < sizeof(*this)+(sizeof(entries[0])*count)) {
    DebugLog("header.size < expected size");
    assert(false);
    return false;
  }
```

2023-01-07 00:09 UTC, mcdurdin commented on core/src/kmx/kmx_plus.cpp
>        return false;
```suggestion
    if(start[length] != 0) {
      DebugLog("#0x%X: String of length 0x%x not null terminated", i, length);
      assert(start[length] == 0);
      return false;
```

2023-01-07 00:09 UTC, mcdurdin commented on core/src/kmx/kmx_plus.cpp
>      return nullptr;
```suggestion
  if (elementNumber >= count) {
    DebugLog("ERROR: COMP_KMXPLUS_ELEM::getElementList(%d) >= count %d", elementNumber, count);
    assert(false);
    return nullptr;
```

2023-01-07 00:09 UTC, mcdurdin commented on core/src/ldml/ldml_processor.cpp
>            return;
```suggestion
        if (nullptr == kplus.strs) {
          DebugLog("for keys: kplus.strs == nullptr"); // need a string table to get strings
          assert(false);
          return;
```

2023-01-07 00:09 UTC, mcdurdin commented on core/src/ldml/ldml_processor.cpp
>      }
```suggestion
    if (nullptr == kplus.elem) {
      DebugLog("for tran: kplus.elem == nullptr");
      assert(false);
      return;
    }
```

2023-01-07 00:09 UTC, mcdurdin commented on core/src/ldml/ldml_processor.cpp
>        return;
```suggestion
    if (nullptr == kplus.strs) {
      DebugLog("for tran: kplus.strs == nullptr"); // need a string table to get strings
      assert(false);
      return;
```

2023-01-07 00:09 UTC, mcdurdin commented on core/src/ldml/ldml_processor.cpp
>          return;
```suggestion
      if (elemNo >= kplus.elem->count) {
        DebugLog("tran[%d].from = %d, out of range for elem->count=%d", i, elemNo, kplus.elem->count);
        assert(false);
        return;
```

2023-01-07 00:09 UTC, mcdurdin commented on core/src/ldml/ldml_processor.cpp
>        }
```suggestion
      if (elemList == nullptr) {
        DebugLog("tran[%d].from = %d, could not load element list", i, elemNo);
        assert(false);
        return;
      }
```

2023-01-07 00:09 UTC, mcdurdin commented on core/src/ldml/ldml_processor.cpp
>          return;
```suggestion
      if (elemListLength == 0) {
        DebugLog("tran[%d].from = %d, element list has 0 length", i, elemNo);
        assert(false);
        return;
```

2023-01-08 04:52 UTC, srl295 commented
> I'm fiddling here...

🎻 

> One could also define an `assert_false_and_return(retval, logmessage, ...)` macro which would bundle that DebugLog(), assert(), return pattern. (May need two versions, one which does a plain `return;`.) I think this could be a good strategy, and enforce a consistent pattern of use.

it would actually be something like the `test_assert…` calls, but would end up with assert(false) instead of test failure.

> In lieu of that, I went through and moved the assertion in each case _after_ the `DebugLog` so that the last debug log message relates directly to the assertion.

yeah that was the other way i was considering.

> I'm not 100% _sure_ that all the assertions here are appropriate -- assertions shouldn't typically be used for input data validation, but for program logic validation, and some of these assertions are being thrown for invalid kmx_plus structures. That said, we are also responsible for generating said structures in kmc, so perhaps this is still appropriate (and certainly early-fail makes it easier to track down _why_ a file is invalid!)

i hear you, but actually *all* of these are for invalid kmx_plus structures. To quote @mcdurdin (emphasis mine) 
> We should consider assert()ing these (_when invalid section data is encountered_) as they indicate an error which it'd be good to catch in a debug build.

The asserts are noops in release mode (right? right??) so no harm is done there.   I'd think unless/until kmx_plus.cpp is expected to have some sort of `validate_with_results()` call (that gives internal state about why validation failed),  assert(false) at least gives you an abort / debugger trap at the failing source line.

2023-01-17 09:31 UTC, mcdurdin commented
> i hear you, but actually _all_ of these are for invalid kmx_plus structures.

Gotcha. That's what I get for trying to do reviews when I am in 'moving' mode... Yes, all looks good to me then.

2023-01-17 09:31 UTC, mcdurdin commented
> asserts are noops in release mode (right? right??)

Yep

2023-01-17 15:15 UTC, srl295 commented
> > i hear you, but actually _all_ of these are for invalid kmx_plus structures.
> 
> Gotcha. That's what I get for trying to do reviews when I am in 'moving' mode... Yes, all looks good to me then.

can i get a stamp then? thanks

2023-01-18 09:07 UTC, mcdurdin approved these changes

2023-01-18 14:58 UTC, merged

2023-01-18 14:58 UTC, srl295 commented
that's _the_ stamp