fix(linux): html tags in package description in keyboard's About page
keymanapp/keyman pull request #8057
Opened 2023-01-20 09:58 UTC by TheSchlunz

This change fixes a bug where html tags were shown in the package description in a keyboard's About page.

Fixes #4769

# User Testing
## Preparations
  - install "khmer_angkor" keyboard 
 
## Tests

**TEST_NO_HTML_TAGS**: no html tags are shown in the package description in keyboard's About page
  - start `km-config`
  - select "Khmer Angkor" keyboard
  - click "About" button
  - verify that no html tags are shown in the package description

2023-01-20 10:01 UTC, keyman-server commented
This pull request is from an external repo and will not automatically be built. The build must still be passed before it can be merged. Ask one of the team members to make a manual build of this PR.

2023-01-20 10:54 UTC, ermshiperete requested changes
LGTM. The only question I have is if this isn't overkill. Another approach would be to remove everything between `<` and `>`, but I'm torn which way is better.

Anyways, this change introduces a new dependency, so we'll have to update the documentation (`docs/linux/keyman-config.md`) and the files that list dependencies (`linux/build/agent/dependencies.config` and `linux/debian/control`).

BeautifulSoup is available as Ubuntu package python3-bs4.

2023-01-20 14:10 UTC, TheSchlunz commented
Removing everything between `<` and `>` is actually what I did first but stuff like this still looked bad because some text was just connected afterwards:
![image](https://user-images.githubusercontent.com/63309602/213716823-e119c400-f4ed-4eb2-83bc-758e72569da8.png)

2023-01-20 16:06 UTC, ermshiperete approved these changes

2023-01-21 10:21 UTC, mcdurdin commented
I don't think we can fix the inclusion of HTML tags like this. There is also potential for hyperlinks, images, and other content there.

I think it would be better to consider updates to the .keyboard_info spec to either exclude rich text, or move to Markdown.

2023-01-23 06:27 UTC, ermshiperete commented
I just noticed that on Linux we're displaying different text from Windows, so the solution might be to simply change what we display.

2023-01-23 07:29 UTC, mcdurdin commented
> I just noticed that on Linux we're displaying different text from Windows, so the solution might be to simply change what we display.

Yes, on Windows, the details from the .keyboard_info / api.keyman.com response are never shown in the keyboard info; only the package description from the .kps is shown. This would be a better solution IMO.

2023-01-23 07:29 UTC, mcdurdin requested changes
Change package description to reading data from kmp.json file. (In fact, we should avoid storing the .keyboard_info data, given that is coming from api.keyman.com, which is not available for side-loaded keyboards.)

2023-01-23 08:40 UTC, ermshiperete commented
Closing this PR since we're displaying the wrong data in the first place.

2023-01-23 08:40 UTC, closed without merging

2023-01-23 14:29 UTC, ermshiperete commented
> Change package description to reading data from kmp.json file. (In fact, we should avoid storing the .keyboard_info data, given that is coming from api.keyman.com, which is not available for side-loaded keyboards.)

@mcdurdin  I'm confused. `kmp.json` doesn't contain anything useful to display for the package description. `khmer_angkor.json` contains a description field, which is what we're already displaying. I can't find the text that Windows displays in the installed keyboard folder. Or are you saying that Windows should do it differently?

2023-01-24 06:57 UTC, mcdurdin commented
True, the only thing that Windows shows right now is the "Message" from the .kmx. We plan to merge the .keyboard_info and .kps metadata in 17.0, so let's hold off on these changes for now.