chore(windows): remove WM_UNICHAR completley
keymanapp/keyman pull request #8744
Opened 2023-05-10 12:57 UTC by rc-swag

Fixes: #8677

2023-05-11 02:01 UTC, mcdurdin reviewed
very quick comments from our paired review

2023-05-11 02:01 UTC, mcdurdin commented on windows/src/engine/keyman32/appint/aiWin2000Unicode.cpp
>  #define KEYMAN_MOREPOST	"WM_KMMOREPOST"
delete this too

2023-05-11 02:01 UTC, mcdurdin commented on windows/src/engine/keyman32/k32_dbg.cpp
> -"WM_UNICHAR"
don't delete this :)

2023-05-11 02:01 UTC, mcdurdin commented on windows/src/engine/keyman32/k32_dbg.cpp
> -      (int) msg->time,
leave this as is, don't delete

2023-05-11 02:01 UTC, mcdurdin commented on windows/src/test/manual-tests/msghooklister/src/App/wm_messages.h
> -	TEXT("WM_UNICHAR"),
leave this -- it's indexed to message ids

2023-05-11 04:56 UTC, mcdurdin requested changes

2023-05-11 04:56 UTC, mcdurdin commented on windows/src/engine/keyman32/k32_dbg.cpp
> -      (int) msg->time,
this code hasn't yet been restored

2023-05-15 08:49 UTC, bharanidharanj commented
# Test Results

* **TEST_TAMIL_OUTPUT (PASSED):** Tested with the attached PR build (Keyman 17.0.87-alpha-test-8744) in Windows 11 OS (VM) and here is my observation: 1. Installed Tamil 99 keyboard. 2. Able to use Tamil keyboard in the Notepad app as well as in the Firefox browser. Thanks, Ross.

..in NotePad
<img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/e79f0771-eeda-43a2-8bf3-449f5a724c66">


..in Firefox browser

<img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/a9ba1b72-9bb2-4081-ab81-0915fea274b8">

* **TEST_KHMER_ANGKOR (PASSED):** 1. Installed Khmer Angkor keybord. 2. Able to use the Khmer Angkor keyboard to type in khmer in the Notepad app as well as in the Firefox browser. Seems to be working fine. Thanks. 

..in Notepad

<img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/44dbec2b-10d3-495c-893a-544b0e53502d">


.. Firefox browser

<img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/e2cb918f-16ef-4afc-8428-42e2438ca7d7">

2023-05-15 23:52 UTC, merged