refactor(linux): Allow to install keyboard for multiple languages
keymanapp/keyman pull request #9017
Opened 2023-06-14 09:51 UTC by ermshiperete

This change makes it possible to install the same keyboard again for a different language. It won't be visible in the GUI if the keyboard is installed for more than language, but it will show up for the installed languages in the keyboard dropdown.

Closes #8619.

# User Testing

## Preparations

- The tests should be run on these Linux platforms:
  - **GROUP_JAMMY_X11**: Ubuntu 22.04 Jammy with Gnome Shell and X11
  - **GROUP_LUNAR_WAYLAND**: Ubuntu 23.04 Lunar with Gnome Shell and Wayland
  - **GROUP_WASTA**: Wasta 20.04 with Cinnamon

- [Install build artifacts of this PR](https://github.com/keymanapp/keyman/wiki/How-to-test-artifacts-from-pull-requests-for-Keyman-for-Linux)

- Reboot
- Install EuroLatin (SIL) keyboard for German

## Tests

**TEST_INSTALL**: Install same keyboard for different language

- Open Keyman Configuration
- Press Download button
- Search for French and install EuroLatin (SIL) keyboard for French
- Verify that EuroLatin (SIL) shows up once in Keyman Configuration
- Verify that the keyboards dropdown shows both German as well as French with the EuroLatin (SIL) keyboard

**TEST_UNINSTALL**: Uninstall the keyboard removes it for all languages

- Open Keyman Configuration
- Uninstall EuroLatin (SIL) keyboard
- Verify that EuroLatin (SIL) no longer shows up in Keyman Configuration
- Verify that the keyboards dropdown no longer shows German and French with the EuroLatin (SIL) keyboard

2023-06-15 11:07 UTC, bharanidharanj commented
### GROUP_JAMMY_X11: Ubuntu 22.04 Jammy with Gnome Shell and X11

* **TEST_INSTALL_UI (PASSED):** Tested with the attached PR build (17.0.125-alpha-local (package version 17.0.125-1~PR-9017+jammy7) in Ubuntu 22.04 (Ubuntu on Xorg) and here is my observation: 1. Verified that the keyboards dropdown shows both German as well as French with the EuroLatin (SIL) keyboard. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/1b6894c1-73ca-414a-93ff-29ca3d09955a">

* **TEST_INSTALL_CLI (PASSED):** Verified that the keyboards dropdown shows Italian in addition to German and French with the EuroLin (SIL) keyboard.

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/8baa486e-6958-40d3-82bc-bd7ed1aff699">

* **TEST_INSTALL_SHARED_CLI (PASSED):** Verified that the EuroLatin (SIL) is listed twice, once in the User area as well as in the Shared area. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/4f77d1fb-d009-4e45-82bc-b9310d913a77">

* **TEST_INSTALL_SHARED_CLI2 (PASSED):** Verified that the keyboards dropdown shows German, French, Italian, Swedish and Swiss German with the EuroLatin (SIL)

   <img widt="300" src="https://github.com/keymanapp/keyman/assets/19683143/22fd4174-d1e7-44f9-8b03-9797b1e3722c">

* **TEST_UNINSTALL_UI (PASSED):** Verified that the Swedish and Swiss German keyboard only appears in the dropdown lisbox. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/62719988-317e-4593-b873-675591438160">

* **TEST_UNINSTALL_CLI (PASSED):** 1. Verified that the Keyboards dropdown shows German with the EuroLatin (SIL) keyboard in addition to Swiss German and Swedish. 2. Verified that the keyboards dropdown shows only German with the EuroLatin (SIL) keyboard. 

..with swedish, swiss, german

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/17868ed5-c09d-4e03-affb-9dea56ed7ff4">


..without swedish, swiss, german

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/cdbfc391-59fd-4d4e-96c8-e82d80eab6c0">

2023-06-15 14:11 UTC, bharanidharanj commented
### GROUP_WASTA: Wasta 20.04 with Cinnamon

* **TEST_INSTALL_UI (FAILED):** Tested with the attached PR build (17.0.125-alpha-local (package version 17.0.125-1~PR-9017+focal7) in Wasta 20.04 with Cinnamon (VM) and here is my observation: 1. Noticed that German EuroLatin (SIL) keyboard is missing in the drop down list box. 

     <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/1d151eea-696b-45f6-9095-a6cf892e6ad0">

* **TEST_INSTALL_CLI (PASSED):** Verified that the keyboards dropdown shows Italian in addition to French with the EuroLatin (SIL) keyboard. 
  
   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/67ad82bb-f277-4c21-a2da-94126805512f">


* **TEST_INSTALL_SHARED_CLI (PASSED):** Verified that the EuroLatin (SIL) is listed twice, once in the User area as well as in the Shared area. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/29f4b602-ffcf-4cac-ada9-f372df34daca">


* **TEST_INSTALL_SHARED_CLI2 (PASSED):** Verified that the keyboards dropdown shows German, French, Italian, Swedish and Swiss German with the EuroLatin (SIL)
   
   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/795fb6d0-1445-4dea-b24b-dc51658d082c">


* **TEST_UNINSTALL_UI (PASSED):** Verified that the Swedish and Swiss German keyboard only appears in the dropdown list box. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/ac702408-cd19-4122-93f4-39cf39f7fe03">


* **TEST_UNINSTALL_CLI (FAILED):** 1. Verified that the Keyboards dropdown shows German with the EuroLatin (SIL) keyboard in addition to Swiss German and Swedish. 2. Noticed that the keyboards dropdown shows German with the EuroLatin (SIL) keyboard with Swiss German and Swedish keyboards. 

....with Swiss German and Swedish keyboards

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/97c3fc04-f475-454b-8570-678749bfedf8">


..Swiss German and Swedish keyboard still appear

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/a13339b2-bb85-477e-bc75-581016f2cb66">

2023-06-15 14:57 UTC, bharanidharanj commented
# Test Results

### GROUP_LUNAR_WAYLAND: Ubuntu 23.04 Lunar with Gnome Shell and Wayland

* **TEST_INSTALL_UI (FAILED):** Tested with the attached PR build (17.0.125-alpha-local (package version 17.0.125-1~PR-9017+lunar7) in Ubuntu 23.04 Lunar Linux OS and here is my observation : Noticed that the German EuroLatin (SIL) keyboard is missing in the drop down list box. 

    <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/3ff84aee-3039-4bb9-a8c7-68569b79484a">


* **TEST_INSTALL_CLI (FAILED):** Verified that the keyboards dropdown shows Italian in addition to French with the EuroLin (SIL) keyboard. 

<img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/26fad749-72f7-4d7e-b50d-fc85be4a30a0">


* **TEST_INSTALL_SHARED_CLI (PASSED):** Verified that the EuroLatin (SIL) is listed twice, once in the User area as well as in the Shared area. 

<img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/ba576e17-d6b2-425a-aa48-9721046b7c75">


* **TEST_INSTALL_SHARED_CLI2 (PASSED):** Verified that the keyboards dropdown showsFrench, Italian, Swedish and Swiss German with the EuroLatin (SIL)

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/7ba40656-e30c-4eae-ba6e-93676d23d7f1">


* **TEST_UNINSTALL_UI (PASSED):** Verified that the Swedish and Swiss German keyboard only appears in the dropdown lisbox. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/2f8837a3-7efc-4aa2-bd43-d77e4faf4420">


* **TEST_UNINSTALL_CLI (PASSED):** 1. Verified that the Keyboards dropdown shows German with the EuroLatin (SIL) keyboard in addition to Swiss German and Swedish. 2.Verified that the keyboards dropdown shows only German with the EuroLatin (SIL) keyboard. 

..with Swiss German and Swedish

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/76a9ce2b-8d2b-42c2-a506-6d3f5b380b50">


..without Swiss German and Swedish
   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/12963d91-2f91-4cb8-8021-632c6e890a39">

2023-06-16 09:49 UTC, darcywong00 commented on linux/keyman-config/keyman_config/uninstall_kmp.py
> +        logging.info(f'Uninstalling {where} keyboard: {packageID}')
Would it be cleaner to move the logging inside l.57?

2023-06-19 02:12 UTC, mcdurdin requested changes

2023-06-19 02:12 UTC, mcdurdin commented on linux/keyman-config/keyman_config/uninstall_kmp.py
> +        removeLanguages (str): if True also uninstall the languages associated with
```suggestion
        removeLanguages (boolean): if True also uninstall the languages associated with
```

2023-06-19 02:12 UTC, mcdurdin commented on linux/keyman-config/km-package-install
> +            if parse_version(installed_kmp_ver) > parse_version(kbdata_version):
Concur with @darcywong00 here

2023-06-29 14:37 UTC, ermshiperete commented
The TEST_INSTALL_UI tests failed because of #9114. Modified the preparation instruction to install Spanish instead of German.

GROUP_LUNAR_WAYLAND:
TEST_INSTALL_UI (Skipped): Ignoring failure caused by #9114 

GROUP_WASTA:
TEST_INSTALL_UI (Skipped): Ignoring failure caused by #9114

2023-06-29 19:21 UTC, darcywong00 approved these changes
lgtm

2023-07-05 04:30 UTC, mcdurdin approved these changes

2023-07-05 16:55 UTC, ermshiperete commented
@keymanapp-test-bot retest

2023-07-06 10:42 UTC, bharanidharanj commented
### GROUP_JAMMY_X11: Ubuntu 22.04 Jammy with Gnome Shell and X11

* **TEST_INSTALL_UI (PASSED):** Tested with the attached PR build (17.0.125-alpha-local (package version 17.0.134-alpha-local (package version 17.0.134-1~PR-9017+jammy26) in Ubuntu 22.04 (Ubuntu on Xorg) and here is my observation: 1. Verified that the keyboards dropdown shows both Spanish as well as French with the EuroLatin (SIL) keyboard.

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/cacd136f-1a42-4ded-9543-a9e1b479cd08">


* **TEST_INSTALL_CLI (PASSED):** Verified that the keyboards dropdown shows Italian in addition to German and French with the EuroLin (SIL) keyboard.

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/d89e3ab6-421b-4405-9540-31f0a396c9ec">


* **TEST_INSTALL_SHARED_CLI (PASSED):** Verified that the EuroLatin (SIL) is listed twice, once in the User area as well as in the Shared area.

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/df483db3-7c92-4635-913d-ace7d1bbb475">


* **TEST_INSTALL_SHARED_CLI2 (PASSED):** Verified that the keyboards dropdown shows German, French, Italian, Swedish and Swiss German with the EuroLatin (SIL)

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/c245449b-9019-4caa-8460-4be77378815c">


* **TEST_UNINSTALL_UI (PASSED):** Verified that the Swedish and Swiss German keyboard only appears in the dropdown listbox.

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/01ad7b2d-ec6e-423a-b319-f5540c458bad">


* **TEST_UNINSTALL_CLI (PASSED):** 1. Verified that the Keyboards dropdown shows German with the EuroLatin (SIL) keyboard in addition to Swiss German and Swedish. 2. Verified that the keyboards dropdown shows only German with the EuroLatin (SIL) keyboard.

..Uninstall_CLI1

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/d1cbb6b4-7bb4-42dd-96f4-3f9e38997075">


..Uninstall_CLI2

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/8e2afb70-176d-41ad-951a-dd33f3e82792">

2023-07-06 11:15 UTC, bharanidharanj commented
### GROUP_LUNAR_WAYLAND: Ubuntu 23.04 Lunar with Gnome Shell and Wayland

* **TEST_INSTALL_UI (PASSED):** Tested with the attached PR build (17.0.134-alpha-local (package version 17.0.134-alpha-local (package version 17.0.134-1~PR-9017+lunar26) in Ubuntu 23.10 (Wayland) and here is my observation: 1. Verified that the keyboards dropdown shows both Spanish as well as French with the EuroLatin (SIL) keyboard.

* **TEST_INSTALL_CLI (PASSED):** Verified that the keyboards dropdown shows Italian in addition to German and French with the EuroLin (SIL) keyboard.

* **TEST_INSTALL_SHARED_CLI (PASSED):** Verified that the EuroLatin (SIL) is listed twice, once in the User area as well as in the Shared area.

* **TEST_INSTALL_SHARED_CLI2 (PASSED):** Verified that the keyboards dropdown shows German, French, Italian, Swedish and Swiss German with the EuroLatin (SIL)

* **TEST_UNINSTALL_UI (PASSED):** Verified that the Swedish and Swiss German keyboard only appears in the dropdown listbox.

* **TEST_UNINSTALL_CLI (PASSED):** 1. Verified that the Keyboards dropdown shows German with the EuroLatin (SIL) keyboard in addition to Swiss German and Swedish. 2. Verified that the keyboards dropdown shows only German with the EuroLatin (SIL) keyboard.

2023-07-06 11:56 UTC, bharanidharanj commented
# Test Results

### GROUP_WASTA: Wasta 20.04 with Cinnamon

* **TEST_INSTALL_UI (PASSED):** Tested with the attached PR build (17.0.134-alpha-local (package version 17.0.134-1~PR-9017+focal26) in Ubuntu 20.04 with Cinnamon and here is my observation: 1. Verified that the keyboards dropdown shows both Spanish as well as French with the EuroLatin (SIL) keyboard.


* **TEST_INSTALL_CLI (PASSED):** Verified that the keyboards dropdown shows Italian in addition to German and French with the EuroLin (SIL) keyboard.


* **TEST_INSTALL_SHARED_CLI (PASSED):** Verified that the EuroLatin (SIL) is listed twice, once in the User area as well as in the Shared area.


* **TEST_INSTALL_SHARED_CLI2 (PASSED):** Verified that the keyboards dropdown shows German, French, Italian, Swedish and Swiss German with the EuroLatin (SIL)


* **TEST_UNINSTALL_UI (PASSED):** Verified that the Swedish and Swiss German keyboard only appears in the dropdown listbox.


* **TEST_UNINSTALL_CLI (PASSED):** 1. Verified that the Keyboards dropdown shows German with the EuroLatin (SIL) keyboard in addition to Swiss German and Swedish. 2. Verified that the keyboards dropdown shows only German with the EuroLatin (SIL) keyboard.

2023-07-06 14:37 UTC, merged

2023-07-06 18:30 UTC, keyman-server commented
Changes in this pull request will be available for download in [Keyman version 17.0.135-alpha](https://keyman.com/downloads/releases/alpha/17.0.135)