Add Core API version number 🎬
keymanapp/keyman pull request #9867
Opened 2023-10-26 15:45 UTC by ermshiperete

- Add Core API version number
- Add additional checks for the symbols file:
  - if a line with a method name gets changed, the package version number
    in that line also needs to be updated
  - for major API changes (methods renamed or removed) the API version
    numbers needs to be incremented
  - the API version numbers in the .symbols file and in `CORE_API_VERSION.md`
    need to match

Closes #9801

@keymanapp-test-bot skip

2023-10-27 01:16 UTC, mcdurdin requested changes
Given the changes to trigger-builds impacts all platforms and every build, I would like to split them out into a separate branch for discussion and review. The changes shouldn't be buried.

I haven't yet reviewed the other aspects of this PR

2023-10-27 13:29 UTC, ermshiperete commented
I split out the Core API version change into #9877.

2023-11-01 01:48 UTC, mcdurdin commented on linux/scripts/deb-packaging.sh
> +  "--git-base=GIT_BASE        The ref of the base commit, e.g. HEAD of the master branch (for verify action)"
Should these be SHAs or commitishes/refs, tag names, branch names or what? :grin:

2023-11-01 01:48 UTC, mcdurdin commented on linux/scripts/deb-packaging.sh
> +  "--git-base=GIT_BASE        The ref of the base commit, e.g. HEAD of the master branch (for verify action)"
```suggestion
  "--git-ref=GIT_REF          The SHA of the HEAD commit, e.g. of the PR branch (for verify action)" \
  "--git-base=GIT_BASE        The ref of the base commit, usually the name of the base branch, e.g. master, stable-16.0 (for verify action)"
```

2023-11-01 01:48 UTC, mcdurdin commented on linux/scripts/deb-packaging.sh
> +is_symbols_file_changed() {
```suggestion
#
# Compare the SHA of the base and head commits for changes to the .symbols file
#
is_symbols_file_changed() {
```

2023-11-01 01:48 UTC, mcdurdin commented on linux/scripts/deb-packaging.sh
> +  tmpDir=$(mktemp -d)
Cleanup?

2023-11-01 01:48 UTC, mcdurdin commented on linux/scripts/deb-packaging.sh
> +    if ! git log -p -1 -- "debian/${PKG_NAME}.symbols" | grep -q "${PKG_VERSION}"; then
`${PKG_VERSION}` could just be `${VERSION}` I think? And then we can eliminate all of that from this script?

2023-11-01 01:48 UTC, mcdurdin commented on linux/scripts/deb-packaging.sh
> +    # we hope this gets flagged in code review.
```suggestion
    # .symbols file changed, now check if the package version got updated as well
    # Note: We don't check that ALL changes in that file have an updated package version -
    # we hope this gets flagged in code review.
    # Note: This version number check may not match the actual released version, if the branch
    # is out of date when it is merged to the release branch (master/beta/stable-x.y). If this
    # is considered important, then make sure the branch is up to date, and wait for test
    # builds to complete, before merging.
```

2023-11-01 01:48 UTC, mcdurdin commented on linux/scripts/deb-packaging.sh
> +  firstline=$(head -1 "debian/${PKG_NAME}.symbols")
```suggestion
  firstline="$(head -1 "debian/${PKG_NAME}.symbols")"
```

2023-11-13 23:33 UTC, mcdurdin approved these changes

2023-11-13 23:33 UTC, mcdurdin commented on linux/scripts/deb-packaging.sh
> +  git checkout "${GIT_SHA}" -- "debian/${PKG_NAME}.symbols"
We could reduce the number of checkouts by switching order of operations here, but it's not terribly important.

2023-11-14 09:26 UTC, merged

2023-11-14 18:14 UTC, keyman-server commented
Changes in this pull request will be available for download in [Keyman version 17.0.210-alpha](https://keyman.com/downloads/releases/alpha/17.0.210)